'use client';

/**
 * Ad Templates tab — which ad templates actually get used, and by whom.
 *
 * The question this answers is a library-management one, not a media one: of the
 * plates the design team maintains, which earn their keep, which the automation
 * leans on, and which get built from and then thrown away. Everything here is
 * derived from ads that already exist (`AdCreative.templateId` + `autoGenerated`
 * + `archivedAt`), so nothing new is tracked to produce it.
 *
 * Deliberately NOT date-ranged like the platform reports. Usage is a lifetime
 * property of a template — "this plate has produced 240 ads" is the useful fact,
 * and slicing it to the last 28 days would mostly report on when the automation
 * last ran. The shared range controls stay visible for consistency but don't
 * filter this view, which the subtitle says out loud.
 *
 * Arriving from a template's ⋯ → Analytics focuses that row (`?template=<id>`).
 */

import { useMemo } from 'react';
import useSWR from 'swr';
import { useSearchParams } from 'next/navigation';
import {
  RectangleGroupIcon,
  SparklesIcon,
  HandRaisedIcon,
  ArchiveBoxIcon,
  CheckCircleIcon,
  ChartBarIcon,
} from '@heroicons/react/24/outline';
import { fetcher, num, Kpi, Section, EmptyState, LoadingState, DataTable, Muted, prettyDate } from './shared';
import type { ReportComponentProps } from './reports-config';

interface Usage {
  templateId: string;
  total: number;
  auto: number;
  manual: number;
  ready: number;
  archived: number;
  lastUsedAt: string | null;
}
interface DocTemplate {
  id: string;
  name: string;
  status: string;
  accountKey: string | null;
}

/** Share of `n` in `total`, as a whole-percent string. Guards divide-by-zero. */
const share = (n: number, total: number) => (total > 0 ? `${Math.round((n / total) * 100)}%` : '—');

export function AdTemplatesReport({ accountKey }: ReportComponentProps) {
  const params = useSearchParams();
  const focusId = params.get('template');

  const { data: usageData, isLoading: usageLoading } = useSWR<{ usage: Usage[] }>(
    accountKey
      ? `/api/ad-generator/templates-doc/usage?accountKey=${encodeURIComponent(accountKey)}`
      : '/api/ad-generator/templates-doc/usage',
    fetcher,
  );
  // Names come from the library; usage is keyed by id alone.
  const { data: tplData, isLoading: tplLoading } = useSWR<{ templates: DocTemplate[] }>(
    accountKey
      ? `/api/ad-generator/templates-doc?all=1&accountKey=${encodeURIComponent(accountKey)}`
      : '/api/ad-generator/templates-doc?all=1',
    fetcher,
  );

  const rows = useMemo(() => {
    const usage = usageData?.usage ?? [];
    const nameById = new Map((tplData?.templates ?? []).map((t) => [t.id, t.name]));
    return usage
      .map((u) => ({
        ...u,
        // A code template (single-offer, dual-offer…) has no library row; show
        // its id rather than dropping ads that genuinely came from it.
        name: nameById.get(u.templateId) ?? u.templateId,
      }))
      .sort((a, b) => b.total - a.total || a.name.localeCompare(b.name));
  }, [usageData, tplData]);

  const totals = useMemo(
    () =>
      rows.reduce(
        (acc, r) => ({
          ads: acc.ads + r.total,
          auto: acc.auto + r.auto,
          ready: acc.ready + r.ready,
          archived: acc.archived + r.archived,
          used: acc.used + (r.total > 0 ? 1 : 0),
        }),
        { ads: 0, auto: 0, ready: 0, archived: 0, used: 0 },
      ),
    [rows],
  );

  if (usageLoading || tplLoading) return <LoadingState />;

  if (!rows.length) {
    return (
      <EmptyState
        icon={RectangleGroupIcon}
        title="No ads have been built yet"
        body="Once ads are created from a template — by hand or by the automation — their usage shows up here."
      />
    );
  }

  const focusRow = focusId ? rows.find((r) => r.templateId === focusId) : undefined;

  return (
    <div className="space-y-6">
      {/* Arrived from one template's ⋯ menu — lead with that template, then keep
          the full library below for context. */}
      {focusId && (
        <Section title={focusRow?.name ?? 'That template'} subtitle="Opened from the template library" icon={RectangleGroupIcon}>
          {focusRow ? (
            <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
              <Kpi icon={ChartBarIcon} label="Ads built" value={num(focusRow.total)} tone="primary" />
              <Kpi icon={SparklesIcon} label="By automation" value={num(focusRow.auto)} secondary={share(focusRow.auto, focusRow.total)} tone="violet" />
              <Kpi icon={HandRaisedIcon} label="By hand" value={num(focusRow.manual)} secondary={share(focusRow.manual, focusRow.total)} tone="sky" />
              <Kpi icon={ArchiveBoxIcon} label="Archived" value={num(focusRow.archived)} tone="amber" />
            </div>
          ) : (
            <Muted>No ads have been built from this template yet.</Muted>
          )}
        </Section>
      )}

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">
        <Kpi icon={RectangleGroupIcon} label="Templates used" value={num(totals.used)} secondary={`of ${num(rows.length)}`} tone="primary" />
        <Kpi icon={ChartBarIcon} label="Ads built" value={num(totals.ads)} tone="sky" />
        <Kpi icon={SparklesIcon} label="By automation" value={num(totals.auto)} secondary={share(totals.auto, totals.ads)} tone="violet" />
        <Kpi icon={CheckCircleIcon} label="Reached ready" value={num(totals.ready)} secondary={share(totals.ready, totals.ads)} tone="emerald" />
        <Kpi icon={ArchiveBoxIcon} label="Archived" value={num(totals.archived)} tone="amber" />
      </div>

      <Section
        title="Usage by template"
        subtitle="Lifetime totals — not filtered by the date range above"
        icon={RectangleGroupIcon}
      >
        <DataTable
          head={['Template', 'Ads', 'By hand', 'Automated', 'Ready', 'Archived', 'Last used']}
          rows={rows.map((r) => [
            // Mark the row you came in on so it's findable in a long library.
            r.templateId === focusId ? `→ ${r.name}` : r.name,
            num(r.total),
            num(r.manual),
            r.auto > 0 ? `${num(r.auto)} (${share(r.auto, r.total)})` : '—',
            num(r.ready),
            r.archived > 0 ? num(r.archived) : '—',
            r.lastUsedAt ? prettyDate(r.lastUsedAt.slice(0, 10)) : '—',
          ])}
          maxRows={12}
        />
      </Section>

      <Muted>
        Counts every ad built from a template, including drafts. “Archived” means an ad was
        created and later put away — a template with a high archived share tends to read well in
        the picker but not survive a real offer.
      </Muted>
    </div>
  );
}
