'use client';

/**
 * Ad Generator — the home surface: a gallery of the active account's created
 * ads (like the Landing Pages / Templates index pages, and styled to match
 * them: sticky page header, shared ListToolbar, glass-card empty states).
 * Click an ad to open the editor (/ad-generator/[id]); "New ad" picks a
 * template and creates one. Live mini previews render through the same
 * template function the editor + export use. Behind AD_GENERATOR_ENABLED (the
 * route layout 404s when off).
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createPortal } from 'react-dom';
import { toast } from 'sonner';
import { BoltIcon, MegaphoneIcon, PlusIcon, TrashIcon, Squares2X2Icon, RectangleGroupIcon, XMarkIcon, Cog6ToothIcon, ChevronDownIcon, DocumentTextIcon, ShieldCheckIcon, ArchiveBoxIcon, ArrowUturnLeftIcon, CheckCircleIcon, PencilSquareIcon, ArrowPathIcon, LifebuoyIcon, InformationCircleIcon } from '@heroicons/react/24/outline';
import { useAccount } from '@/contexts/account-context';
import { useLoomiDialog } from '@/contexts/loomi-dialog-context';
import { openSupportModal } from '@/lib/ui-events';
import { MANAGEMENT_ROLES } from '@/lib/roles';
import { ListToolbar } from '@/components/list-toolbar';
import BulkActionDock from '@/components/bulk-action-dock';
import { AccountLogo } from '@/components/account-logo';
import { ImpersonationEscape } from '@/components/impersonation-escape';
import type { StatusFilterValue } from '@/components/status-filter';
import { AdPreviewThumb, brandingFromAccount } from '@/components/ad-generator/ad-preview-thumb';
import { ALL_TEMPLATES } from '@/lib/ad-generator/templates';
import { adTemplateFromDoc, blankTemplateDoc } from '@/lib/ad-generator/doc-template';
import { designHash, isBehindTemplate } from '@/lib/ad-generator/template-sync';
import { addFieldKit, type VehicleFieldsMode } from '@/lib/ad-generator/vehicle-fields';
import { DEFAULT_OFFER_KIND } from '@/lib/ad-generator/offer-kinds';
import { OfferKindBadge } from '@/components/ad-generator/offer-kind-badge';
import { Tooltip } from '@/app/app/tools/_shared/Tooltip';
import type { LibrarySize } from '@/lib/ad-generator/ad-size-library';
import { useSizeLibrary } from '@/lib/ad-generator/use-size-library';
import { SizePicker } from '@/components/ad-generator/size-picker';
import { kindInIndustry, offerKindsForIndustry, templateInIndustry } from '@/lib/ad-generator/industry';
import { templateInSchedule, usableForCustom } from '@/lib/ad-generator/doc-types';
import {
  facetsForAd,
  matchesFacets,
  buildFacetOptions,
  countSelected,
  offerEndsAt,
  matchesWindow,
  FACET_KEYS,
  type AdFacetValues,
  type FacetSelection,
  type OfferWindow,
} from '@/lib/ad-generator/ad-facets';
import { AdFilterPanel } from '@/components/ad-generator/ad-filter-panel';
import { GenerateOffersModal, type GenerateCandidate } from '@/components/ad-generator/generate-offers-modal';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';
import type { AdTemplate, AdData } from '@/lib/ad-generator/types';

type Creative = {
  id: string;
  name: string;
  templateId: string;
  status: string;
  updatedAt: string;
  createdByName: string | null;
  /** True when the nightly job built this rather than a person. */
  autoGenerated?: boolean;
  /** Auto-generated only: when the underlying offer stops being valid. */
  expiresAt?: string | null;
  /** Auto-generated only: why the generator held it as a draft. */
  reviewNotes?: string | null;
  /** Whether this ad still follows its source template's design. */
  templateSync?: 'synced' | 'detached';
  /** Design hash of the template revision this ad's doc came from. */
  templateDocHash?: string | null;
  /** Set when a person edited this ad's own design. */
  docEditedAt?: string | null;
  doc?: TemplateDoc | null;
  data: AdData;
};

/** Manual / automated split for the list. */
type SourceFilter = 'all' | 'manual' | 'auto';

/** A creative plus everything derived from its data, memoised for filtering. */
type FacetedCreative = Creative & { facets: AdFacetValues; endsAt: Date | null };

export default function AdGeneratorListPage() {
  const { accountKey, accountData, userRole } = useAccount();
  const isManager = !!userRole && MANAGEMENT_ROLES.includes(userRole);
  const { confirm } = useLoomiDialog();
  const router = useRouter();
  const [dbTemplates, setDbTemplates] = useState<AdTemplate[]>([]);
  /** templateId → its CURRENT design, and that design's hash (see the fetch below). */
  const [templateDocs, setTemplateDocs] = useState<Record<string, TemplateDoc>>({});
  const [templateHashes, setTemplateHashes] = useState<Record<string, string>>({});
  /** Ad id currently pulling its template's design, for the button's busy state. */
  const [syncing, setSyncing] = useState<string | null>(null);
  const [creatives, setCreatives] = useState<Creative[] | null>(null);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [scratchOpen, setScratchOpen] = useState(false);
  const [creating, setCreating] = useState(false);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilterValue>('all');
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>('all');
  const [facetSel, setFacetSel] = useState<FacetSelection>({});
  const [offerWindow, setOfferWindow] = useState<OfferWindow>('all');
  // What's standing between this sub-account and a generate run. A run needs
  // automation set up AND a template mapped, or it can only ever report zero —
  // but the entry point stays visible either way and says which piece is missing.
  // Hiding it outright sent people hunting for a menu item that wasn't there,
  // including from the automation page's own "use New ad → Generate from OEM
  // offers" empty state.
  const [automationBlocker, setAutomationBlocker] = useState<'unconfigured' | 'no-template' | null>(
    'unconfigured',
  );
  const automationReady = automationBlocker === null;
  const [generating, setGenerating] = useState(false);
  const [genOpen, setGenOpen] = useState(false);
  const [candidates, setCandidates] = useState<GenerateCandidate[]>([]);
  const [maxAdsPerRun, setMaxAdsPerRun] = useState(10);
  // Bulk selection. Ids rather than indices so it survives filtering and reloads.
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [bulkBusy, setBulkBusy] = useState(false);
  // Header dropdowns: the settings cog + the "New ad" split menu.
  const [cogOpen, setCogOpen] = useState(false);
  const [newOpen, setNewOpen] = useState(false);
  const cogRef = useRef<HTMLDivElement>(null);
  const newRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!cogOpen && !newOpen) return;
    const onDown = (e: MouseEvent) => {
      const t = e.target as Node;
      if (cogOpen && !cogRef.current?.contains(t)) setCogOpen(false);
      if (newOpen && !newRef.current?.contains(t)) setNewOpen(false);
    };
    document.addEventListener('mousedown', onDown);
    return () => document.removeEventListener('mousedown', onDown);
  }, [cogOpen, newOpen]);

  useEffect(() => {
    let cancelled = false;
    // Global templates + this account's own (dealer-branded plates etc.).
    fetch(`/api/ad-generator/templates-doc${accountKey ? `?accountKey=${encodeURIComponent(accountKey)}` : ''}`)
      .then((r) => (r.ok ? r.json() : { templates: [] }))
      .then((d: { templates?: { id: string; doc: TemplateDoc | null }[] }) => {
        if (cancelled) return;
        const withDocs = (d.templates ?? []).filter((t) => t.doc);
        setDbTemplates(withDocs.map((t) => adTemplateFromDoc(t.id, t.doc as TemplateDoc)));
        // Each template's CURRENT design, kept raw and by hash. The hash tells the
        // list which ads are on an older design; the raw doc is what an ad's card
        // must switch to after a sync, since the previews render from the ad's own
        // doc rather than from a stored image.
        setTemplateDocs(Object.fromEntries(withDocs.map((t) => [t.id, t.doc as TemplateDoc])));
        setTemplateHashes(
          Object.fromEntries(withDocs.map((t) => [t.id, designHash(t.doc as TemplateDoc)])),
        );
      })
      .catch(() => {
        if (!cancelled) {
          setDbTemplates([]);
          setTemplateDocs({});
          setTemplateHashes({});
        }
      });
    return () => {
      cancelled = true;
    };
  }, [accountKey]);

  // Resolution list (incl. retired templates) — for rendering existing ads.
  const templates = useMemo(() => [...ALL_TEMPLATES, ...dbTemplates], [dbTemplates]);
  // Picker list — the shared library (DB templates), scoped to this account's
  // industry. Code-defined starters stay in ALL_TEMPLATES (so existing ads still
  // render) but aren't offered here — the DB library is the single source (the
  // built-in/DB split and the old Ad-Types filter row were both retired).
  const pickerTemplates = useMemo(
    () =>
      dbTemplates.filter((t) => {
        if (!templateInIndustry(t, accountData?.category)) return false;
        // `adTemplateFromDoc` doesn't carry usage or schedule, so both come off
        // the raw doc. Absent doc ⇒ show it: a template we can't inspect is
        // better offered than silently withheld.
        const doc = templateDocs[t.id];
        if (!doc) return true;
        // The template's KIND has to fit the account's industry too. The
        // `industries` tag above is a filing choice and an untagged template is
        // global — but a vehicle offer's questions (VIN, lease term, cost per
        // $1,000) have no answers outside a dealership.
        if (!kindInIndustry(doc, accountData?.category)) return false;
        // The ad generator builds CUSTOM ads now. A design meant for the
        // automation expects the feed to fill it and would hand a person a form
        // of fields they have no source for.
        if (!usableForCustom(doc)) return false;
        // Seasonal windows. `TemplateDoc.schedule` has always documented itself
        // as hiding the template outside its dates, but only the automation
        // resolver honoured it — in the human library a Christmas plate showed
        // in July.
        return templateInSchedule(doc, new Date());
      }),
    [dbTemplates, templateDocs, accountData?.category],
  );

  useEffect(() => {
    if (!accountKey) {
      setCreatives([]);
      return;
    }
    let cancelled = false;
    setCreatives(null);
    // Archived ads live behind their own query rather than being filtered out
    // client-side, so an account with thousands of them doesn't ship them all.
    const archived = statusFilter === 'archived' ? '&archived=1' : '';
    fetch(`/api/ad-generator/creatives?accountKey=${encodeURIComponent(accountKey)}${archived}`)
      .then((r) => (r.ok ? r.json() : { creatives: [] }))
      .then((d: { creatives?: Creative[] }) => {
        if (!cancelled) setCreatives(d.creatives ?? []);
      })
      .catch(() => {
        if (!cancelled) setCreatives([]);
      });
    return () => {
      cancelled = true;
    };
  }, [accountKey, statusFilter]);

  // Selecting something, then filtering it out of view, would leave it queued
  // for a bulk action nobody can see. Keep the selection inside the visible set.
  useEffect(() => {
    setSelected(new Set());
  }, [accountKey]);

  // Is automation set up for this sub-account? Managers only — the endpoint is
  // admin-gated, and a 403 here should stay silent rather than toast.
  useEffect(() => {
    if (!accountKey || !isManager) {
      setAutomationBlocker('unconfigured');
      return;
    }
    let cancelled = false;
    fetch(`/api/ad-generator/automation/shadow?accountKey=${encodeURIComponent(accountKey)}`)
      .then((r) => (r.ok ? r.json() : null))
      .then(
        (
          d: {
            configured?: boolean;
            scope?: { templateMap?: Record<string, string>; maxAdsPerRun?: number };
            vehicles?: (GenerateCandidate & { liveOffers?: number })[];
          } | null,
        ) => {
          if (cancelled) return;
          setAutomationBlocker(
            !d?.configured ? 'unconfigured' : !d.scope?.templateMap?.all ? 'no-template' : null,
          );
          setMaxAdsPerRun(d?.scope?.maxAdsPerRun ?? 10);
          // Only vehicles that could actually produce an ad — on the lot with at
          // least one live offer. The dialog narrows further from there.
          setCandidates(
            (d?.vehicles ?? [])
              .filter((v) => v.stock > 0 && (v.offerTypes?.length ?? 0) > 0)
              .map((v) => ({
                year: v.year,
                make: v.make,
                model: v.model,
                stock: v.stock,
                offerTypes: v.offerTypes ?? [],
                wouldChoose: v.wouldChoose ?? null,
                wouldChooseType: v.wouldChooseType ?? null,
              })),
          );
        },
      )
      .catch(() => {
        if (!cancelled) setAutomationBlocker('unconfigured');
      });
    return () => {
      cancelled = true;
    };
  }, [accountKey, isManager]);

  async function generateFromOffers(scope: { vehicles: string[]; offerTypes: string[] }) {
    if (!accountKey) return;
    setGenerating(true);
    try {
      const res = await fetch('/api/ad-generator/automation/shadow', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountKey, action: 'generate', scope }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
      const skipped = (json.skipped ?? []).length;
      if (json.created || json.refreshed) {
        toast.success(
          `${json.created} new draft${json.created === 1 ? '' : 's'}, ${json.refreshed} refreshed` +
            (skipped ? `, ${skipped} skipped` : ''),
        );
        // Show them straight away rather than making the user reload.
        const list = await fetch(`/api/ad-generator/creatives?accountKey=${encodeURIComponent(accountKey)}`)
          .then((r) => (r.ok ? r.json() : { creatives: [] }))
          .catch(() => ({ creatives: [] }));
        setCreatives(list.creatives ?? []);
      } else {
        toast.warning(
          `No ads generated${skipped ? ` — ${skipped} vehicle(s) skipped` : ''}. See Automation → Run history.`,
        );
      }
      // The run completed either way, so the dialog has done its job. A thrown
      // error leaves it open so the same selection can be retried.
      setGenOpen(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Could not generate');
    } finally {
      setGenerating(false);
    }
  }

  function toggleSelect(id: string) {
    setSelected((cur) => {
      const next = new Set(cur);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function runBulk(action: 'archive' | 'restore' | 'delete' | 'mark_ready' | 'mark_draft') {
    const ids = selectedVisible;
    if (!ids.length) return;

    // Deletion is the one that can't be walked back — archive is reversible, and
    // a status flip is just a flip.
    if (action === 'delete') {
      const ok = await confirm({
        title: `Delete ${ids.length} ad${ids.length === 1 ? '' : 's'}?`,
        message: 'This can’t be undone. Archive them instead if you only want them out of the way.',
        confirmLabel: 'Delete',
        destructive: true,
      });
      if (!ok) return;
    }

    setBulkBusy(true);
    try {
      const res = await fetch('/api/ad-generator/creatives/bulk', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ids, action }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);

      const n = json.count ?? ids.length;
      const noun = `${n} ad${n === 1 ? '' : 's'}`;
      toast.success(
        action === 'delete'
          ? `Deleted ${noun}`
          : action === 'archive'
            ? `Archived ${noun}`
            : action === 'restore'
              ? `Restored ${noun}`
              : `Marked ${noun} ${action === 'mark_ready' ? 'ready' : 'draft'}`,
      );

      // Apply locally rather than refetching: delete/archive/restore all remove
      // the rows from the current view, and a status flip is a field update.
      const gone = action === 'delete' || action === 'archive' || action === 'restore';
      setCreatives((cur) =>
        (cur ?? [])
          .filter((c) => !(gone && ids.includes(c.id)))
          .map((c) =>
            !gone && ids.includes(c.id)
              ? { ...c, status: action === 'mark_ready' ? 'ready' : 'draft' }
              : c,
          ),
      );
      setSelected(new Set());
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Bulk action failed');
    } finally {
      setBulkBusy(false);
    }
  }

  // Account branding for the mini previews (same as the editor merges in).
  const branding: AdData = useMemo(() => brandingFromAccount(accountData), [accountData]);

  // Vehicle/offer facets + the offer deadline, derived once per ad rather than
  // on every keystroke.
  const faceted: FacetedCreative[] = useMemo(
    () =>
      (creatives ?? []).map((c) => ({
        ...c,
        facets: facetsForAd(c.data),
        endsAt: offerEndsAt(c.data, c.expiresAt),
      })),
    [creatives],
  );

  // Everything EXCEPT the facets — status, source and search. Kept separate so
  // the facet counts below describe the list you're actually looking at (search
  // for "Silverado" and the Make picker shows only the makes still in play).
  const preFacet = useMemo(() => {
    let list = faceted;
    // 'archived' is served by its own query, so there's nothing to narrow here.
    if (statusFilter === 'published') list = list.filter((c) => c.status === 'ready');
    else if (statusFilter === 'draft') list = list.filter((c) => c.status !== 'ready');
    if (sourceFilter === 'auto') list = list.filter((c) => c.autoGenerated);
    else if (sourceFilter === 'manual') list = list.filter((c) => !c.autoGenerated);
    if (offerWindow !== 'all') {
      const now = new Date();
      list = list.filter((c) => matchesWindow(c.endsAt, offerWindow, now));
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      list = list.filter((c) => {
        const t = templates.find((x) => x.id === c.templateId);
        // Vehicle too: an ad named "Momentum — July lease" should still be
        // findable by typing the car it advertises.
        const vehicles = [c.data.vehicleName, c.data.o2_vehicleName].filter((v): v is string => !!v);
        return (
          c.name.toLowerCase().includes(q) ||
          (t?.name ?? c.templateId).toLowerCase().includes(q) ||
          vehicles.some((v) => v.toLowerCase().includes(q))
        );
      });
    }
    return list;
  }, [faceted, statusFilter, sourceFilter, offerWindow, search, templates]);

  const facetOptions = useMemo(() => buildFacetOptions(preFacet, facetSel), [preFacet, facetSel]);

  // Which pickers exist at all — from the whole account list, so the bar keeps
  // a stable shape while you filter (see FacetBar's `visibleFacets`).
  const visibleFacets = useMemo(() => {
    const all = buildFacetOptions(faceted, {});
    return FACET_KEYS.filter((k) => all[k].length > 1);
  }, [faceted]);

  // Ads only have a card view, so this is the grid.
  const visible = useMemo(
    () => preFacet.filter((c) => matchesFacets(c.facets, facetSel)),
    [preFacet, facetSel],
  );

  /** Ids currently visible — what "select all" means, and what a bulk action hits. */
  const visibleIds = useMemo(() => visible.map((c) => c.id), [visible]);
  const selectedVisible = useMemo(
    () => visibleIds.filter((id) => selected.has(id)),
    [visibleIds, selected],
  );

  // Switching sub-accounts carries the old rooftop's vehicles into a store that
  // doesn't sell them — a stale "Mazda" filter would show an empty Chevrolet
  // list and read as a loading bug.
  useEffect(() => {
    setFacetSel({});
    setOfferWindow('all');
  }, [accountKey]);

  async function createAd(templateId: string) {
    if (!accountKey) {
      toast.error('Select an account first');
      return;
    }
    setCreating(true);
    try {
      const t = templates.find((x) => x.id === templateId);
      const res = await fetch('/api/ad-generator/creatives', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountKey, name: `New ${t?.name ?? 'ad'}`, templateId, data: t?.defaults ?? {} }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
      router.push(`/ad-generator/${json.creative.id}`);
    } catch (err) {
      toast.error(`Couldn't create: ${err instanceof Error ? err.message : 'unknown error'}`);
      setCreating(false);
    }
  }

  // From scratch: a blank ad (empty doc) at the chosen name + starting size(s),
  // opened straight in the builder's ad mode so the designer starts on an empty
  // canvas with no layers.
  async function createBlank(name: string, sizes: LibrarySize[], kind: string, vehicleMode: VehicleFieldsMode) {
    if (!accountKey) {
      toast.error('Select an account first');
      return;
    }
    const chosen: { name: string; width: number; height: number }[] = sizes.length
      ? sizes
      : [{ name: 'Square', width: 1080, height: 1080 }];
    setCreating(true);
    try {
      const trimmed = name.trim() || 'Untitled ad';
      const docSizes = chosen.map((size, i) => {
        const slug = size.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
        return {
          id: slug || `size-${i}`,
          label: `${size.name} ${size.width}×${size.height}`,
          width: size.width,
          height: size.height,
        };
      });
      // The offer KIND decides the field schema stamped into the doc — a general
      // ad gets headline/CTA/media, not the ~50-field vehicle offer schema.
      let doc = blankTemplateDoc(`blank-${Date.now()}`, trimmed, docSizes, kind);
      // `dual` additionally merges the parallel `o2_` question set. Only the
      // vehicle kind offers it (see `capabilities.dualOffer`), and `single` is a
      // no-op now that the kind already stamps its own schema.
      if (vehicleMode === 'dual') doc = addFieldKit(doc, 'dual');
      const res = await fetch('/api/ad-generator/creatives', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountKey, name: trimmed, templateId: 'blank', data: {}, doc }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
      router.push(`/ad-generator/builder?ad=${encodeURIComponent(json.creative.id)}${accountKey ? `&account=${encodeURIComponent(accountKey)}` : ''}&from=${encodeURIComponent('/ad-generator')}`);
    } catch (err) {
      toast.error(`Couldn't create: ${err instanceof Error ? err.message : 'unknown error'}`);
      setCreating(false);
    }
  }

  async function remove(id: string) {
    const name = (creatives ?? []).find((x) => x.id === id)?.name || 'this ad';
    const ok = await confirm({
      title: 'Delete ad',
      message: `Delete “${name}”? This can’t be undone.`,
      confirmLabel: 'Delete',
      destructive: true,
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/ad-generator/creatives/${id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setCreatives((c) => (c ?? []).filter((x) => x.id !== id));
      toast.success('Deleted');
    } catch (err) {
      toast.error(`Couldn't delete: ${err instanceof Error ? err.message : 'unknown error'}`);
    }
  }

  /**
   * Pull the source template's current design into one ad.
   *
   * The other half of the save-time push, and what makes declining it safe: an ad
   * that shows "Template updated" can take the change later, on its own. `force`
   * is the explicit reset of a customized ad, which discards its design, so it
   * asks first.
   */
  async function syncFromTemplate(id: string, force: boolean) {
    const ad = (creatives ?? []).find((x) => x.id === id);
    if (force) {
      const ok = await confirm({
        title: 'Reset to template?',
        message: `“${ad?.name ?? 'This ad'}” has its own design. Resetting replaces it with the template's current design and discards those changes. The offer values are kept.`,
        confirmLabel: 'Reset to template',
        cancelLabel: 'Keep its design',
      });
      if (!ok) return;
    }
    setSyncing(id);
    try {
      const res = await fetch(`/api/ad-generator/creatives/${id}/sync`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ force }),
      });
      if (!res.ok) throw new Error((await res.json().catch(() => null))?.error || `HTTP ${res.status}`);
      const { result } = (await res.json()) as {
        result?: { outcome: string; detail?: string; demoted?: boolean };
      };
      if (result?.outcome === 'updated') {
        // Reflect the new state without a refetch. `doc` MUST be carried across:
        // each card renders its preview from the ad's own doc, so updating only the
        // link fields left the badge correct and the picture stale until a reload.
        setCreatives((c) =>
          (c ?? []).map((x) =>
            x.id === id
              ? {
                  ...x,
                  doc: templateDocs[x.templateId] ?? x.doc,
                  templateSync: 'synced',
                  templateDocHash: templateHashes[x.templateId] ?? x.templateDocHash,
                  docEditedAt: null,
                  updatedAt: new Date().toISOString(),
                }
              : x,
          ),
        );
        toast.success('Updated to the template design');
      } else if (result?.outcome === 'blocked') {
        toast.warning(
          `Kept its current design: ${result.detail ?? 'the template update fails preflight for this ad.'}`,
        );
      } else {
        toast.error(result?.detail ?? "That ad couldn't be updated");
      }
    } catch (err) {
      toast.error(`Couldn't update: ${err instanceof Error ? err.message : 'unknown error'}`);
    } finally {
      setSyncing(null);
    }
  }

  return (
    // Managers render inside the app shell's padded card; clients render bare,
    // so give them the same centered, padded content column the editor uses.
    <div className={!isManager ? 'mx-auto max-w-6xl px-6 py-8' : undefined}>
      {/* Clients have no app chrome — show their dealership's brand at the top.
          The impersonation escape sits to the right of the logo and only
          renders while a developer is viewing as this client (never for the
          client themselves). */}
      {!isManager && (
        <div className="mb-5 flex items-center justify-between gap-3 border-b border-[var(--border)] pb-4">
          <AccountLogo className="h-11 w-auto max-w-[220px] object-contain" />
          <div className="flex items-center gap-2">
            {/* Clients have no sidebar and no utility bar, so this is their only
                route to the help desk — without it they'd have nowhere in the
                product to report that the one page they use is broken. */}
            <button
              type="button"
              onClick={openSupportModal}
              className="inline-flex items-center gap-1.5 px-3 h-9 text-sm rounded-lg border border-[var(--border)] text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors"
            >
              <LifebuoyIcon className="w-4 h-4" />
              Get help
            </button>
            <ImpersonationEscape />
          </div>
        </div>
      )}
      <div className="page-sticky-header mb-6">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <MegaphoneIcon className="w-7 h-7 text-[var(--primary)]" />
            <div>
              <h2 className="text-2xl font-bold">Ad Generator</h2>
              <p className="text-[var(--muted-foreground)] mt-1">
                Your account&rsquo;s ads. Open one to edit, or start a new one from a template.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap justify-end">
            {/* Settings cog → the Studio settings tabs that configure this
                tool: sizes, disclaimers, OEM rules, automation. The screens
                themselves live in the settings rail (the four /ad-generator/*
                routes redirect there); this stays as the shortcut from where the
                work happens. Managers only — clients get a bare
                create-and-export surface. */}
            {isManager && (
            <div className="relative" ref={cogRef}>
              <button
                type="button"
                onClick={() => setCogOpen((v) => !v)}
                title="Settings"
                aria-label="Settings"
                className="flex items-center justify-center w-10 h-10 rounded-lg border border-[var(--border)] text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors"
              >
                <Cog6ToothIcon className="w-4 h-4" />
              </button>
              {cogOpen && (
                <div className="absolute right-0 top-full mt-1 z-30 w-56 glass-dropdown">
                  {(() => {
                    const itemCls =
                      'flex w-full items-center gap-2 px-3 py-2 text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors';
                    return (
                      <>
                        <Link href="/settings/ad-sizes" onClick={() => setCogOpen(false)} className={itemCls}>
                          <RectangleGroupIcon className="w-4 h-4" />
                          Ad Sizes
                        </Link>
                        <Link href="/settings/ad-disclaimers" onClick={() => setCogOpen(false)} className={itemCls}>
                          <DocumentTextIcon className="w-4 h-4" />
                          Disclaimer templates
                        </Link>
                        <Link href="/settings/ad-oem-rules" onClick={() => setCogOpen(false)} className={itemCls}>
                          <ShieldCheckIcon className="w-4 h-4" />
                          OEM compliance rules
                        </Link>
                        <Link href="/settings/ad-automation" onClick={() => setCogOpen(false)} className={itemCls}>
                          <BoltIcon className="w-4 h-4" />
                          Automation
                        </Link>
                      </>
                    );
                  })()}
                </div>
              )}
            </div>
            )}

            {/* New ad. Managers get a split menu (template library or a
                from-scratch build); clients get a single button that opens the
                template picker — they never touch the builder. */}
            {isManager ? (
            <div className="relative" ref={newRef}>
              <button
                type="button"
                onClick={() => setNewOpen((v) => !v)}
                disabled={!accountKey}
                className="flex items-center gap-1.5 px-3 h-10 text-sm rounded-lg border border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-foreground)] hover:bg-[var(--primary)]/90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <PlusIcon className="w-4 h-4" />
                New ad
                <ChevronDownIcon className={`w-3.5 h-3.5 transition-transform ${newOpen ? 'rotate-180' : ''}`} />
              </button>
              {newOpen && (
                <div className="absolute right-0 top-full mt-1 z-30 w-56 glass-dropdown">
                  <button
                    type="button"
                    onClick={() => {
                      setNewOpen(false);
                      setPickerOpen(true);
                    }}
                    className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors"
                  >
                    <MegaphoneIcon className="w-4 h-4 flex-shrink-0" />
                    <span>
                      From template library
                      <span className="block text-[11px] text-[var(--muted-foreground)]">Start from a ready-made layout.</span>
                    </span>
                  </button>
                  <button
                    type="button"
                    disabled={creating || !accountKey}
                    onClick={() => {
                      setNewOpen(false);
                      setScratchOpen(true);
                    }}
                    className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors disabled:opacity-50"
                  >
                    <Squares2X2Icon className="w-4 h-4 flex-shrink-0" />
                    <span>
                      From scratch
                      <span className="block text-[11px] text-[var(--muted-foreground)]">Name it and pick a size, then design in the builder.</span>
                    </span>
                  </button>
                  {/* Generating from the OEM feed is a way of making ads, so it
                      belongs with the other two rather than on the automation
                      dashboard. A run needs automation set up with a template
                      mapped, or it can only ever report "0 generated" — but the
                      entry point stays put and routes to the missing setup instead
                      of vanishing, which just looked like the feature was absent. */}
                  <div className="my-1 border-t border-[var(--border)]" />
                  {automationReady ? (
                    <button
                      type="button"
                      disabled={generating || !accountKey}
                      onClick={() => {
                        setNewOpen(false);
                        setGenOpen(true);
                      }}
                      className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors disabled:opacity-50"
                    >
                      <BoltIcon className={`w-4 h-4 flex-shrink-0 ${generating ? 'animate-pulse' : ''}`} />
                      <span>
                        Generate from OEM offers
                        <span className="block text-[11px] text-[var(--muted-foreground)]">
                          Pick the models and offer types, then build drafts.
                        </span>
                      </span>
                    </button>
                  ) : (
                    <Link
                      href="/settings/ad-automation?tab=settings"
                      onClick={() => setNewOpen(false)}
                      className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--muted-foreground)] hover:bg-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
                    >
                      <BoltIcon className="w-4 h-4 flex-shrink-0" />
                      <span>
                        Generate from OEM offers
                        <span className="block text-[11px] text-[var(--muted-foreground)]">
                          {automationBlocker === 'no-template'
                            ? 'Needs a template mapped — open automation settings.'
                            : 'Set up ad automation for this account first.'}
                        </span>
                      </span>
                    </Link>
                  )}
                </div>
              )}
            </div>
            ) : (
              <button
                type="button"
                onClick={() => setPickerOpen(true)}
                disabled={!accountKey}
                className="flex items-center gap-1.5 px-3 h-10 text-sm rounded-lg border border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-foreground)] hover:bg-[var(--primary)]/90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <PlusIcon className="w-4 h-4" />
                New ad
              </button>
            )}
          </div>
        </div>
      </div>

      {creatives && creatives.length > 0 && (
        <div className="mb-4">
          {/* Status, source, offer window and the vehicle facets all live in the
              Filters popover — they answer one question, so they get one
              control and one count instead of a crowded toolbar row. */}
          <ListToolbar
            leading={
              <div className="flex items-center gap-3">
                <span className="text-sm text-[var(--muted-foreground)]">
                  {visible.length} {visible.length === 1 ? 'ad' : 'ads'}
                </span>
                {visible.length > 0 && (
                  <button
                    type="button"
                    onClick={() =>
                      setSelected(
                        selectedVisible.length === visible.length ? new Set() : new Set(visibleIds),
                      )
                    }
                    className="text-xs font-medium text-[var(--muted-foreground)] transition-colors hover:text-[var(--foreground)]"
                  >
                    {selectedVisible.length === visible.length ? 'Clear selection' : 'Select all'}
                  </button>
                )}
              </div>
            }
            search={search}
            onSearchChange={setSearch}
            searchPlaceholder="Search ads…"
            trailing={
              <AdFilterPanel
                status={statusFilter}
                onStatusChange={setStatusFilter}
                source={sourceFilter}
                onSourceChange={setSourceFilter}
                offerWindow={offerWindow}
                onOfferWindowChange={setOfferWindow}
                options={facetOptions}
                visibleFacets={visibleFacets}
                selection={facetSel}
                onSelectionChange={setFacetSel}
                // Until the job has produced something, the split is noise.
                showSource={(creatives ?? []).some((c) => c.autoGenerated)}
              />
            }
          />
        </div>
      )}

      {!accountKey ? (
        <div className="glass-card rounded-2xl p-12 text-center flex flex-col items-center">
          <div className="w-16 h-16 rounded-2xl bg-[var(--muted)] flex items-center justify-center mb-4">
            <MegaphoneIcon className="w-8 h-8 text-[var(--muted-foreground)]" />
          </div>
          <h2 className="text-lg font-semibold mb-1">Select an account</h2>
          <p className="text-sm text-[var(--muted-foreground)] max-w-md">
            Choose an account in the top bar to see and create its ads.
          </p>
        </div>
      ) : creatives === null ? (
        <div className="text-sm text-[var(--muted-foreground)]">Loading…</div>
      ) : creatives.length === 0 ? (
        <div className="glass-card rounded-2xl p-12 text-center flex flex-col items-center">
          <div className="w-16 h-16 rounded-2xl bg-[var(--muted)] flex items-center justify-center mb-4">
            <MegaphoneIcon className="w-8 h-8 text-[var(--muted-foreground)]" />
          </div>
          <h2 className="text-lg font-semibold mb-1">No ads yet</h2>
          <p className="text-sm text-[var(--muted-foreground)] max-w-md mb-6">
            Start from a template — pick a layout, drop in the offer + vehicle, and export sized for every channel.
          </p>
          <button
            type="button"
            onClick={() => setPickerOpen(true)}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-[var(--primary)] text-[var(--primary-foreground)] text-sm font-medium hover:opacity-90 transition-opacity"
          >
            <PlusIcon className="w-4 h-4" />
            Create your first ad
          </button>
        </div>
      ) : visible.length === 0 ? (
        <div className="glass-card rounded-2xl p-10 text-center text-sm text-[var(--muted-foreground)]">
          No ads match the current filters.
          {countSelected(facetSel) + (statusFilter !== 'all' ? 1 : 0) + (sourceFilter !== 'all' ? 1 : 0) + (offerWindow !== 'all' ? 1 : 0) > 0 && (
            <button
              type="button"
              onClick={() => {
                setFacetSel({});
                setStatusFilter('all');
                setSourceFilter('all');
                setOfferWindow('all');
              }}
              className="ml-1.5 font-medium text-[var(--primary)] hover:underline"
            >
              Clear filters
            </button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
          {visible.map((c) => {
            // Render the thumbnail from the ad's own snapshot when present, so it
            // matches the editor/export even if the master template later changed.
            const template = c.doc ? adTemplateFromDoc(c.id, c.doc) : templates.find((t) => t.id === c.templateId);
            return (
              <div
                key={c.id}
                role="button"
                tabIndex={0}
                // With a selection open the card toggles instead of navigating —
                // clicking through to the editor mid-selection is never what you
                // meant, and it loses the selection on the way.
                onClick={() => (selected.size > 0 ? toggleSelect(c.id) : router.push(`/ad-generator/${c.id}`))}
                onKeyDown={(e) => {
                  if (e.key !== 'Enter' && e.key !== ' ') return;
                  e.preventDefault();
                  if (selected.size > 0) toggleSelect(c.id);
                  else router.push(`/ad-generator/${c.id}`);
                }}
                className={`glass-card group relative cursor-pointer overflow-hidden rounded-2xl border text-left transition-colors ${
                  selected.has(c.id)
                    ? 'border-[var(--primary)] ring-1 ring-[var(--primary)]'
                    : 'border-[var(--border)] hover:border-[var(--primary)]'
                }`}
              >
                {/* Hidden until hover or selection, so an unselected grid stays
                    clean but the affordance is one movement away. */}
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    toggleSelect(c.id);
                  }}
                  aria-label={selected.has(c.id) ? `Deselect ${c.name}` : `Select ${c.name}`}
                  aria-pressed={selected.has(c.id)}
                  className={`absolute left-2.5 top-2.5 z-10 flex h-5 w-5 items-center justify-center rounded-md border transition-opacity ${
                    selected.has(c.id)
                      ? 'border-[var(--primary)] bg-[var(--primary)] opacity-100'
                      : 'border-[var(--border)] bg-[var(--background)]/90 opacity-0 group-hover:opacity-100 focus-visible:opacity-100'
                  }`}
                >
                  {selected.has(c.id) && (
                    <svg viewBox="0 0 12 12" className="h-3 w-3 text-white" fill="none">
                      <path
                        d="M2.5 6.5l2.5 2.5 4.5-5"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  )}
                </button>
                <AdPreviewThumb template={template} data={c.data} branding={branding} />
                <div className="flex items-start justify-between gap-2 p-3">
                  <div className="min-w-0">
                    <div className="truncate text-sm font-semibold text-[var(--foreground)]">{c.name}</div>
                    <div className="mt-0.5 flex items-center gap-1.5 text-[11px] text-[var(--muted-foreground)]">
                      <span
                        className={`rounded px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide ${
                          c.status === 'ready' ? 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400' : 'bg-[var(--muted)] text-[var(--muted-foreground)]'
                        }`}
                      >
                        {c.status}
                      </span>
                      {/* What KIND of ad this is. Sits next to the status because
                          it's the other thing you scan a grid for — and because
                          the neighbouring "Custom" chip is a template-SYNC state,
                          not an offer type, and used to be the only thing here
                          that looked like an answer to "what kind of ad is this". */}
                      <OfferKindBadge doc={c.doc} />
                      {c.autoGenerated && (
                        <span
                          title="Built by the nightly offer job, not by hand"
                          className="flex items-center gap-0.5 rounded bg-[var(--primary)]/12 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-[var(--primary)]"
                        >
                          <BoltIcon className="h-2.5 w-2.5" />
                          Auto
                        </span>
                      )}
                      {/* Customized = this ad owns its design and template edits
                          skip it. Worth stating on the card, because it's the
                          reason a template fix didn't show up here. */}
                      {c.docEditedAt && (
                        <span
                          title={`Edited on ${new Date(c.docEditedAt).toLocaleDateString()} — this ad keeps its own design, so template updates skip it`}
                          className="flex items-center gap-0.5 rounded bg-[var(--muted)] px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-[var(--muted-foreground)]"
                        >
                          <PencilSquareIcon className="h-2.5 w-2.5" />
                          {/* Was "Custom", which read like an answer to "what kind
                              of ad is this" while actually meaning "this ad keeps
                              its own design". Now that Custom is an offer KIND,
                              the two were unusable side by side. "Edited" is what
                              the chip's own tooltip has always said. */}
                          Edited
                        </span>
                      )}
                      <span className="truncate">{template?.name ?? c.templateId}</span>
                    </div>
                    <div className="mt-0.5 text-[10px] text-[var(--muted-foreground)]">
                      Updated {new Date(c.updatedAt).toLocaleDateString()}
                      {/* Auto-generated ads are pinned to an offer that expires, so
                          the useful date is when it stops being runnable — a
                          human-built ad has no such deadline. */}
                      {c.autoGenerated && c.expiresAt && (
                        <> · offer ends {new Date(c.expiresAt).toLocaleDateString()}</>
                      )}
                    </div>
                    {/* The template has moved on since this ad was built. Offered
                        rather than applied: a design change has to be someone's
                        decision, and for a customized ad it costs them their edit. */}
                    {isBehindTemplate(
                      { doc: c.doc, templateDocHash: c.templateDocHash, templateSync: c.templateSync, autoGenerated: c.autoGenerated },
                      templateHashes[c.templateId] ?? null,
                    ) && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          void syncFromTemplate(c.id, !!c.docEditedAt);
                        }}
                        disabled={syncing === c.id}
                        // Amber here too, so the "your ad is behind its template"
                        // affordance is one colour everywhere it appears — and so it
                        // stands out from a card that is otherwise all brand colour.
                        className="mt-1.5 flex items-center gap-1 rounded-md bg-amber-500/15 px-1.5 py-1 text-[10px] font-semibold text-amber-700 transition-colors hover:bg-amber-500/25 disabled:opacity-50 dark:text-amber-400"
                      >
                        <ArrowPathIcon className={`h-3 w-3 ${syncing === c.id ? 'animate-spin' : ''}`} />
                        {syncing === c.id
                          ? 'Updating…'
                          : c.docEditedAt
                            ? 'Template changed · reset to it'
                            : 'Template updated · apply'}
                      </button>
                    )}
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      remove(c.id);
                    }}
                    title="Delete"
                    className="flex-shrink-0 rounded-md p-1.5 text-[var(--muted-foreground)] opacity-0 transition-opacity hover:bg-red-500/10 hover:text-red-500 group-hover:opacity-100"
                  >
                    <TrashIcon className="h-4 w-4" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {pickerOpen && typeof document !== 'undefined' && createPortal(
        <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-black/60 p-4 pt-10 sm:pt-16" onClick={() => !creating && setPickerOpen(false)}>
          <div className="flex max-h-[85vh] w-full max-w-4xl flex-col rounded-2xl border border-[var(--border)] bg-[var(--card-strong)] shadow-2xl backdrop-blur-2xl" onClick={(e) => e.stopPropagation()}>
            {/* Header */}
            <div className="flex items-start justify-between gap-3 border-b border-[var(--border)] p-5">
              <div className="flex items-center gap-3">
                <span className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl bg-[var(--primary)]/10 text-[var(--primary)]">
                  <MegaphoneIcon className="h-5 w-5" />
                </span>
                <div>
                  <h2 className="text-lg font-bold text-[var(--foreground)]">Start a new ad</h2>
                  <p className="text-xs text-[var(--muted-foreground)]">
                    {isManager
                      ? 'Pick a template to begin — you can edit everything after.'
                      : 'Pick a template, then fill in your offer and vehicle.'}
                  </p>
                </div>
              </div>
              <button onClick={() => setPickerOpen(false)} className="rounded-lg p-1.5 text-[var(--muted-foreground)] transition-colors hover:bg-[var(--muted)] hover:text-[var(--foreground)]">
                <XMarkIcon className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="min-h-0 flex-1 overflow-y-auto p-5">
              {pickerTemplates.length === 0 ? (
                <div className="rounded-xl border border-dashed border-[var(--border)] p-12 text-center">
                  <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--muted)]">
                    <MegaphoneIcon className="h-6 w-6 text-[var(--muted-foreground)]" />
                  </div>
                  {isManager ? (
                    <>
                      <p className="text-sm text-[var(--muted-foreground)]">No templates for this account&rsquo;s industry yet.</p>
                      <button
                        type="button"
                        disabled={creating}
                        onClick={() => {
                          setPickerOpen(false);
                          setScratchOpen(true);
                        }}
                        className="mt-4 inline-flex items-center gap-1.5 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-medium text-[var(--primary-foreground)] transition-opacity hover:opacity-90 disabled:opacity-50"
                      >
                        <Squares2X2Icon className="h-4 w-4" />
                        Start from scratch
                      </button>
                    </>
                  ) : (
                    <p className="mx-auto max-w-sm text-sm text-[var(--muted-foreground)]">
                      No ad templates have been published for your account yet. Your Loomi team will add this month&rsquo;s offer template here.
                    </p>
                  )}
                </div>
              ) : (
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {pickerTemplates.map((t) => (
                    <button
                      key={t.id}
                      disabled={creating}
                      onClick={() => createAd(t.id)}
                      className="group flex flex-col overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--card)] text-left transition-all hover:-translate-y-0.5 hover:border-[var(--primary)] hover:shadow-lg disabled:pointer-events-none disabled:opacity-60"
                    >
                      <div className="relative overflow-hidden border-b border-[var(--border)]">
                        <AdPreviewThumb template={t} data={{}} branding={branding} height={190} />
                        <div className="pointer-events-none absolute inset-0 flex items-end justify-center bg-gradient-to-t from-black/55 to-transparent p-3 opacity-0 transition-opacity group-hover:opacity-100">
                          <span className="rounded-lg bg-white/95 px-3 py-1 text-xs font-semibold text-black shadow">Use this template</span>
                        </div>
                      </div>
                      <div className="p-3">
                        <div className="flex items-center gap-1.5">
                          {/* Which form you're about to be handed — worth knowing
                              before you pick, not after. */}
                          <OfferKindBadge doc={templateDocs[t.id]} />
                          <span className="truncate text-sm font-semibold text-[var(--foreground)]">{t.name}</span>
                        </div>
                        {t.description && <div className="mt-0.5 line-clamp-2 text-[11px] leading-snug text-[var(--muted-foreground)]">{t.description}</div>}
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Footer — template count + from-scratch (managers, when templates exist) */}
            {isManager && pickerTemplates.length > 0 && (
              <div className="flex items-center justify-between gap-2 border-t border-[var(--border)] p-4">
                <span className="text-[11px] text-[var(--muted-foreground)]">
                  {pickerTemplates.length} template{pickerTemplates.length === 1 ? '' : 's'} available
                </span>
                <button
                  type="button"
                  disabled={creating}
                  onClick={() => {
                    setPickerOpen(false);
                    setScratchOpen(true);
                  }}
                  className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-medium text-[var(--foreground)] transition-colors hover:border-[var(--primary)] hover:text-[var(--primary)] disabled:opacity-50"
                >
                  <Squares2X2Icon className="h-4 w-4" />
                  Start from scratch
                </button>
              </div>
            )}
          </div>
        </div>,
        document.body,
      )}

      {scratchOpen && (
        <ScratchSetupModal
          creating={creating}
          industry={accountData?.category ?? null}
          onClose={() => !creating && setScratchOpen(false)}
          onStart={(name, sizes, kind, vehicleMode) => void createBlank(name, sizes, kind, vehicleMode)}
        />
      )}

      {selectedVisible.length > 0 && (
        <BulkActionDock
          count={selectedVisible.length}
          itemLabel={selectedVisible.length === 1 ? 'ad' : 'ads'}
          onClose={() => setSelected(new Set())}
          actions={
            statusFilter === 'archived'
              ? [
                  {
                    id: 'restore',
                    label: 'Restore',
                    icon: <ArrowUturnLeftIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('restore'),
                  },
                  {
                    id: 'delete',
                    label: 'Delete',
                    icon: <TrashIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    danger: true,
                    onClick: () => void runBulk('delete'),
                  },
                ]
              : [
                  {
                    id: 'mark-ready',
                    label: 'Mark ready',
                    icon: <CheckCircleIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('mark_ready'),
                  },
                  {
                    id: 'mark-draft',
                    label: 'Mark draft',
                    icon: <PencilSquareIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('mark_draft'),
                  },
                  {
                    id: 'archive',
                    label: 'Archive',
                    icon: <ArchiveBoxIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('archive'),
                  },
                  {
                    id: 'delete',
                    label: 'Delete',
                    icon: <TrashIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    danger: true,
                    onClick: () => void runBulk('delete'),
                  },
                ]
          }
        />
      )}

      {genOpen && (
        <GenerateOffersModal
          candidates={candidates}
          maxAdsPerRun={maxAdsPerRun}
          busy={generating}
          onCancel={() => !generating && setGenOpen(false)}
          onGenerate={(scope) => void generateFromOffers(scope)}
        />
      )}
    </div>
  );
}

/**
 * The "Ad type" choices, derived from the offer-kind registry so a new kind shows
 * up here without editing this file. The vehicle kind additionally offers its
 * two-offer variant — gated on `capabilities.dualOffer`, because "Two vehicles"
 * merges the VEHICLE field kit and would be meaningless (or wrong) elsewhere.
 *
 * Scoped to the ACCOUNT'S industry: outside automotive/powersports there is no
 * vehicle to offer, and the whole control collapses to a single choice — which
 * the modal then stops asking about.
 *
 * The old control here was "Vehicle offer fields — Blank / Single vehicle / Two
 * vehicles", and Blank and Single vehicle produced BYTE-IDENTICAL docs: every doc
 * was stamped with the whole vehicle schema regardless, so "Blank" never gave
 * anyone a blank form. Offer kinds are what make the choice mean something.
 */
type AdType = { kind: string; mode: VehicleFieldsMode; label: string; hint: string };

const adTypesForIndustry = (industry: string | null | undefined): AdType[] =>
  offerKindsForIndustry(industry).flatMap((k) => [
    { kind: k.id, mode: 'none' as VehicleFieldsMode, label: k.label, hint: k.description },
    ...(k.capabilities.dualOffer
      ? [{
          kind: k.id,
          mode: 'dual' as VehicleFieldsMode,
          label: 'Two vehicle offers',
          hint: 'Two offers side by side, each with its own vehicle, type, payment and terms.',
        }]
      : []),
  ]);

/**
 * "From scratch" setup step — name the ad and pick a starting size before the
 * builder opens, so a brand-new design starts at the right dimensions instead
 * of always defaulting to a 1080 square.
 *
 * Sizes come from the size library (Settings → Ad Sizes) — the same list the
 * builder's Sizes panel reads. This modal used to render a code-side catalog
 * instead, so sizes a team added were simply absent here.
 */
function ScratchSetupModal({
  creating,
  industry,
  onClose,
  onStart,
}: {
  creating: boolean;
  /** The account's industry — decides which ad types exist here at all. */
  industry: string | null;
  onClose: () => void;
  onStart: (name: string, sizes: LibrarySize[], kind: string, vehicleMode: VehicleFieldsMode) => void;
}) {
  const { sizes, facets, loading } = useSizeLibrary();
  const adTypes = useMemo(() => adTypesForIndustry(industry), [industry]);
  const [name, setName] = useState('Untitled ad');
  const [adType, setAdType] = useState(0);
  const [selected, setSelected] = useState<LibrarySize[]>([]);
  const toggle = (s: LibrarySize) =>
    setSelected((cur) => (cur.some((x) => x.id === s.id) ? cur.filter((x) => x.id !== s.id) : [...cur, s]));
  const selectedIds = useMemo(() => new Set(selected.map((s) => s.id)), [selected]);

  // Preselect a sensible default once the library lands — a square if there is
  // one (matches the old 1080 default), else whatever's first. Runs only while
  // nothing is selected, so it can't fight the user's picks on a revalidation.
  useEffect(() => {
    if (selected.length || !sizes.length) return;
    const square = sizes.find((s) => s.width === s.height);
    setSelected([square ?? sizes[0]]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sizes]);

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-black/60 p-4 pt-16" onClick={onClose}>
      <div className="w-full max-w-lg rounded-2xl border border-[var(--border)] bg-[var(--card-strong)] p-5 shadow-xl backdrop-blur-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="mb-4 flex items-start justify-between">
          <div>
            <h2 className="text-sm font-bold text-[var(--foreground)]">Start from scratch</h2>
            <p className="text-xs text-[var(--muted-foreground)]">Name it and pick one or more starting sizes — you can add more or change everything in the builder.</p>
          </div>
          <button onClick={onClose} className="rounded-md p-1 text-[var(--muted-foreground)] transition-colors hover:bg-[var(--muted)] hover:text-[var(--foreground)]">
            <XMarkIcon className="h-5 w-5" />
          </button>
        </div>

        <label className="mb-4 block">
          <span className="mb-1 block text-xs font-medium text-[var(--foreground)]">Name</span>
          <input
            autoFocus
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Untitled ad"
            className="w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none focus:border-[var(--primary)]"
          />
        </label>

        {/* One ad type is not a choice — outside automotive the vehicle offer
            isn't on the menu, so asking "what kind?" of a one-item list is a
            control that can only be answered one way. */}
        {adTypes.length > 1 && (
        <div className="mb-4">
          <div className="mb-1.5 flex items-center gap-1.5">
            <span className="text-xs font-medium text-[var(--foreground)]">Ad type</span>
            <Tooltip label="What kind of ad this is. It sets the questions the form asks — a vehicle offer asks for payments, terms and a VIN; a general ad asks for a headline and a call to action. You can't change it later, so pick the one that matches the ad.">
              <InformationCircleIcon className="h-3.5 w-3.5 shrink-0 text-[var(--muted-foreground)] transition-colors hover:text-[var(--foreground)]" />
            </Tooltip>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {adTypes.map((opt, i) => (
              <Tooltip key={`${opt.kind}:${opt.mode}`} label={opt.hint}>
                <button
                  type="button"
                  onClick={() => setAdType(i)}
                  className={`rounded-lg border px-3 py-1.5 text-xs font-medium transition-colors ${
                    adType === i ? 'border-[var(--primary)] bg-[var(--primary)]/10 text-[var(--primary)]' : 'border-[var(--border)] text-[var(--muted-foreground)] hover:border-[var(--primary)] hover:text-[var(--foreground)]'
                  }`}
                >
                  {opt.label}
                </button>
              </Tooltip>
            ))}
          </div>
        </div>
        )}

        <div className="mb-1.5 flex items-baseline justify-between">
          <span className="text-xs font-medium text-[var(--foreground)]">Starting sizes</span>
          <span className="text-[11px] text-[var(--muted-foreground)]">{selected.length} selected</span>
        </div>
        <div className="max-h-[44vh] overflow-y-auto pr-1">
          <SizePicker sizes={sizes} facets={facets} loading={loading} selectedIds={selectedIds} onToggle={toggle} />
        </div>
        <Link
          href="/settings/ad-sizes"
          className="mt-2 inline-block text-[11px] font-medium text-[var(--muted-foreground)] transition-colors hover:text-[var(--primary)]"
        >
          Manage size library →
        </Link>

        <div className="mt-5 flex items-center justify-end gap-2">
          <button onClick={onClose} disabled={creating} className="rounded-lg px-3 py-2 text-sm text-[var(--muted-foreground)] transition-colors hover:text-[var(--foreground)] disabled:opacity-50">
            Cancel
          </button>
          <button
            onClick={() => onStart(name, selected, adTypes[adType]?.kind ?? DEFAULT_OFFER_KIND, adTypes[adType]?.mode ?? 'none')}
            disabled={creating || selected.length === 0}
            className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-medium text-[var(--primary-foreground)] transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Squares2X2Icon className="h-4 w-4" />
            {creating ? 'Creating…' : selected.length > 1 ? `Start with ${selected.length} sizes` : 'Start designing'}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}

