'use client';

/**
 * Ad Generator — the home surface: a gallery of the active account's created
 * ads (like the Landing Pages / Templates index pages, and styled to match
 * them: sticky page header, shared ListToolbar, glass-card empty states).
 * Click an ad to open the editor (/ad-generator/[id]); "New ad" picks a
 * template and creates one. Live mini previews render through the same
 * template function the editor + export use. Behind AD_GENERATOR_ENABLED (the
 * route layout 404s when off).
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createPortal } from 'react-dom';
import { toast } from 'sonner';
import { BoltIcon, MegaphoneIcon, PlusIcon, TrashIcon, Squares2X2Icon, RectangleGroupIcon, XMarkIcon, Cog6ToothIcon, ChevronDownIcon, CheckIcon, DocumentTextIcon, ShieldCheckIcon, ArchiveBoxIcon, ArrowUturnLeftIcon, CheckCircleIcon, PencilSquareIcon } from '@heroicons/react/24/outline';
import { useAccount } from '@/contexts/account-context';
import { useLoomiDialog } from '@/contexts/loomi-dialog-context';
import { MANAGEMENT_ROLES } from '@/lib/roles';
import { ListToolbar } from '@/components/list-toolbar';
import BulkActionDock from '@/components/bulk-action-dock';
import { AccountLogo } from '@/components/account-logo';
import { ImpersonationEscape } from '@/components/impersonation-escape';
import type { StatusFilterValue } from '@/components/status-filter';
import { AdPreviewThumb, brandingFromAccount } from '@/components/ad-generator/ad-preview-thumb';
import { ALL_TEMPLATES } from '@/lib/ad-generator/templates';
import { adTemplateFromDoc, blankTemplateDoc } from '@/lib/ad-generator/doc-template';
import { addFieldKit, type VehicleFieldsMode } from '@/lib/ad-generator/vehicle-fields';
import { catalogByCategory, aspectLabel, type CatalogSize } from '@/lib/ad-generator/ad-size-catalog';
import { templateInIndustry } from '@/lib/ad-generator/industry';
import {
  facetsForAd,
  matchesFacets,
  buildFacetOptions,
  countSelected,
  offerEndsAt,
  matchesWindow,
  FACET_KEYS,
  type AdFacetValues,
  type FacetSelection,
  type OfferWindow,
} from '@/lib/ad-generator/ad-facets';
import { AdFilterPanel } from '@/components/ad-generator/ad-filter-panel';
import { GenerateOffersModal, type GenerateCandidate } from '@/components/ad-generator/generate-offers-modal';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';
import type { AdTemplate, AdData } from '@/lib/ad-generator/types';

type Creative = {
  id: string;
  name: string;
  templateId: string;
  status: string;
  updatedAt: string;
  createdByName: string | null;
  /** True when the nightly job built this rather than a person. */
  autoGenerated?: boolean;
  /** Auto-generated only: when the underlying offer stops being valid. */
  expiresAt?: string | null;
  /** Auto-generated only: why the generator held it as a draft. */
  reviewNotes?: string | null;
  doc?: TemplateDoc | null;
  data: AdData;
};

/** Manual / automated split for the list. */
type SourceFilter = 'all' | 'manual' | 'auto';

/** A creative plus everything derived from its data, memoised for filtering. */
type FacetedCreative = Creative & { facets: AdFacetValues; endsAt: Date | null };

export default function AdGeneratorListPage() {
  const { accountKey, accountData, userRole } = useAccount();
  const isManager = !!userRole && MANAGEMENT_ROLES.includes(userRole);
  const { confirm } = useLoomiDialog();
  const router = useRouter();
  const [dbTemplates, setDbTemplates] = useState<AdTemplate[]>([]);
  const [creatives, setCreatives] = useState<Creative[] | null>(null);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [scratchOpen, setScratchOpen] = useState(false);
  const [creating, setCreating] = useState(false);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilterValue>('all');
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>('all');
  const [facetSel, setFacetSel] = useState<FacetSelection>({});
  const [offerWindow, setOfferWindow] = useState<OfferWindow>('all');
  // What's standing between this sub-account and a generate run. A run needs
  // automation set up AND a template mapped, or it can only ever report zero —
  // but the entry point stays visible either way and says which piece is missing.
  // Hiding it outright sent people hunting for a menu item that wasn't there,
  // including from the automation page's own "use New ad → Generate from OEM
  // offers" empty state.
  const [automationBlocker, setAutomationBlocker] = useState<'unconfigured' | 'no-template' | null>(
    'unconfigured',
  );
  const automationReady = automationBlocker === null;
  const [generating, setGenerating] = useState(false);
  const [genOpen, setGenOpen] = useState(false);
  const [candidates, setCandidates] = useState<GenerateCandidate[]>([]);
  const [maxAdsPerRun, setMaxAdsPerRun] = useState(10);
  // Bulk selection. Ids rather than indices so it survives filtering and reloads.
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [bulkBusy, setBulkBusy] = useState(false);
  // Header dropdowns: the settings cog + the "New ad" split menu.
  const [cogOpen, setCogOpen] = useState(false);
  const [newOpen, setNewOpen] = useState(false);
  const cogRef = useRef<HTMLDivElement>(null);
  const newRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!cogOpen && !newOpen) return;
    const onDown = (e: MouseEvent) => {
      const t = e.target as Node;
      if (cogOpen && !cogRef.current?.contains(t)) setCogOpen(false);
      if (newOpen && !newRef.current?.contains(t)) setNewOpen(false);
    };
    document.addEventListener('mousedown', onDown);
    return () => document.removeEventListener('mousedown', onDown);
  }, [cogOpen, newOpen]);

  useEffect(() => {
    let cancelled = false;
    // Global templates + this account's own (dealer-branded plates etc.).
    fetch(`/api/ad-generator/templates-doc${accountKey ? `?accountKey=${encodeURIComponent(accountKey)}` : ''}`)
      .then((r) => (r.ok ? r.json() : { templates: [] }))
      .then((d: { templates?: { id: string; doc: TemplateDoc | null }[] }) => {
        if (cancelled) return;
        setDbTemplates((d.templates ?? []).filter((t) => t.doc).map((t) => adTemplateFromDoc(t.id, t.doc as TemplateDoc)));
      })
      .catch(() => {
        if (!cancelled) setDbTemplates([]);
      });
    return () => {
      cancelled = true;
    };
  }, [accountKey]);

  // Resolution list (incl. retired templates) — for rendering existing ads.
  const templates = useMemo(() => [...ALL_TEMPLATES, ...dbTemplates], [dbTemplates]);
  // Picker list — the shared library (DB templates), scoped to this account's
  // industry. Code-defined starters stay in ALL_TEMPLATES (so existing ads still
  // render) but aren't offered here — the DB library is the single source (the
  // built-in/DB split and the old Ad-Types filter row were both retired).
  const pickerTemplates = useMemo(
    () => dbTemplates.filter((t) => templateInIndustry(t, accountData?.category)),
    [dbTemplates, accountData?.category],
  );

  useEffect(() => {
    if (!accountKey) {
      setCreatives([]);
      return;
    }
    let cancelled = false;
    setCreatives(null);
    // Archived ads live behind their own query rather than being filtered out
    // client-side, so an account with thousands of them doesn't ship them all.
    const archived = statusFilter === 'archived' ? '&archived=1' : '';
    fetch(`/api/ad-generator/creatives?accountKey=${encodeURIComponent(accountKey)}${archived}`)
      .then((r) => (r.ok ? r.json() : { creatives: [] }))
      .then((d: { creatives?: Creative[] }) => {
        if (!cancelled) setCreatives(d.creatives ?? []);
      })
      .catch(() => {
        if (!cancelled) setCreatives([]);
      });
    return () => {
      cancelled = true;
    };
  }, [accountKey, statusFilter]);

  // Selecting something, then filtering it out of view, would leave it queued
  // for a bulk action nobody can see. Keep the selection inside the visible set.
  useEffect(() => {
    setSelected(new Set());
  }, [accountKey]);

  // Is automation set up for this sub-account? Managers only — the endpoint is
  // admin-gated, and a 403 here should stay silent rather than toast.
  useEffect(() => {
    if (!accountKey || !isManager) {
      setAutomationBlocker('unconfigured');
      return;
    }
    let cancelled = false;
    fetch(`/api/ad-generator/automation/shadow?accountKey=${encodeURIComponent(accountKey)}`)
      .then((r) => (r.ok ? r.json() : null))
      .then(
        (
          d: {
            configured?: boolean;
            scope?: { templateMap?: Record<string, string>; maxAdsPerRun?: number };
            vehicles?: (GenerateCandidate & { liveOffers?: number })[];
          } | null,
        ) => {
          if (cancelled) return;
          setAutomationBlocker(
            !d?.configured ? 'unconfigured' : !d.scope?.templateMap?.all ? 'no-template' : null,
          );
          setMaxAdsPerRun(d?.scope?.maxAdsPerRun ?? 10);
          // Only vehicles that could actually produce an ad — on the lot with at
          // least one live offer. The dialog narrows further from there.
          setCandidates(
            (d?.vehicles ?? [])
              .filter((v) => v.stock > 0 && (v.offerTypes?.length ?? 0) > 0)
              .map((v) => ({
                year: v.year,
                make: v.make,
                model: v.model,
                stock: v.stock,
                offerTypes: v.offerTypes ?? [],
                wouldChoose: v.wouldChoose ?? null,
                wouldChooseType: v.wouldChooseType ?? null,
              })),
          );
        },
      )
      .catch(() => {
        if (!cancelled) setAutomationBlocker('unconfigured');
      });
    return () => {
      cancelled = true;
    };
  }, [accountKey, isManager]);

  async function generateFromOffers(scope: { vehicles: string[]; offerTypes: string[] }) {
    if (!accountKey) return;
    setGenerating(true);
    try {
      const res = await fetch('/api/ad-generator/automation/shadow', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountKey, action: 'generate', scope }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
      const skipped = (json.skipped ?? []).length;
      if (json.created || json.refreshed) {
        toast.success(
          `${json.created} new draft${json.created === 1 ? '' : 's'}, ${json.refreshed} refreshed` +
            (skipped ? `, ${skipped} skipped` : ''),
        );
        // Show them straight away rather than making the user reload.
        const list = await fetch(`/api/ad-generator/creatives?accountKey=${encodeURIComponent(accountKey)}`)
          .then((r) => (r.ok ? r.json() : { creatives: [] }))
          .catch(() => ({ creatives: [] }));
        setCreatives(list.creatives ?? []);
      } else {
        toast.warning(
          `No ads generated${skipped ? ` — ${skipped} vehicle(s) skipped` : ''}. See Automation → Run history.`,
        );
      }
      // The run completed either way, so the dialog has done its job. A thrown
      // error leaves it open so the same selection can be retried.
      setGenOpen(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Could not generate');
    } finally {
      setGenerating(false);
    }
  }

  function toggleSelect(id: string) {
    setSelected((cur) => {
      const next = new Set(cur);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function runBulk(action: 'archive' | 'restore' | 'delete' | 'mark_ready' | 'mark_draft') {
    const ids = selectedVisible;
    if (!ids.length) return;

    // Deletion is the one that can't be walked back — archive is reversible, and
    // a status flip is just a flip.
    if (action === 'delete') {
      const ok = await confirm({
        title: `Delete ${ids.length} ad${ids.length === 1 ? '' : 's'}?`,
        message: 'This can’t be undone. Archive them instead if you only want them out of the way.',
        confirmLabel: 'Delete',
        destructive: true,
      });
      if (!ok) return;
    }

    setBulkBusy(true);
    try {
      const res = await fetch('/api/ad-generator/creatives/bulk', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ids, action }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);

      const n = json.count ?? ids.length;
      const noun = `${n} ad${n === 1 ? '' : 's'}`;
      toast.success(
        action === 'delete'
          ? `Deleted ${noun}`
          : action === 'archive'
            ? `Archived ${noun}`
            : action === 'restore'
              ? `Restored ${noun}`
              : `Marked ${noun} ${action === 'mark_ready' ? 'ready' : 'draft'}`,
      );

      // Apply locally rather than refetching: delete/archive/restore all remove
      // the rows from the current view, and a status flip is a field update.
      const gone = action === 'delete' || action === 'archive' || action === 'restore';
      setCreatives((cur) =>
        (cur ?? [])
          .filter((c) => !(gone && ids.includes(c.id)))
          .map((c) =>
            !gone && ids.includes(c.id)
              ? { ...c, status: action === 'mark_ready' ? 'ready' : 'draft' }
              : c,
          ),
      );
      setSelected(new Set());
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Bulk action failed');
    } finally {
      setBulkBusy(false);
    }
  }

  // Account branding for the mini previews (same as the editor merges in).
  const branding: AdData = useMemo(() => brandingFromAccount(accountData), [accountData]);

  // Vehicle/offer facets + the offer deadline, derived once per ad rather than
  // on every keystroke.
  const faceted: FacetedCreative[] = useMemo(
    () =>
      (creatives ?? []).map((c) => ({
        ...c,
        facets: facetsForAd(c.data),
        endsAt: offerEndsAt(c.data, c.expiresAt),
      })),
    [creatives],
  );

  // Everything EXCEPT the facets — status, source and search. Kept separate so
  // the facet counts below describe the list you're actually looking at (search
  // for "Silverado" and the Make picker shows only the makes still in play).
  const preFacet = useMemo(() => {
    let list = faceted;
    // 'archived' is served by its own query, so there's nothing to narrow here.
    if (statusFilter === 'published') list = list.filter((c) => c.status === 'ready');
    else if (statusFilter === 'draft') list = list.filter((c) => c.status !== 'ready');
    if (sourceFilter === 'auto') list = list.filter((c) => c.autoGenerated);
    else if (sourceFilter === 'manual') list = list.filter((c) => !c.autoGenerated);
    if (offerWindow !== 'all') {
      const now = new Date();
      list = list.filter((c) => matchesWindow(c.endsAt, offerWindow, now));
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      list = list.filter((c) => {
        const t = templates.find((x) => x.id === c.templateId);
        // Vehicle too: an ad named "Momentum — July lease" should still be
        // findable by typing the car it advertises.
        const vehicles = [c.data.vehicleName, c.data.o2_vehicleName].filter((v): v is string => !!v);
        return (
          c.name.toLowerCase().includes(q) ||
          (t?.name ?? c.templateId).toLowerCase().includes(q) ||
          vehicles.some((v) => v.toLowerCase().includes(q))
        );
      });
    }
    return list;
  }, [faceted, statusFilter, sourceFilter, offerWindow, search, templates]);

  const facetOptions = useMemo(() => buildFacetOptions(preFacet, facetSel), [preFacet, facetSel]);

  // Which pickers exist at all — from the whole account list, so the bar keeps
  // a stable shape while you filter (see FacetBar's `visibleFacets`).
  const visibleFacets = useMemo(() => {
    const all = buildFacetOptions(faceted, {});
    return FACET_KEYS.filter((k) => all[k].length > 1);
  }, [faceted]);

  // Ads only have a card view, so this is the grid.
  const visible = useMemo(
    () => preFacet.filter((c) => matchesFacets(c.facets, facetSel)),
    [preFacet, facetSel],
  );

  /** Ids currently visible — what "select all" means, and what a bulk action hits. */
  const visibleIds = useMemo(() => visible.map((c) => c.id), [visible]);
  const selectedVisible = useMemo(
    () => visibleIds.filter((id) => selected.has(id)),
    [visibleIds, selected],
  );

  // Switching sub-accounts carries the old rooftop's vehicles into a store that
  // doesn't sell them — a stale "Mazda" filter would show an empty Chevrolet
  // list and read as a loading bug.
  useEffect(() => {
    setFacetSel({});
    setOfferWindow('all');
  }, [accountKey]);

  async function createAd(templateId: string) {
    if (!accountKey) {
      toast.error('Select an account first');
      return;
    }
    setCreating(true);
    try {
      const t = templates.find((x) => x.id === templateId);
      const res = await fetch('/api/ad-generator/creatives', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountKey, name: `New ${t?.name ?? 'ad'}`, templateId, data: t?.defaults ?? {} }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
      router.push(`/ad-generator/${json.creative.id}`);
    } catch (err) {
      toast.error(`Couldn't create: ${err instanceof Error ? err.message : 'unknown error'}`);
      setCreating(false);
    }
  }

  // From scratch: a blank ad (empty doc) at the chosen name + starting size(s),
  // opened straight in the builder's ad mode so the designer starts on an empty
  // canvas with no layers.
  async function createBlank(name: string, sizes: CatalogSize[], vehicleMode: VehicleFieldsMode) {
    if (!accountKey) {
      toast.error('Select an account first');
      return;
    }
    const chosen = sizes.length ? sizes : [{ name: 'Square', width: 1080, height: 1080 } as CatalogSize];
    setCreating(true);
    try {
      const trimmed = name.trim() || 'Untitled ad';
      const docSizes = chosen.map((size, i) => {
        const slug = size.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
        return {
          id: slug || `size-${i}`,
          label: `${size.name} ${size.width}×${size.height}`,
          width: size.width,
          height: size.height,
        };
      });
      let doc = blankTemplateDoc(`blank-${Date.now()}`, trimmed, docSizes);
      // Optionally seed the vehicle/offer question set (single or dual) so a
      // from-scratch ad isn't a blank form — the offer engine gates on these
      // fields being present. Same merge path the builder's "Add offer fields"
      // action uses (fields + starter defaults, deduped by key).
      if (vehicleMode !== 'none') doc = addFieldKit(doc, vehicleMode);
      const res = await fetch('/api/ad-generator/creatives', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountKey, name: trimmed, templateId: 'blank', data: {}, doc }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
      router.push(`/ad-generator/builder?ad=${encodeURIComponent(json.creative.id)}${accountKey ? `&account=${encodeURIComponent(accountKey)}` : ''}&from=${encodeURIComponent('/ad-generator')}`);
    } catch (err) {
      toast.error(`Couldn't create: ${err instanceof Error ? err.message : 'unknown error'}`);
      setCreating(false);
    }
  }

  async function remove(id: string) {
    const name = (creatives ?? []).find((x) => x.id === id)?.name || 'this ad';
    const ok = await confirm({
      title: 'Delete ad',
      message: `Delete “${name}”? This can’t be undone.`,
      confirmLabel: 'Delete',
      destructive: true,
    });
    if (!ok) return;
    try {
      const res = await fetch(`/api/ad-generator/creatives/${id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setCreatives((c) => (c ?? []).filter((x) => x.id !== id));
      toast.success('Deleted');
    } catch (err) {
      toast.error(`Couldn't delete: ${err instanceof Error ? err.message : 'unknown error'}`);
    }
  }

  return (
    // Managers render inside the app shell's padded card; clients render bare,
    // so give them the same centered, padded content column the editor uses.
    <div className={!isManager ? 'mx-auto max-w-6xl px-6 py-8' : undefined}>
      {/* Clients have no app chrome — show their dealership's brand at the top.
          The impersonation escape sits to the right of the logo and only
          renders while a developer is viewing as this client (never for the
          client themselves). */}
      {!isManager && (
        <div className="mb-5 flex items-center justify-between gap-3 border-b border-[var(--border)] pb-4">
          <AccountLogo className="h-11 w-auto max-w-[220px] object-contain" />
          <ImpersonationEscape />
        </div>
      )}
      <div className="page-sticky-header mb-6">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <MegaphoneIcon className="w-7 h-7 text-[var(--primary)]" />
            <div>
              <h2 className="text-2xl font-bold">Ad Generator</h2>
              <p className="text-[var(--muted-foreground)] mt-1">
                Your account&rsquo;s ads. Open one to edit, or start a new one from a template.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap justify-end">
            {/* Settings cog → management links (Ad Sizes, Template Builder).
                Managers only — clients get a bare create-and-export surface. */}
            {isManager && (
            <div className="relative" ref={cogRef}>
              <button
                type="button"
                onClick={() => setCogOpen((v) => !v)}
                title="Settings"
                aria-label="Settings"
                className="flex items-center justify-center w-10 h-10 rounded-lg border border-[var(--border)] text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors"
              >
                <Cog6ToothIcon className="w-4 h-4" />
              </button>
              {cogOpen && (
                <div className="absolute right-0 top-full mt-1 z-30 w-56 glass-dropdown">
                  {(() => {
                    const acct = accountKey ? `?account=${encodeURIComponent(accountKey)}` : '';
                    const itemCls =
                      'flex w-full items-center gap-2 px-3 py-2 text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors';
                    return (
                      <>
                        <Link href={`/ad-generator/sizes${acct}`} onClick={() => setCogOpen(false)} className={itemCls}>
                          <RectangleGroupIcon className="w-4 h-4" />
                          Ad Sizes
                        </Link>
                        {isManager && (
                          <>
                            <Link href={`/ad-generator/templates${acct}`} onClick={() => setCogOpen(false)} className={itemCls}>
                              <DocumentTextIcon className="w-4 h-4" />
                              Disclaimer templates
                            </Link>
                            <Link href={`/ad-generator/oem-rules${acct}`} onClick={() => setCogOpen(false)} className={itemCls}>
                              <ShieldCheckIcon className="w-4 h-4" />
                              OEM compliance rules
                            </Link>
                            <Link href={`/ad-generator/automation${acct}`} onClick={() => setCogOpen(false)} className={itemCls}>
                              <BoltIcon className="w-4 h-4" />
                              Automation
                            </Link>
                          </>
                        )}
                      </>
                    );
                  })()}
                </div>
              )}
            </div>
            )}

            {/* New ad. Managers get a split menu (template library or a
                from-scratch build); clients get a single button that opens the
                template picker — they never touch the builder. */}
            {isManager ? (
            <div className="relative" ref={newRef}>
              <button
                type="button"
                onClick={() => setNewOpen((v) => !v)}
                disabled={!accountKey}
                className="flex items-center gap-1.5 px-3 h-10 text-sm rounded-lg border border-[var(--primary)] bg-[var(--primary)] text-white hover:bg-[var(--primary)]/90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <PlusIcon className="w-4 h-4" />
                New ad
                <ChevronDownIcon className={`w-3.5 h-3.5 transition-transform ${newOpen ? 'rotate-180' : ''}`} />
              </button>
              {newOpen && (
                <div className="absolute right-0 top-full mt-1 z-30 w-56 glass-dropdown">
                  <button
                    type="button"
                    onClick={() => {
                      setNewOpen(false);
                      setPickerOpen(true);
                    }}
                    className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors"
                  >
                    <MegaphoneIcon className="w-4 h-4 flex-shrink-0" />
                    <span>
                      From template library
                      <span className="block text-[11px] text-[var(--muted-foreground)]">Start from a ready-made layout.</span>
                    </span>
                  </button>
                  <button
                    type="button"
                    disabled={creating || !accountKey}
                    onClick={() => {
                      setNewOpen(false);
                      setScratchOpen(true);
                    }}
                    className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors disabled:opacity-50"
                  >
                    <Squares2X2Icon className="w-4 h-4 flex-shrink-0" />
                    <span>
                      From scratch
                      <span className="block text-[11px] text-[var(--muted-foreground)]">Name it and pick a size, then design in the builder.</span>
                    </span>
                  </button>
                  {/* Generating from the OEM feed is a way of making ads, so it
                      belongs with the other two rather than on the automation
                      dashboard. A run needs automation set up with a template
                      mapped, or it can only ever report "0 generated" — but the
                      entry point stays put and routes to the missing setup instead
                      of vanishing, which just looked like the feature was absent. */}
                  <div className="my-1 border-t border-[var(--border)]" />
                  {automationReady ? (
                    <button
                      type="button"
                      disabled={generating || !accountKey}
                      onClick={() => {
                        setNewOpen(false);
                        setGenOpen(true);
                      }}
                      className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--foreground)] hover:bg-[var(--muted)] transition-colors disabled:opacity-50"
                    >
                      <BoltIcon className={`w-4 h-4 flex-shrink-0 ${generating ? 'animate-pulse' : ''}`} />
                      <span>
                        Generate from OEM offers
                        <span className="block text-[11px] text-[var(--muted-foreground)]">
                          Pick the models and offer types, then build drafts.
                        </span>
                      </span>
                    </button>
                  ) : (
                    <Link
                      href={`/ad-generator/automation${accountKey ? `?account=${encodeURIComponent(accountKey)}` : ''}`}
                      onClick={() => setNewOpen(false)}
                      className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-[var(--muted-foreground)] hover:bg-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
                    >
                      <BoltIcon className="w-4 h-4 flex-shrink-0" />
                      <span>
                        Generate from OEM offers
                        <span className="block text-[11px] text-[var(--muted-foreground)]">
                          {automationBlocker === 'no-template'
                            ? 'Needs a template mapped — open automation settings.'
                            : 'Set up ad automation for this sub-account first.'}
                        </span>
                      </span>
                    </Link>
                  )}
                </div>
              )}
            </div>
            ) : (
              <button
                type="button"
                onClick={() => setPickerOpen(true)}
                disabled={!accountKey}
                className="flex items-center gap-1.5 px-3 h-10 text-sm rounded-lg border border-[var(--primary)] bg-[var(--primary)] text-white hover:bg-[var(--primary)]/90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <PlusIcon className="w-4 h-4" />
                New ad
              </button>
            )}
          </div>
        </div>
      </div>

      {creatives && creatives.length > 0 && (
        <div className="mb-4">
          {/* Status, source, offer window and the vehicle facets all live in the
              Filters popover — they answer one question, so they get one
              control and one count instead of a crowded toolbar row. */}
          <ListToolbar
            leading={
              <div className="flex items-center gap-3">
                <span className="text-sm text-[var(--muted-foreground)]">
                  {visible.length} {visible.length === 1 ? 'ad' : 'ads'}
                </span>
                {visible.length > 0 && (
                  <button
                    type="button"
                    onClick={() =>
                      setSelected(
                        selectedVisible.length === visible.length ? new Set() : new Set(visibleIds),
                      )
                    }
                    className="text-xs font-medium text-[var(--muted-foreground)] transition-colors hover:text-[var(--foreground)]"
                  >
                    {selectedVisible.length === visible.length ? 'Clear selection' : 'Select all'}
                  </button>
                )}
              </div>
            }
            search={search}
            onSearchChange={setSearch}
            searchPlaceholder="Search ads…"
            trailing={
              <AdFilterPanel
                status={statusFilter}
                onStatusChange={setStatusFilter}
                source={sourceFilter}
                onSourceChange={setSourceFilter}
                offerWindow={offerWindow}
                onOfferWindowChange={setOfferWindow}
                options={facetOptions}
                visibleFacets={visibleFacets}
                selection={facetSel}
                onSelectionChange={setFacetSel}
                // Until the job has produced something, the split is noise.
                showSource={(creatives ?? []).some((c) => c.autoGenerated)}
              />
            }
          />
        </div>
      )}

      {!accountKey ? (
        <div className="glass-card rounded-2xl p-12 text-center flex flex-col items-center">
          <div className="w-16 h-16 rounded-2xl bg-[var(--muted)] flex items-center justify-center mb-4">
            <MegaphoneIcon className="w-8 h-8 text-[var(--muted-foreground)]" />
          </div>
          <h2 className="text-lg font-semibold mb-1">Select an account</h2>
          <p className="text-sm text-[var(--muted-foreground)] max-w-md">
            Choose an account in the top bar to see and create its ads.
          </p>
        </div>
      ) : creatives === null ? (
        <div className="text-sm text-[var(--muted-foreground)]">Loading…</div>
      ) : creatives.length === 0 ? (
        <div className="glass-card rounded-2xl p-12 text-center flex flex-col items-center">
          <div className="w-16 h-16 rounded-2xl bg-[var(--muted)] flex items-center justify-center mb-4">
            <MegaphoneIcon className="w-8 h-8 text-[var(--muted-foreground)]" />
          </div>
          <h2 className="text-lg font-semibold mb-1">No ads yet</h2>
          <p className="text-sm text-[var(--muted-foreground)] max-w-md mb-6">
            Start from a template — pick a layout, drop in the offer + vehicle, and export sized for every channel.
          </p>
          <button
            type="button"
            onClick={() => setPickerOpen(true)}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-[var(--primary)] text-white text-sm font-medium hover:opacity-90 transition-opacity"
          >
            <PlusIcon className="w-4 h-4" />
            Create your first ad
          </button>
        </div>
      ) : visible.length === 0 ? (
        <div className="glass-card rounded-2xl p-10 text-center text-sm text-[var(--muted-foreground)]">
          No ads match the current filters.
          {countSelected(facetSel) + (statusFilter !== 'all' ? 1 : 0) + (sourceFilter !== 'all' ? 1 : 0) + (offerWindow !== 'all' ? 1 : 0) > 0 && (
            <button
              type="button"
              onClick={() => {
                setFacetSel({});
                setStatusFilter('all');
                setSourceFilter('all');
                setOfferWindow('all');
              }}
              className="ml-1.5 font-medium text-[var(--primary)] hover:underline"
            >
              Clear filters
            </button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
          {visible.map((c) => {
            // Render the thumbnail from the ad's own snapshot when present, so it
            // matches the editor/export even if the master template later changed.
            const template = c.doc ? adTemplateFromDoc(c.id, c.doc) : templates.find((t) => t.id === c.templateId);
            return (
              <div
                key={c.id}
                role="button"
                tabIndex={0}
                // With a selection open the card toggles instead of navigating —
                // clicking through to the editor mid-selection is never what you
                // meant, and it loses the selection on the way.
                onClick={() => (selected.size > 0 ? toggleSelect(c.id) : router.push(`/ad-generator/${c.id}`))}
                onKeyDown={(e) => {
                  if (e.key !== 'Enter' && e.key !== ' ') return;
                  e.preventDefault();
                  if (selected.size > 0) toggleSelect(c.id);
                  else router.push(`/ad-generator/${c.id}`);
                }}
                className={`glass-card group relative cursor-pointer overflow-hidden rounded-2xl border text-left transition-colors ${
                  selected.has(c.id)
                    ? 'border-[var(--primary)] ring-1 ring-[var(--primary)]'
                    : 'border-[var(--border)] hover:border-[var(--primary)]'
                }`}
              >
                {/* Hidden until hover or selection, so an unselected grid stays
                    clean but the affordance is one movement away. */}
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    toggleSelect(c.id);
                  }}
                  aria-label={selected.has(c.id) ? `Deselect ${c.name}` : `Select ${c.name}`}
                  aria-pressed={selected.has(c.id)}
                  className={`absolute left-2.5 top-2.5 z-10 flex h-5 w-5 items-center justify-center rounded-md border transition-opacity ${
                    selected.has(c.id)
                      ? 'border-[var(--primary)] bg-[var(--primary)] opacity-100'
                      : 'border-[var(--border)] bg-[var(--background)]/90 opacity-0 group-hover:opacity-100 focus-visible:opacity-100'
                  }`}
                >
                  {selected.has(c.id) && (
                    <svg viewBox="0 0 12 12" className="h-3 w-3 text-white" fill="none">
                      <path
                        d="M2.5 6.5l2.5 2.5 4.5-5"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  )}
                </button>
                <AdPreviewThumb template={template} data={c.data} branding={branding} />
                <div className="flex items-start justify-between gap-2 p-3">
                  <div className="min-w-0">
                    <div className="truncate text-sm font-semibold text-[var(--foreground)]">{c.name}</div>
                    <div className="mt-0.5 flex items-center gap-1.5 text-[11px] text-[var(--muted-foreground)]">
                      <span
                        className={`rounded px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide ${
                          c.status === 'ready' ? 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400' : 'bg-[var(--muted)] text-[var(--muted-foreground)]'
                        }`}
                      >
                        {c.status}
                      </span>
                      {c.autoGenerated && (
                        <span
                          title="Built by the nightly offer job, not by hand"
                          className="flex items-center gap-0.5 rounded bg-[var(--primary)]/12 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-[var(--primary)]"
                        >
                          <BoltIcon className="h-2.5 w-2.5" />
                          Auto
                        </span>
                      )}
                      <span className="truncate">{template?.name ?? c.templateId}</span>
                    </div>
                    <div className="mt-0.5 text-[10px] text-[var(--muted-foreground)]">
                      Updated {new Date(c.updatedAt).toLocaleDateString()}
                      {/* Auto-generated ads are pinned to an offer that expires, so
                          the useful date is when it stops being runnable — a
                          human-built ad has no such deadline. */}
                      {c.autoGenerated && c.expiresAt && (
                        <> · offer ends {new Date(c.expiresAt).toLocaleDateString()}</>
                      )}
                    </div>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      remove(c.id);
                    }}
                    title="Delete"
                    className="flex-shrink-0 rounded-md p-1.5 text-[var(--muted-foreground)] opacity-0 transition-opacity hover:bg-red-500/10 hover:text-red-500 group-hover:opacity-100"
                  >
                    <TrashIcon className="h-4 w-4" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {pickerOpen && typeof document !== 'undefined' && createPortal(
        <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-black/60 p-4 pt-10 sm:pt-16" onClick={() => !creating && setPickerOpen(false)}>
          <div className="flex max-h-[85vh] w-full max-w-4xl flex-col rounded-2xl border border-[var(--border)] bg-[var(--card-strong)] shadow-2xl backdrop-blur-2xl" onClick={(e) => e.stopPropagation()}>
            {/* Header */}
            <div className="flex items-start justify-between gap-3 border-b border-[var(--border)] p-5">
              <div className="flex items-center gap-3">
                <span className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl bg-[var(--primary)]/10 text-[var(--primary)]">
                  <MegaphoneIcon className="h-5 w-5" />
                </span>
                <div>
                  <h2 className="text-lg font-bold text-[var(--foreground)]">Start a new ad</h2>
                  <p className="text-xs text-[var(--muted-foreground)]">
                    {isManager
                      ? 'Pick a template to begin — you can edit everything after.'
                      : 'Pick a template, then fill in your offer and vehicle.'}
                  </p>
                </div>
              </div>
              <button onClick={() => setPickerOpen(false)} className="rounded-lg p-1.5 text-[var(--muted-foreground)] transition-colors hover:bg-[var(--muted)] hover:text-[var(--foreground)]">
                <XMarkIcon className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="min-h-0 flex-1 overflow-y-auto p-5">
              {pickerTemplates.length === 0 ? (
                <div className="rounded-xl border border-dashed border-[var(--border)] p-12 text-center">
                  <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--muted)]">
                    <MegaphoneIcon className="h-6 w-6 text-[var(--muted-foreground)]" />
                  </div>
                  {isManager ? (
                    <>
                      <p className="text-sm text-[var(--muted-foreground)]">No templates for this account&rsquo;s industry yet.</p>
                      <button
                        type="button"
                        disabled={creating}
                        onClick={() => {
                          setPickerOpen(false);
                          setScratchOpen(true);
                        }}
                        className="mt-4 inline-flex items-center gap-1.5 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90 disabled:opacity-50"
                      >
                        <Squares2X2Icon className="h-4 w-4" />
                        Start from scratch
                      </button>
                    </>
                  ) : (
                    <p className="mx-auto max-w-sm text-sm text-[var(--muted-foreground)]">
                      No ad templates have been published for your account yet. Your Loomi team will add this month&rsquo;s offer template here.
                    </p>
                  )}
                </div>
              ) : (
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {pickerTemplates.map((t) => (
                    <button
                      key={t.id}
                      disabled={creating}
                      onClick={() => createAd(t.id)}
                      className="group flex flex-col overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--card)] text-left transition-all hover:-translate-y-0.5 hover:border-[var(--primary)] hover:shadow-lg disabled:pointer-events-none disabled:opacity-60"
                    >
                      <div className="relative overflow-hidden border-b border-[var(--border)]">
                        <AdPreviewThumb template={t} data={{}} branding={branding} height={190} />
                        <div className="pointer-events-none absolute inset-0 flex items-end justify-center bg-gradient-to-t from-black/55 to-transparent p-3 opacity-0 transition-opacity group-hover:opacity-100">
                          <span className="rounded-lg bg-white/95 px-3 py-1 text-xs font-semibold text-black shadow">Use this template</span>
                        </div>
                      </div>
                      <div className="p-3">
                        <div className="truncate text-sm font-semibold text-[var(--foreground)]">{t.name}</div>
                        {t.description && <div className="mt-0.5 line-clamp-2 text-[11px] leading-snug text-[var(--muted-foreground)]">{t.description}</div>}
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Footer — template count + from-scratch (managers, when templates exist) */}
            {isManager && pickerTemplates.length > 0 && (
              <div className="flex items-center justify-between gap-2 border-t border-[var(--border)] p-4">
                <span className="text-[11px] text-[var(--muted-foreground)]">
                  {pickerTemplates.length} template{pickerTemplates.length === 1 ? '' : 's'} available
                </span>
                <button
                  type="button"
                  disabled={creating}
                  onClick={() => {
                    setPickerOpen(false);
                    setScratchOpen(true);
                  }}
                  className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-medium text-[var(--foreground)] transition-colors hover:border-[var(--primary)] hover:text-[var(--primary)] disabled:opacity-50"
                >
                  <Squares2X2Icon className="h-4 w-4" />
                  Start from scratch
                </button>
              </div>
            )}
          </div>
        </div>,
        document.body,
      )}

      {scratchOpen && (
        <ScratchSetupModal
          creating={creating}
          onClose={() => !creating && setScratchOpen(false)}
          onStart={(name, sizes, vehicleMode) => void createBlank(name, sizes, vehicleMode)}
        />
      )}

      {selectedVisible.length > 0 && (
        <BulkActionDock
          count={selectedVisible.length}
          itemLabel={selectedVisible.length === 1 ? 'ad' : 'ads'}
          onClose={() => setSelected(new Set())}
          actions={
            statusFilter === 'archived'
              ? [
                  {
                    id: 'restore',
                    label: 'Restore',
                    icon: <ArrowUturnLeftIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('restore'),
                  },
                  {
                    id: 'delete',
                    label: 'Delete',
                    icon: <TrashIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    danger: true,
                    onClick: () => void runBulk('delete'),
                  },
                ]
              : [
                  {
                    id: 'mark-ready',
                    label: 'Mark ready',
                    icon: <CheckCircleIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('mark_ready'),
                  },
                  {
                    id: 'mark-draft',
                    label: 'Mark draft',
                    icon: <PencilSquareIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('mark_draft'),
                  },
                  {
                    id: 'archive',
                    label: 'Archive',
                    icon: <ArchiveBoxIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    onClick: () => void runBulk('archive'),
                  },
                  {
                    id: 'delete',
                    label: 'Delete',
                    icon: <TrashIcon className="h-4 w-4" />,
                    disabled: bulkBusy,
                    danger: true,
                    onClick: () => void runBulk('delete'),
                  },
                ]
          }
        />
      )}

      {genOpen && (
        <GenerateOffersModal
          candidates={candidates}
          maxAdsPerRun={maxAdsPerRun}
          busy={generating}
          onCancel={() => !generating && setGenOpen(false)}
          onGenerate={(scope) => void generateFromOffers(scope)}
        />
      )}
    </div>
  );
}

/**
 * "From scratch" setup step — name the ad and pick a starting size before the
 * builder opens, so a brand-new design starts at the right dimensions instead
 * of always defaulting to a 1080 square. Sizes come from the shared catalog.
 */
function ScratchSetupModal({
  creating,
  onClose,
  onStart,
}: {
  creating: boolean;
  onClose: () => void;
  onStart: (name: string, sizes: CatalogSize[], vehicleMode: VehicleFieldsMode) => void;
}) {
  const groups = useMemo(() => catalogByCategory(), []);
  const [name, setName] = useState('Untitled ad');
  const [vehicleMode, setVehicleMode] = useState<VehicleFieldsMode>('none');
  const [selected, setSelected] = useState<CatalogSize[]>(() => [AD_SIZE_CATALOG_DEFAULT(groups)]);
  const toggle = (s: CatalogSize) =>
    setSelected((cur) => (cur.some((x) => x.name === s.name) ? cur.filter((x) => x.name !== s.name) : [...cur, s]));

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-black/60 p-4 pt-16" onClick={onClose}>
      <div className="w-full max-w-lg rounded-2xl border border-[var(--border)] bg-[var(--card-strong)] p-5 shadow-xl backdrop-blur-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="mb-4 flex items-start justify-between">
          <div>
            <h2 className="text-sm font-bold text-[var(--foreground)]">Start from scratch</h2>
            <p className="text-xs text-[var(--muted-foreground)]">Name it and pick one or more starting sizes — you can add more or change everything in the builder.</p>
          </div>
          <button onClick={onClose} className="rounded-md p-1 text-[var(--muted-foreground)] transition-colors hover:bg-[var(--muted)] hover:text-[var(--foreground)]">
            <XMarkIcon className="h-5 w-5" />
          </button>
        </div>

        <label className="mb-4 block">
          <span className="mb-1 block text-xs font-medium text-[var(--foreground)]">Name</span>
          <input
            autoFocus
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Untitled ad"
            className="w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none focus:border-[var(--primary)]"
          />
        </label>

        <div className="mb-4">
          <span className="mb-1.5 block text-xs font-medium text-[var(--foreground)]">Vehicle offer fields <span className="font-normal text-[var(--muted-foreground)]">— seed the offer questions, or start with a blank form</span></span>
          <div className="flex flex-wrap gap-1.5">
            {([
              { mode: 'none', label: 'Blank' },
              { mode: 'single', label: 'Single vehicle' },
              { mode: 'dual', label: 'Two vehicles' },
            ] as { mode: VehicleFieldsMode; label: string }[]).map((opt) => (
              <button
                key={opt.mode}
                type="button"
                onClick={() => setVehicleMode(opt.mode)}
                className={`rounded-lg border px-3 py-1.5 text-xs font-medium transition-colors ${
                  vehicleMode === opt.mode ? 'border-[var(--primary)] bg-[var(--primary)]/10 text-[var(--primary)]' : 'border-[var(--border)] text-[var(--muted-foreground)] hover:border-[var(--primary)] hover:text-[var(--foreground)]'
                }`}
              >
                {opt.label}
              </button>
            ))}
          </div>
        </div>

        <div className="mb-1 flex items-baseline justify-between">
          <span className="text-xs font-medium text-[var(--foreground)]">Starting sizes</span>
          <span className="text-[11px] text-[var(--muted-foreground)]">{selected.length} selected</span>
        </div>
        <div className="max-h-[44vh] space-y-4 overflow-y-auto pr-1">
          {groups.map((grp) => (
            <div key={grp.category}>
              <div className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-[var(--muted-foreground)]">{grp.label}</div>
              <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
                {grp.sizes.map((s) => {
                  const ratio = s.width / s.height;
                  const boxW = ratio >= 1 ? 28 : 28 * ratio;
                  const boxH = ratio >= 1 ? 28 / ratio : 28;
                  const on = selected.some((x) => x.name === s.name);
                  return (
                    <button
                      key={s.name}
                      type="button"
                      onClick={() => toggle(s)}
                      aria-pressed={on}
                      title={`${s.name} · ${s.width}×${s.height}`}
                      className={`relative flex items-center gap-2 rounded-xl border p-2.5 text-left transition-colors ${
                        on ? 'border-[var(--primary)] ring-1 ring-[var(--primary)]/40' : 'border-[var(--border)] hover:border-[var(--primary)]'
                      }`}
                    >
                      {on && (
                        <span className="absolute right-1.5 top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-[var(--primary)] text-white">
                          <CheckIcon className="h-3 w-3" />
                        </span>
                      )}
                      <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded bg-[var(--muted)]/50">
                        <div className="rounded-[2px] bg-[var(--primary)]/30 ring-1 ring-[var(--primary)]/50" style={{ width: boxW, height: boxH }} />
                      </div>
                      <div className="min-w-0">
                        <div className="truncate text-[11px] font-semibold text-[var(--foreground)]">{s.name}</div>
                        <div className="truncate text-[10px] text-[var(--muted-foreground)]">
                          {s.width}×{s.height} · {aspectLabel(s.width, s.height)}
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-5 flex items-center justify-end gap-2">
          <button onClick={onClose} disabled={creating} className="rounded-lg px-3 py-2 text-sm text-[var(--muted-foreground)] transition-colors hover:text-[var(--foreground)] disabled:opacity-50">
            Cancel
          </button>
          <button
            onClick={() => onStart(name, selected, vehicleMode)}
            disabled={creating || selected.length === 0}
            className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Squares2X2Icon className="h-4 w-4" />
            {creating ? 'Creating…' : selected.length > 1 ? `Start with ${selected.length} sizes` : 'Start designing'}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}

/** Default starting size for the scratch modal — Instagram Square if present
 *  (matches the prior 1080 default), else the first catalog size. */
function AD_SIZE_CATALOG_DEFAULT(groups: { sizes: CatalogSize[] }[]): CatalogSize {
  const all = groups.flatMap((g) => g.sizes);
  return all.find((s) => s.name === 'Instagram Square') ?? all[0];
}
