/**
 * Ad creative — GET / PATCH / DELETE one (by id). Flag- + auth-gated.
 */
import { NextRequest, NextResponse } from 'next/server';
import { getAuthSession, getAccountScope, canAccessAccount, forbidden } from '@/lib/api-auth';
import { adGeneratorAllowed } from '@/lib/ad-generator/access';
import { prisma } from '@/lib/prisma';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';
import { designHash, resolveSyncState } from '@/lib/ad-generator/template-sync';
import { changedOfferFields } from '@/lib/ad-generator/offer-edit';
import type { AdData } from '@/lib/ad-generator/types';

/** Prefix for the note left when a person changes an ad's offer values. */
const OFFER_EDITED_NOTE = 'Offer values were edited by hand, so this ad no longer states the manufacturer\'s published terms —';

function safeData(raw: string | null): AdData | null {
  if (!raw) return null;
  try {
    return JSON.parse(raw) as AdData;
  } catch {
    return null;
  }
}

function parseNotes(raw: string | null): string[] {
  if (!raw) return [];
  try {
    const v = JSON.parse(raw);
    return Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];
  } catch {
    return [];
  }
}

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** Parse a stored doc; null when absent or unreadable. */
function safeDoc(raw: string | null): TemplateDoc | null {
  if (!raw) return null;
  try {
    const v = JSON.parse(raw) as TemplateDoc;
    return Array.isArray(v?.sizes) ? v : null;
  } catch {
    return null;
  }
}

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  try {
    const row = await prisma.adCreative.findUnique({ where: { id } });
    if (!row) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    // Only readable within the caller's account scope.
    if (!canAccessAccount(getAccountScope(session), row.accountKey)) return forbidden();
    let data: Record<string, string> = {};
    try {
      data = JSON.parse(row.data) ?? {};
    } catch {
      data = {};
    }
    let doc: unknown = null;
    if (row.doc) {
      try {
        doc = JSON.parse(row.doc);
      } catch {
        doc = null;
      }
    }
    return NextResponse.json({
      creative: {
        id: row.id,
        accountKey: row.accountKey,
        name: row.name,
        templateId: row.templateId,
        status: row.status,
        doc,
        data,
        // Template link, so the builder can warn before an edit detaches the ad.
        templateSync: resolveSyncState(row),
        templateDocHash: row.templateDocHash,
        docEditedAt: row.docEditedAt,
        autoGenerated: row.autoGenerated,
      },
    });
  } catch (err) {
    console.warn('[api/ad-generator/creatives/[id]] GET failed:', err);
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
}

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  // Guard the target is within scope before mutating it.
  const existing = await prisma.adCreative.findUnique({
    where: { id },
    select: {
      accountKey: true,
      doc: true,
      templateSync: true,
      autoGenerated: true,
      // Needed to tell an offer EDIT from an ordinary autosave — see offer-edit.
      data: true,
      status: true,
      reviewNotes: true,
      offerEditedAt: true,
    },
  });
  if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  if (!canAccessAccount(getAccountScope(session), existing.accountKey)) return forbidden();

  let body: {
    name?: string;
    data?: Record<string, string>;
    status?: string;
    thumbnailUrl?: string;
    doc?: unknown;
    /** Only `detached` is honored — see below. */
    templateSync?: string;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  const data: Record<string, unknown> = {};
  if (typeof body.name === 'string') data.name = body.name.trim() || 'Untitled ad';
  if (body.data && typeof body.data === 'object') {
    const next = body.data as AdData;
    data.data = JSON.stringify(next);

    // ── did a person change the OFFER? ──
    //
    // Only meaningful on a generated ad: a hand-built one never claimed to be
    // stating the manufacturer's numbers, so there is nothing to have departed
    // from. Compared field by field rather than trusting that data was sent,
    // because the form autosaves as you type and posts the whole blob — the same
    // distinction `docEditedAt` draws below by hashing the design.
    if (existing.autoGenerated) {
      const prev = safeData(existing.data);
      const changed = changedOfferFields(prev, next);
      if (changed.length > 0) {
        data.offerEditedAt = new Date();

        // Demote an approved ad. Approval was granted against the
        // manufacturer's numbers; changing them afterward is exactly the case
        // where riding a stale approval is dangerous. Same posture as
        // `expire-ads`, which demotes a `ready` ad whose offer has died.
        if (existing.status === 'ready' && body.status !== 'draft') {
          data.status = 'draft';
        }

        // Recorded on the ad, not just in a column, so the reason travels with
        // it into the review queue and the compare view. Naming the fields
        // beats "the offer was edited", which sends a reviewer diffing screens.
        const notes = parseNotes(existing.reviewNotes).filter((n) => !n.startsWith(OFFER_EDITED_NOTE));
        notes.unshift(`${OFFER_EDITED_NOTE} ${changed.join(', ')}.`);
        data.reviewNotes = JSON.stringify(notes);
      }
    }
  }
  if (typeof body.status === 'string') data.status = body.status === 'ready' ? 'ready' : 'draft';
  if (typeof body.thumbnailUrl === 'string') data.thumbnailUrl = body.thumbnailUrl;
  // Stop following the template, without changing the design. Detaching is
  // always safe, so the client may ask for it directly; RE-linking is not — it
  // has to re-preflight and re-render — so it only happens via the sync route.
  if (body.templateSync === 'detached') {
    data.templateSync = 'detached';
    data.docEditedAt = new Date();
  }
  // The ad's own design copy (edited in the builder's ad mode).
  if (body.doc && typeof body.doc === 'object' && Array.isArray((body.doc as { sizes?: unknown }).sizes)) {
    const nextDoc = body.doc as TemplateDoc;
    data.doc = JSON.stringify(nextDoc);
    // Editing an ad's own design detaches it from its template — customizing IS
    // the opt-out, so there's no separate switch to forget.
    //
    // Gated on the design actually having CHANGED, not merely on a doc being
    // sent: the builder posts the whole doc on every save, so a user who only
    // corrected a payment would otherwise silently stop receiving template
    // fixes. Comparing render-relevant hashes is exactly that distinction.
    const prev = safeDoc(existing.doc);
    const designChanged = !prev || designHash(prev) !== designHash(nextDoc);
    if (designChanged) {
      data.templateSync = 'detached';
      data.docEditedAt = new Date();
    }
  }

  try {
    const row = await prisma.adCreative.update({ where: { id }, data });
    return NextResponse.json({
      creative: {
        id: row.id,
        name: row.name,
        status: row.status,
        // So the builder can tell the user their edit just detached the ad.
        templateSync: resolveSyncState(row),
      },
    });
  } catch (err) {
    console.error('[api/ad-generator/creatives/[id]] update failed:', err);
    return NextResponse.json({ error: 'Could not update' }, { status: 500 });
  }
}

export async function DELETE(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  const existing = await prisma.adCreative.findUnique({ where: { id }, select: { accountKey: true } });
  if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  if (!canAccessAccount(getAccountScope(session), existing.accountKey)) return forbidden();
  try {
    await prisma.adCreative.delete({ where: { id } });
    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error('[api/ad-generator/creatives/[id]] delete failed:', err);
    return NextResponse.json({ error: 'Could not delete' }, { status: 500 });
  }
}
