/**
 * Ad creative — GET / PATCH / DELETE one (by id). Flag- + auth-gated.
 */
import { NextRequest, NextResponse } from 'next/server';
import { getAuthSession, getAccountScope, canAccessAccount, forbidden } from '@/lib/api-auth';
import { adGeneratorAllowed } from '@/lib/ad-generator/access';
import { prisma } from '@/lib/prisma';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';
import { designHash, resolveSyncState } from '@/lib/ad-generator/template-sync';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** Parse a stored doc; null when absent or unreadable. */
function safeDoc(raw: string | null): TemplateDoc | null {
  if (!raw) return null;
  try {
    const v = JSON.parse(raw) as TemplateDoc;
    return Array.isArray(v?.sizes) ? v : null;
  } catch {
    return null;
  }
}

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  try {
    const row = await prisma.adCreative.findUnique({ where: { id } });
    if (!row) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    // Only readable within the caller's account scope.
    if (!canAccessAccount(getAccountScope(session), row.accountKey)) return forbidden();
    let data: Record<string, string> = {};
    try {
      data = JSON.parse(row.data) ?? {};
    } catch {
      data = {};
    }
    let doc: unknown = null;
    if (row.doc) {
      try {
        doc = JSON.parse(row.doc);
      } catch {
        doc = null;
      }
    }
    return NextResponse.json({
      creative: {
        id: row.id,
        accountKey: row.accountKey,
        name: row.name,
        templateId: row.templateId,
        status: row.status,
        doc,
        data,
        // Template link, so the builder can warn before an edit detaches the ad.
        templateSync: resolveSyncState(row),
        templateDocHash: row.templateDocHash,
        docEditedAt: row.docEditedAt,
        autoGenerated: row.autoGenerated,
      },
    });
  } catch (err) {
    console.warn('[api/ad-generator/creatives/[id]] GET failed:', err);
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
}

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  // Guard the target is within scope before mutating it.
  const existing = await prisma.adCreative.findUnique({
    where: { id },
    select: { accountKey: true, doc: true, templateSync: true, autoGenerated: true },
  });
  if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  if (!canAccessAccount(getAccountScope(session), existing.accountKey)) return forbidden();

  let body: {
    name?: string;
    data?: Record<string, string>;
    status?: string;
    thumbnailUrl?: string;
    doc?: unknown;
    /** Only `detached` is honored — see below. */
    templateSync?: string;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  const data: Record<string, unknown> = {};
  if (typeof body.name === 'string') data.name = body.name.trim() || 'Untitled ad';
  if (body.data && typeof body.data === 'object') data.data = JSON.stringify(body.data);
  if (typeof body.status === 'string') data.status = body.status === 'ready' ? 'ready' : 'draft';
  if (typeof body.thumbnailUrl === 'string') data.thumbnailUrl = body.thumbnailUrl;
  // Stop following the template, without changing the design. Detaching is
  // always safe, so the client may ask for it directly; RE-linking is not — it
  // has to re-preflight and re-render — so it only happens via the sync route.
  if (body.templateSync === 'detached') {
    data.templateSync = 'detached';
    data.docEditedAt = new Date();
  }
  // The ad's own design copy (edited in the builder's ad mode).
  if (body.doc && typeof body.doc === 'object' && Array.isArray((body.doc as { sizes?: unknown }).sizes)) {
    const nextDoc = body.doc as TemplateDoc;
    data.doc = JSON.stringify(nextDoc);
    // Editing an ad's own design detaches it from its template — customizing IS
    // the opt-out, so there's no separate switch to forget.
    //
    // Gated on the design actually having CHANGED, not merely on a doc being
    // sent: the builder posts the whole doc on every save, so a user who only
    // corrected a payment would otherwise silently stop receiving template
    // fixes. Comparing render-relevant hashes is exactly that distinction.
    const prev = safeDoc(existing.doc);
    const designChanged = !prev || designHash(prev) !== designHash(nextDoc);
    if (designChanged) {
      data.templateSync = 'detached';
      data.docEditedAt = new Date();
    }
  }

  try {
    const row = await prisma.adCreative.update({ where: { id }, data });
    return NextResponse.json({
      creative: {
        id: row.id,
        name: row.name,
        status: row.status,
        // So the builder can tell the user their edit just detached the ad.
        templateSync: resolveSyncState(row),
      },
    });
  } catch (err) {
    console.error('[api/ad-generator/creatives/[id]] update failed:', err);
    return NextResponse.json({ error: 'Could not update' }, { status: 500 });
  }
}

export async function DELETE(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  const existing = await prisma.adCreative.findUnique({ where: { id }, select: { accountKey: true } });
  if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  if (!canAccessAccount(getAccountScope(session), existing.accountKey)) return forbidden();
  try {
    await prisma.adCreative.delete({ where: { id } });
    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error('[api/ad-generator/creatives/[id]] delete failed:', err);
    return NextResponse.json({ error: 'Could not delete' }, { status: 500 });
  }
}
