/**
 * "What would saving this template do to the ads already built from it?"
 * — POST /api/ad-generator/templates-doc/[id]/sync-impact
 *
 * The builder calls this with the doc it is ABOUT to save, so the save-time
 * prompt can say what it's actually proposing: which ads follow the template,
 * which of those are still running, and whether the edit is cosmetic or moves the
 * data contract. Read-only — nothing is applied here.
 *
 * POST rather than GET because the incoming doc is the input, and it's far too
 * big for a query string.
 */
import { NextRequest, NextResponse } from 'next/server';
import { requirePermission } from '@/lib/permissions/require';
import { adGeneratorAllowed } from '@/lib/ad-generator/access';
import { prisma } from '@/lib/prisma';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';
import {
  classifyDocChange,
  designHash,
  isBehindTemplate,
  resolveSyncState,
  type DocChange,
} from '@/lib/ad-generator/template-sync';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface ImpactAd {
  id: string;
  name: string;
  accountKey: string;
  status: string;
  autoGenerated: boolean;
  /** Null on hand-built ads — they aren't pinned to an offer window. */
  expiresAt: string | null;
  /** True when the offer behind it hasn't ended yet (or it never expires). */
  offerActive: boolean;
  /** synced → may be updated; detached → the ad owns its design. */
  sync: 'synced' | 'detached';
  /** Set when a person edited this ad's design, so the UI can say so. */
  docEditedAt: string | null;
  /** False when the ad's design already matches the incoming doc. */
  behind: boolean;
}

function parseDoc(raw: string): TemplateDoc | null {
  try {
    const v = JSON.parse(raw) as TemplateDoc;
    return Array.isArray(v?.sizes) && Array.isArray(v?.elements) && v?.layouts ? v : null;
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  // Same gate as saving the template: only someone who can edit it can be asked
  // what editing it would do.
  const { error } = await requirePermission('studio.adgen.edit');
  if (error) return error;

  const { id } = await params;
  let body: { doc?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  const nextDoc =
    body.doc && typeof body.doc === 'object' && Array.isArray((body.doc as { sizes?: unknown }).sizes)
      ? (body.doc as TemplateDoc)
      : null;
  if (!nextDoc) return NextResponse.json({ error: 'A doc is required' }, { status: 400 });

  const nextHash = designHash(nextDoc);

  let ads: ImpactAd[] = [];
  // The design a following ad is actually ON, which is the baseline the change
  // must be measured against.
  //
  // NOT the stored template row: the builder autosaves every edit, so by the time
  // anyone presses Save the template already holds the new design and comparing
  // against it would report "nothing changed" for a change the ads haven't got.
  // The real question is always template-vs-ads.
  let baselineDoc: TemplateDoc | null = null;
  try {
    const rows = await prisma.adCreative.findMany({
      where: { templateId: id, archivedAt: null },
      select: {
        id: true,
        name: true,
        accountKey: true,
        status: true,
        autoGenerated: true,
        expiresAt: true,
        templateSync: true,
        templateDocHash: true,
        docEditedAt: true,
        doc: true,
      },
      orderBy: { updatedAt: 'desc' },
      // A bound, so one template used by thousands of ads can't turn a save
      // dialog into a table scan. See `truncated` below — the count is exact
      // even when the list isn't.
      take: 500,
    });
    const now = Date.now();
    ads = rows.map((r) => ({
      id: r.id,
      name: r.name,
      accountKey: r.accountKey,
      status: r.status,
      autoGenerated: r.autoGenerated,
      expiresAt: r.expiresAt ? r.expiresAt.toISOString() : null,
      // No expiry = nothing has ended, which is the normal case for a hand-built
      // ad. Only an offer-pinned ad can be past its window.
      offerActive: !r.expiresAt || r.expiresAt.getTime() >= now,
      sync: resolveSyncState(r),
      docEditedAt: r.docEditedAt ? r.docEditedAt.toISOString() : null,
      // Measured from the ad's own stored design — the same comparison the ad list
      // makes in the browser, so the prompt and the badges can never disagree.
      behind: isBehindTemplate({ doc: parseDoc(r.doc ?? ''), templateDocHash: r.templateDocHash }, nextHash),
    }));
    // First following ad that is behind — the design the update would replace.
    const baselineId = ads.find((a) => a.sync === 'synced' && a.behind)?.id;
    const baselineRaw = baselineId ? rows.find((r) => r.id === baselineId)?.doc : null;
    baselineDoc = baselineRaw ? parseDoc(baselineRaw) : null;
  } catch (err) {
    // An unmigrated table must not block saving a template.
    console.warn('[api/ad-generator/templates-doc/[id]/sync-impact] falling back to []:', err);
    ads = [];
  }

  let total = ads.length;
  try {
    total = await prisma.adCreative.count({ where: { templateId: id, archivedAt: null } });
  } catch {
    total = ads.length;
  }

  // Cosmetic or structural, measured against what the ads have. Null when there
  // is no following ad to compare with — the counts still stand on their own.
  const change: DocChange | null = baselineDoc ? classifyDocChange(baselineDoc, nextDoc) : null;

  // The three groups the prompt offers, pre-computed so the client isn't
  // re-deriving the policy: only a synced ad whose design is behind can take an
  // update, and "active" is the default because re-rendering an ad whose offer
  // has ended rewrites history for no benefit.
  const syncable = ads.filter((a) => a.sync === 'synced' && a.behind);
  return NextResponse.json({
    templateId: id,
    docHash: nextHash,
    change,
    total,
    truncated: total > ads.length,
    counts: {
      active: syncable.filter((a) => a.offerActive).length,
      expired: syncable.filter((a) => !a.offerActive).length,
      customized: ads.filter((a) => a.sync === 'detached').length,
      upToDate: ads.filter((a) => a.sync === 'synced' && !a.behind).length,
      ready: syncable.filter((a) => a.status === 'ready').length,
    },
    activeIds: syncable.filter((a) => a.offerActive).map((a) => a.id),
    expiredIds: syncable.filter((a) => !a.offerActive).map((a) => a.id),
    ads,
  });
}
