import { prisma } from '@/lib/prisma';
import { createNotification } from '@/lib/notifications/service';

/**
 * Expiration sweep — retire ads whose underlying OEM offer has ended.
 *
 * This is the safety net the whole autonomous design leans on. Offers are
 * time-boxed and short: measured against the live feed, GM and Mazda programmes
 * ran only to month-end. An ad that keeps advertising a dead payment is exactly
 * the exposure that makes dealers nervous about automation, and it is the one
 * failure that gets worse the longer nobody looks.
 *
 * Two different actions, because the states mean different things:
 *
 *  • A `ready` ad whose offer has expired is DEMOTED to `draft`. It was approved
 *    for use and the thing it advertises no longer exists, so it must stop being
 *    usable. This is the safety-critical half.
 *
 *  • An expired `draft` is left alone structurally — nobody was going to run it —
 *    but the expiry is recorded so the review queue can show it as dead rather
 *    than leaving someone to work out why the numbers look wrong.
 *
 * Only ever touches `autoGenerated` ads. A hand-built ad's lifecycle belongs to
 * the person who built it, and `expiresAt` is null on those anyway.
 *
 * Server-only.
 */

const EXPIRY_NOTE = 'Offer expired — this ad advertises terms that are no longer available.';

export interface ExpireResult {
  /** Ads that were `ready` and got demoted — the ones that mattered. */
  demoted: { id: string; accountKey: string; name: string; expiredAt: string }[];
  /** Expired drafts newly annotated. */
  annotated: number;
  runId: string | null;
}

function parseNotes(raw: string | null): string[] {
  if (!raw) return [];
  try {
    const v = JSON.parse(raw);
    return Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];
  } catch {
    return [];
  }
}

/** Add the expiry note without discarding the generation-time warnings. */
function withExpiryNote(raw: string | null): string {
  const notes = parseNotes(raw);
  if (!notes.includes(EXPIRY_NOTE)) notes.unshift(EXPIRY_NOTE);
  return JSON.stringify(notes);
}

/**
 * Sweep expired auto-generated ads.
 *
 * `accountKey` narrows it for an on-demand run; omit for the scheduled sweep.
 */
export async function expireStaleAds(accountKey?: string, now = new Date()): Promise<ExpireResult> {
  const started = new Date();
  const result: ExpireResult = { demoted: [], annotated: 0, runId: null };

  let stale: {
    id: string;
    accountKey: string;
    name: string;
    status: string;
    expiresAt: Date | null;
    reviewNotes: string | null;
  }[] = [];
  try {
    stale = await prisma.adCreative.findMany({
      where: {
        autoGenerated: true,
        expiresAt: { not: null, lt: now },
        ...(accountKey ? { accountKey } : {}),
      },
      select: { id: true, accountKey: true, name: true, status: true, expiresAt: true, reviewNotes: true },
    });
  } catch (err) {
    console.warn('[expire-ads] lookup failed:', err);
    return result;
  }

  for (const ad of stale) {
    const alreadyNoted = parseNotes(ad.reviewNotes).includes(EXPIRY_NOTE);
    // Nothing to do: already a draft and already annotated on an earlier sweep.
    if (ad.status !== 'ready' && alreadyNoted) continue;

    try {
      await prisma.adCreative.update({
        where: { id: ad.id },
        data: {
          // Demotion is the point. An approved ad for a dead offer must stop
          // being approved.
          ...(ad.status === 'ready' ? { status: 'draft' } : {}),
          reviewNotes: withExpiryNote(ad.reviewNotes),
        },
      });
      if (ad.status === 'ready') {
        result.demoted.push({
          id: ad.id,
          accountKey: ad.accountKey,
          name: ad.name,
          expiredAt: ad.expiresAt!.toISOString(),
        });
      } else {
        result.annotated++;
      }
    } catch (err) {
      console.warn(`[expire-ads] could not update ${ad.id}:`, err);
    }
  }

  // Heartbeat, written even on a no-op sweep — same reasoning as the other jobs:
  // "nothing expired" and "the sweep stopped running" must not look identical.
  try {
    const run = await prisma.adAutomationRun.create({
      data: {
        accountKey: accountKey ?? null,
        kind: 'expire_sweep',
        startedAt: started,
        finishedAt: new Date(),
        scopesChecked: stale.length,
        issueCount: result.demoted.length,
        detail: JSON.stringify({ demoted: result.demoted, annotated: result.annotated }),
      },
    });
    result.runId = run.id;
  } catch (err) {
    console.warn('[expire-ads] could not record run:', err);
  }

  await notifyDemotions(result);
  return result;
}

/**
 * Tell people when an approved ad was pulled. Only for demotions — annotating a
 * draft nobody was running isn't worth an interruption.
 */
async function notifyDemotions(result: ExpireResult): Promise<void> {
  if (result.demoted.length === 0) return;

  const byAccount = new Map<string, ExpireResult['demoted']>();
  for (const d of result.demoted) {
    byAccount.set(d.accountKey, [...(byAccount.get(d.accountKey) ?? []), d]);
  }

  for (const [accountKey, ads] of byAccount) {
    let recipients: string[] = [];
    try {
      const account = await prisma.account.findUnique({
        where: { key: accountKey },
        select: { accountRepId: true },
      });
      if (account?.accountRepId) recipients = [account.accountRepId];
      else {
        const admins = await prisma.user.findMany({
          where: { role: { in: ['developer', 'super_admin', 'admin'] } },
          select: { id: true },
          take: 5,
        });
        recipients = admins.map((a) => a.id);
      }
    } catch {
      recipients = [];
    }

    for (const userId of recipients) {
      try {
        await createNotification({
          userId,
          type: 'incentive_ads_ready',
          // Warning, not info: something that was approved has been pulled.
          severity: 'warning',
          title: `${ads.length} approved offer ad(s) pulled — offer expired`,
          body: `${ads
            .slice(0, 3)
            .map((a) => a.name)
            .join('; ')}${ads.length > 3 ? ` and ${ads.length - 3} more` : ''}. Returned to draft.`,
          link: '/ad-generator',
          meta: { accountKey, demoted: ads.length },
          dedupeKey: `adgen-expire:${accountKey}:${new Date().toISOString().slice(0, 10)}`,
          dedupeWindowHours: 20,
        });
      } catch (err) {
        console.warn('[expire-ads] notification failed:', err);
      }
    }
  }
}
