// DB-backed tests for the offer-run orchestrator — the container, the cycle key,
// the lock, the rollover — with a FIXTURE generator standing in for
// `generateForAccount`, whose real path needs EVOX, Chromium, S3 and Anthropic
// and is covered by the staging pass.
//
// Self-skip unless RUN_DB_TESTS=1. Requires DATABASE_URL and the two ensure
// scripts applied (the 409 assertion is the partial unique index).
import 'dotenv/config';
import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { prisma } from '@/lib/prisma';
import type { GenerateConfigRow, GenerateResult, GeneratedAd } from './generate-ads';
import { OfferRunInProgressError, runOfferCampaign } from './offer-run';

const RUN = !!process.env.RUN_DB_TESTS;
const PREFIX = '__vitest_offerrun_';
const acct = `${PREFIX}a`;
// A fixed clock: 15 June 2031 → cycle 2031-06 under current_month.
const NOW = new Date(Date.UTC(2031, 5, 15, 12));

const config = {
  accountKey: acct,
  enabled: false,
  emailEnabled: false,
  emailTemplateId: null,
  emailAudienceId: null,
  emailMaxOffers: 6,
  makes: '[]',
  focusModels: '[]',
  excludeModels: '[]',
  zip: null,
  radius: 75,
  offerTypePriority: '["lease","apr","cash"]',
  expandOfferTypes: true,
  runWindowMode: 'current_month',
  rollingDays: 30,
  sizeIds: null,
  maxAdsPerRun: 10,
  maxVehiclesPerRun: 25,
  minStock: 0,
  templateMap: null,
  fanOutTemplateIds: null,
  mode: 'draft',
  notifyUserIds: null,
} as GenerateConfigRow;

/** Creates N real AdCreative rows and reports them the way generateForAccount would. */
function fixtureGenerator(count: number, tag: string) {
  return async (): Promise<GenerateResult> => {
    const generated: GeneratedAd[] = [];
    for (let i = 0; i < count; i += 1) {
      const row = await prisma.adCreative.create({
        data: {
          accountKey: acct,
          name: `${tag} ${i}`,
          templateId: 't1',
          data: '{}',
          autoGenerated: true,
          offerFingerprint: `${tag}-fp-${i}`,
          offerGroupKey: `${tag}-g-${i}`,
        },
        select: { id: true },
      });
      generated.push({
        creativeId: row.id,
        vehicle: '2031 Test Vehicle',
        offerFingerprint: `${tag}-fp-${i}`,
        offerGroupKey: `${tag}-g-${i}`,
        offerPrints: [],
        offerSummary: '',
        templateId: 't1',
        templateName: 'T',
        templateReason: '',
        recommended: true,
        status: 'draft',
        imageSource: '',
        eventName: null,
        vin: null,
        sizes: 1,
        expiresAt: null,
        coopVersion: null,
        warnings: [],
        updated: false,
      });
    }
    return { accountKey: acct, runId: null, generated, skipped: [], scopesChecked: count, offersSeen: count };
  };
}

async function wipe() {
  await prisma.adCreative.deleteMany({ where: { accountKey: acct } });
  await prisma.campaign.deleteMany({ where: { accountKey: acct } });
  await prisma.adAutomationRun.deleteMany({ where: { accountKey: acct } });
}

describe.skipIf(!RUN)('runOfferCampaign — DB integration', () => {
  beforeAll(async () => {
    await wipe();
    await prisma.account.deleteMany({ where: { key: acct } });
    await prisma.account.create({ data: { key: acct, dealer: 'Vitest Offer Run' } });
  });
  beforeEach(wipe);
  afterAll(async () => {
    await wipe();
    await prisma.account.deleteMany({ where: { key: acct } });
  });

  it('creates the cycle container, attaches the ads, and releases it as draft', async () => {
    const r = await runOfferCampaign(config, {
      trigger: { kind: 'manual', userId: 'u1', userName: 'Connor' },
      now: NOW,
      generate: fixtureGenerator(3, 'a'),
    });
    expect(r.cycleKey).toBe(`adgen:${acct}:2031-06`);
    expect(r.campaignId).toBeTruthy();

    const c = await prisma.campaign.findUnique({ where: { id: r.campaignId! } });
    expect(c?.automationKey).toBe(r.cycleKey);
    expect(c?.name).toBe('June 2031 offers — Vitest Offer Run');
    expect(c?.source).toBe('automation');
    expect(c?.status).toBe('draft'); // released after the run, not left `building`
    expect(c?.createdByUserId).toBe('u1');

    const ads = await prisma.adCreative.findMany({ where: { accountKey: acct } });
    expect(ads).toHaveLength(3);
    for (const ad of ads) {
      expect(ad.campaignId).toBe(r.campaignId);
      expect(ad.runId).toBe(r.runId);
    }

    const run = await prisma.adAutomationRun.findUnique({ where: { id: r.runId } });
    expect(run?.finishedAt).not.toBeNull();
    expect(JSON.parse(run!.detail!).trigger).toEqual({ kind: 'manual', userId: 'u1', userName: 'Connor' });
    // Email off → the campaign exists anyway. This is the common shape.
    expect(JSON.parse(run!.detail!).email).toEqual({ reason: 'email_disabled' });
  });

  it('lands a second run for the same cycle in the SAME campaign', async () => {
    const first = await runOfferCampaign(config, { trigger: { kind: 'scheduled' }, now: NOW, generate: fixtureGenerator(2, 'b') });
    const second = await runOfferCampaign(config, {
      trigger: { kind: 'manual' },
      now: new Date(NOW.getTime() + 86_400_000), // the next day, same month
      generate: fixtureGenerator(1, 'c'),
    });
    expect(second.campaignId).toBe(first.campaignId);
    expect(await prisma.campaign.count({ where: { accountKey: acct } })).toBe(1);
    // Every ad from both runs is on it.
    expect(await prisma.adCreative.count({ where: { campaignId: first.campaignId! } })).toBe(3);
  });

  it('refuses a second run while one is open — the lock is the index, not the schedule', async () => {
    // A generator that holds the run open long enough for the second call to collide.
    const slow = async (): Promise<GenerateResult> => {
      await new Promise((res) => setTimeout(res, 300));
      return fixtureGenerator(1, 'd')();
    };
    const results = await Promise.allSettled([
      runOfferCampaign(config, { trigger: { kind: 'manual' }, now: NOW, generate: slow }),
      runOfferCampaign(config, { trigger: { kind: 'manual' }, now: NOW, generate: slow }),
    ]);
    const rejected = results.filter((x) => x.status === 'rejected') as PromiseRejectedResult[];
    expect(rejected).toHaveLength(1);
    expect(rejected[0].reason).toBeInstanceOf(OfferRunInProgressError);
    expect(await prisma.campaign.count({ where: { accountKey: acct } })).toBe(1);
  });

  it('archives the previous cycle on its way in, even when this run builds nothing', async () => {
    const old = await prisma.campaign.create({
      data: { name: 'May 2031 offers — Vitest Offer Run', accountKey: acct, source: 'automation', automationKey: `adgen:${acct}:2031-05` },
      select: { id: true },
    });
    const r = await runOfferCampaign(config, { trigger: { kind: 'scheduled' }, now: NOW, generate: fixtureGenerator(0, 'e') });
    expect(r.archivedCampaignIds).toEqual([old.id]);
    expect((await prisma.campaign.findUnique({ where: { id: old.id } }))?.archivedAt).not.toBeNull();
    // Nothing was built, so no June container was created for nothing.
    expect(r.campaignId).toBeNull();
    expect(await prisma.campaign.count({ where: { accountKey: acct, archivedAt: null } })).toBe(0);
  });

  it('does not archive a container for a month that has not ended', async () => {
    // next_month: a container built in May for June must survive 1 June.
    await prisma.campaign.create({
      data: { name: 'June 2031 offers — Vitest Offer Run', accountKey: acct, source: 'automation', automationKey: `adgen:${acct}:2031-06` },
    });
    const r = await runOfferCampaign(config, {
      trigger: { kind: 'scheduled' },
      now: new Date(Date.UTC(2031, 5, 1)),
      generate: fixtureGenerator(0, 'f'),
    });
    expect(r.archivedCampaignIds).toEqual([]);
  });

  it('closes a run the process died under, then proceeds', async () => {
    await prisma.adAutomationRun.create({
      data: { accountKey: acct, kind: 'generate', startedAt: new Date(NOW.getTime() - 20 * 60_000), finishedAt: null },
    });
    const r = await runOfferCampaign(config, { trigger: { kind: 'manual' }, now: NOW, generate: fixtureGenerator(1, 'g') });
    expect(r.campaignId).toBeTruthy();
    const abandoned = await prisma.adAutomationRun.findMany({ where: { accountKey: acct, error: 'abandoned' } });
    expect(abandoned).toHaveLength(1);
  });
});
