import { prisma } from '@/lib/prisma';
import type { MarketCheckIncentive } from '@/lib/integrations/marketcheck';
import type { EmailTemplate } from '@/lib/email/types';
import { isV2Template } from '@/lib/email/types';
import { renderEmailTemplate } from '@/lib/email/render';
import type { AdData } from '../types';
import { offerHeadline, rankOffers } from './generate-offer-email';
import {
  buildOfferEmail,
  offerBlocks,
  spliceOffers,
  resetBlockIds,
  type OfferEmailInput,
  type OfferEmailVehicle,
} from './offer-email-doc';

/**
 * Render what the companion offer email would look like, without writing one.
 *
 * WHY THIS ISN'T JUST `generateOfferEmail` IN DRY-RUN. That function's job is to
 * create or update a draft: it needs a completed run's `GeneratedAd[]`, it
 * writes a Campaign and an EmailBlast, and it refuses outright on the states a
 * preview most needs to SHOW (no offers yet, shell missing its marker). A
 * preview has to render something useful in exactly those cases, so it shares
 * the document builders and nothing else.
 *
 * It previews the settings ON SCREEN, not the saved ones, so the shell and the
 * offer cap can be judged before anyone commits them.
 *
 * Server-only. Reads exclusively — this module never writes.
 */

/** One selectable shell, rendered. */
export interface OfferEmailOption {
  /** `Template.slug`, or '' for the brand-kit layout. */
  slug: string;
  title: string;
  html: string;
  /**
   * False when this shell carries no `{{offers}}` block. Surfaced rather than
   * filtered: "why isn't my template here" is a real question, and the answer —
   * add the block — is one the reader can act on.
   */
  usable: boolean;
}

export interface OfferEmailPreview {
  subject: string;
  /** How many offers the preview features. */
  offers: number;
  /**
   * True when no real offers were available and the layout is drawn with
   * representative stand-ins. The UI must say so — a preview silently made of
   * invented numbers is worse than no preview.
   */
  sample: boolean;
  /** Why the preview is degraded, in the reader's terms. */
  notes: string[];
  /** Every shell choice, each rendered with THIS account's real offers. */
  options: OfferEmailOption[];
}

function safeJson<T>(raw: string | null | undefined): T | null {
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

function jsonArray(raw: string | null): string[] {
  const v = safeJson<unknown>(raw);
  return Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];
}

/**
 * Stand-ins used only when the account has no generated ads yet.
 *
 * Deliberately obvious placeholders rather than plausible fake numbers —
 * "$XXX/mo" cannot be mistaken for a real programme if someone screenshots the
 * preview, which invented-but-realistic figures absolutely can.
 */
const SAMPLE: OfferEmailVehicle[] = [
  {
    name: '2026 Example Model',
    imageUrl: null,
    offerType: 'lease',
    headline: '$XXX/mo · 36 mo',
    subhead: '$X,XXX due at signing',
    programName: 'Sample programme',
    description: 'Manufacturer wording appears here, reproduced exactly as published.',
    offerDetails: null,
    eligibility: null,
    disclaimer:
      'Sample disclaimer. The real email reproduces the offer’s resolved disclaimer verbatim.',
    expiration: null,
  },
  {
    name: '2026 Example Model 2',
    imageUrl: null,
    offerType: 'apr',
    headline: 'X.X% APR · 60 mo',
    subhead: '',
    programName: 'Sample programme',
    description: null,
    offerDetails: null,
    eligibility: null,
    disclaimer:
      'Sample disclaimer. The real email reproduces the offer’s resolved disclaimer verbatim.',
    expiration: null,
  },
];

export async function previewOfferEmail(
  accountKey: string,
  opts: { emailMaxOffers?: number },
): Promise<OfferEmailPreview | null> {
  const notes: string[] = [];
  const maxOffers = Math.min(Math.max(Math.floor(opts.emailMaxOffers ?? 6), 1), 20);

  const account = await prisma.account.findUnique({
    where: { key: accountKey },
    select: { key: true, dealer: true, branding: true, logos: true, website: true },
  });
  if (!account) return null;

  const config = await prisma.adAutomationConfig.findUnique({
    where: { accountKey },
    select: { offerTypePriority: true },
  });

  // ── the offers this email would actually feature ──
  //
  // The already-generated ads, because that is the rule the generator follows:
  // the email advertises exactly what the paid side is running, never more.
  const creatives = await prisma.adCreative.findMany({
    where: { accountKey, autoGenerated: true, archivedAt: null },
    orderBy: { updatedAt: 'desc' },
    take: 40,
    select: { data: true, offerFingerprint: true },
  });

  const fingerprints = creatives.map((c) => c.offerFingerprint).filter((f): f is string => !!f);
  const snapshots = fingerprints.length
    ? await prisma.oemOfferSnapshot.findMany({
        where: { accountKey, fingerprint: { in: fingerprints } },
        select: { fingerprint: true, payload: true },
      })
    : [];
  const incentiveByFingerprint = new Map<string, MarketCheckIncentive>();
  for (const s of snapshots) {
    const inc = safeJson<MarketCheckIncentive>(s.payload);
    if (inc && !incentiveByFingerprint.has(s.fingerprint)) {
      incentiveByFingerprint.set(s.fingerprint, inc);
    }
  }

  // One row per vehicle: the drafts list holds a creative per SIZE, so without
  // this the preview would repeat the same truck three times.
  const seen = new Set<string>();
  const real: OfferEmailVehicle[] = [];
  for (const c of creatives) {
    const data = safeJson<AdData>(c.data) ?? {};
    const name = (data.vehicleName ?? '').trim();
    // The generator drops offers with no resolved disclaimer, so the preview
    // has to as well, or it shows a row that would never be sent.
    if (!name || !((data.disclaimer ?? '').trim()) || seen.has(name)) continue;
    seen.add(name);
    const inc = c.offerFingerprint ? incentiveByFingerprint.get(c.offerFingerprint) ?? null : null;
    const { headline, subhead } = offerHeadline(data);
    real.push({
      name,
      imageUrl: (data.vehicleImageUrl ?? '').trim() || null,
      offerType: (data.offerType ?? '').trim(),
      headline,
      subhead,
      programName: inc?.programName?.trim() || null,
      description: inc?.description?.trim() || null,
      offerDetails: inc?.offerDetails?.trim() || null,
      eligibility: inc?.eligibility?.trim() || null,
      disclaimer: (data.disclaimer ?? '').trim(),
      expiration: (data.expiration ?? '').trim() || null,
    });
  }

  const sample = real.length === 0;
  if (sample) {
    notes.push(
      'No generated ads yet, so this shows the layout with placeholder offers rather than real ones.',
    );
  }

  const ranked = rankOffers(
    sample ? SAMPLE : real,
    jsonArray(config?.offerTypePriority ?? null),
    maxOffers,
  );
  if (!sample && real.length > ranked.length) {
    notes.push(`${real.length} offers available — the email features the top ${ranked.length}.`);
  }

  const branding = safeJson<{ colors?: Record<string, string> }>(account.branding ?? null);
  const logos = safeJson<Record<string, string>>(account.logos ?? null);
  const input: OfferEmailInput = {
    dealerName: account.dealer,
    accentColor: branding?.colors?.primary || '#1a1a1a',
    logoUrl: logos?.light || logos?.dark || null,
    ctaUrl: account.website?.trim() || null,
    ctaLabel: 'View inventory',
    vehicles: ranked,
  };

  const subject = `${account.dealer} — current offers`;
  const preheader = ranked.map((v) => `${v.name}: ${v.headline}`).join(' · ').slice(0, 150);

  /** Render one choice. Ids reset per document so identical settings render
   *  identical markup and the iframes aren't rewritten on every keystroke. */
  const render = async (doc: EmailTemplate): Promise<string> => {
    resetBlockIds();
    doc.subject = subject;
    doc.preheader = preheader;
    return renderEmailTemplate(doc);
  };

  // The brand-kit layout leads: it is the default, it always works, and it needs
  // no template to exist first.
  const options: OfferEmailOption[] = [
    {
      slug: '',
      title: 'Brand kit',
      html: await render(buildOfferEmail(input)),
      usable: true,
    },
  ];

  const shellRows = await prisma.template.findMany({
    where: { accountKey, type: 'design' },
    select: { slug: true, title: true, content: true },
    orderBy: { updatedAt: 'desc' },
    take: 24,
  });

  for (const row of shellRows) {
    if (!isV2Template(row.content)) continue;
    const shell = safeJson<EmailTemplate>(row.content);
    if (!shell) continue;
    const spliced = spliceOffers(shell, offerBlocks(input));
    options.push({
      slug: row.slug,
      title: row.title,
      // A shell with no marker still renders — as ITSELF, with no offers in it,
      // which is precisely what makes the problem obvious at a glance.
      html: await render(spliced ?? shell),
      usable: spliced !== null,
    });
  }

  return { subject, offers: ranked.length, sample, notes, options };
}
