/**
 * Template usage — /api/ad-generator/templates-doc/usage
 *
 * How often each ad template actually gets used, split by WHO used it: a person
 * in the generator, or the nightly automation. That split is the whole point —
 * a template the machine leans on hard and a template designers reach for are
 * different assets, and a library that can't tell them apart can't be pruned.
 *
 * No new tracking was needed: every ad already records `templateId`,
 * `autoGenerated`, `status` and `archivedAt`, and AdCreative carries an index on
 * `templateId` for exactly this lookup. So this is a groupBy, not a pipeline.
 *
 * `archived` is reported rather than hidden. An ad that was made and thrown away
 * is the honest signal that a template looks right in the picker and doesn't
 * survive contact with a real offer — counting it as "used" would flatter the
 * template, and dropping it entirely would lose the warning.
 *
 * Scope: with `accountKey`, that account's ads only (scope-checked). Without it,
 * every account the caller can see — the Admin view of the shared library.
 * Resilient: an unmigrated table returns empty rather than breaking the library.
 */
import { NextRequest, NextResponse } from 'next/server';
import { getAuthSession, getAccountScope, canAccessAccount, forbidden } from '@/lib/api-auth';
import { adGeneratorAllowed } from '@/lib/ad-generator/access';
import { prisma } from '@/lib/prisma';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** One template's counts. All are ad counts, never distinct-offer counts. */
export interface TemplateUsage {
  templateId: string;
  /** Live (non-archived) ads built from this template. */
  total: number;
  /** Of `total`, how many the automation produced. */
  auto: number;
  /** Of `total`, how many a person built. `total - auto`. */
  manual: number;
  /** Of `total`, how many reached `ready` (approved, launchable). */
  ready: number;
  /** Ads made from this template and then archived — made-but-discarded. */
  archived: number;
  /** Newest ad's creation time, ISO. Null when never used. */
  lastUsedAt: string | null;
}

export async function GET(req: NextRequest) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const scope = getAccountScope(session);
  const accountKey = (req.nextUrl.searchParams.get('accountKey') || '').trim();
  if (accountKey && !canAccessAccount(scope, accountKey)) return forbidden();

  // Admin (no account) reads the whole library; otherwise one account. A scoped
  // caller with no accountKey is narrowed to the keys they can actually see
  // (`scope === null` means unrestricted), so usage never leaks counts from
  // accounts outside their scope.
  const where = accountKey ? { accountKey } : scope === null ? {} : { accountKey: { in: scope } };

  try {
    const [live, archived] = await Promise.all([
      prisma.adCreative.groupBy({
        by: ['templateId', 'autoGenerated', 'status'],
        where: { ...where, archivedAt: null },
        _count: { _all: true },
        _max: { createdAt: true },
      }),
      prisma.adCreative.groupBy({
        by: ['templateId'],
        where: { ...where, archivedAt: { not: null } },
        _count: { _all: true },
      }),
    ]);

    const byId = new Map<string, TemplateUsage>();
    const get = (templateId: string): TemplateUsage => {
      let u = byId.get(templateId);
      if (!u) {
        u = { templateId, total: 0, auto: 0, manual: 0, ready: 0, archived: 0, lastUsedAt: null };
        byId.set(templateId, u);
      }
      return u;
    };

    for (const row of live) {
      const u = get(row.templateId);
      const n = row._count._all;
      u.total += n;
      if (row.autoGenerated) u.auto += n;
      else u.manual += n;
      if (row.status === 'ready') u.ready += n;
      const at = row._max.createdAt;
      if (at && (!u.lastUsedAt || at.toISOString() > u.lastUsedAt)) u.lastUsedAt = at.toISOString();
    }
    for (const row of archived) get(row.templateId).archived += row._count._all;

    return NextResponse.json({ usage: [...byId.values()] });
  } catch (err) {
    // An unmigrated / unreachable table must not take the template library down;
    // the cards simply show no usage.
    console.warn('[api/ad-generator/templates-doc/usage] falling back to []:', err);
    return NextResponse.json({ usage: [] });
  }
}
