/**
 * Ad creatives — /api/ad-generator/creatives
 *
 * A saved ad = a template id + the filled-in field values, scoped to an
 * account. GET lists the account's ads (newest first); POST creates one.
 * Flag- + auth-gated; resilient (unmigrated table → empty list).
 */
import { NextRequest, NextResponse } from 'next/server';
import { getAuthSession, getAccountScope, canAccessAccount, forbidden } from '@/lib/api-auth';
import { requirePermission } from '@/lib/permissions/require';
import { adGeneratorAllowed } from '@/lib/ad-generator/access';
import { prisma } from '@/lib/prisma';
import { designHash, resolveSyncState } from '@/lib/ad-generator/template-sync';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Row = {
  id: string;
  name: string;
  templateId: string;
  doc: string | null;
  data: string;
  status: string;
  thumbnailUrl: string | null;
  updatedAt: Date;
  createdByName: string | null;
  autoGenerated: boolean;
  expiresAt: Date | null;
  reviewNotes: string | null;
  archivedAt: Date | null;
  offerGroupKey: string | null;
  recommended: boolean;
  selectedAt: Date | null;
  campaignId: string | null;
  offerEditedAt: Date | null;
  templateSync: string | null;
  templateDocHash: string | null;
  docEditedAt: Date | null;
};

function shape(r: Row, running = false) {
  let data: Record<string, string> = {};
  try {
    data = JSON.parse(r.data) ?? {};
  } catch {
    data = {};
  }
  let doc: unknown = null;
  if (r.doc) {
    try {
      doc = JSON.parse(r.doc);
    } catch {
      doc = null;
    }
  }
  return {
    id: r.id,
    name: r.name,
    templateId: r.templateId,
    status: r.status,
    thumbnailUrl: r.thumbnailUrl,
    updatedAt: r.updatedAt,
    createdByName: r.createdByName,
    // Provenance. Without this the list can't tell an ad a person built from one
    // the nightly job produced, which is the first thing anyone asks of a shared
    // library that two things write to.
    autoGenerated: r.autoGenerated,
    /** When the underlying offer stops being valid. Auto-generated ads only. */
    expiresAt: r.expiresAt,
    /** Set while the ad is archived; null for a live one. */
    archivedAt: r.archivedAt,
    /** Why the generator held it back, when it did. */
    reviewNotes: r.reviewNotes,
    // ── offer fan-out ──
    // Shared by every design built from the same vehicle + offer, which is what
    // lets the list fold them into one row the dealer chooses within. Null on
    // hand-built ads and on anything generated before the fan-out; those group
    // alone and render exactly as they always did.
    offerGroupKey: r.offerGroupKey,
    /** The design the generator ranked first within its group. */
    recommended: r.recommended,
    /** When a person chose this design. Independent of `status`. */
    selectedAt: r.selectedAt,
    /**
     * The run this ad came from. `generateOfferEmail` creates one `Campaign` per
     * run and stamps it onto every ad AND the offer email, so this is what lets
     * the list show a run's output together instead of as unrelated cards.
     */
    campaignId: r.campaignId,
    /**
     * A person changed the offer values after generation, so the numbers are no
     * longer the manufacturer's. The data-side twin of `docEditedAt`.
     */
    offerEditedAt: r.offerEditedAt,
    /**
     * In a launch that actually published. The one piece of an ad's state that
     * lives outside `AdCreative` — `AdLaunch.creativeIds` is a JSON array rather
     * than a relation, so it can't be joined and is resolved per request.
     */
    running,
    // Template link. `templateSync` is resolved (never null) so the client never
    // has to repeat the auto-vs-hand-built default; the hash lets the list say
    // "this ad is behind its template" by comparing against the template docs it
    // already loaded, with no extra request.
    templateSync: resolveSyncState(r),
    templateDocHash: r.templateDocHash,
    docEditedAt: r.docEditedAt,
    doc,
    data,
  };
}

export async function GET(req: NextRequest) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const accountKey = (req.nextUrl.searchParams.get('accountKey') || '').trim();
  if (!accountKey) return NextResponse.json({ creatives: [] });
  // A caller may only list ads for an account within their scope. Clients (and
  // scoped admins) can't read another account's creatives by swapping the key.
  if (!canAccessAccount(getAccountScope(session), accountKey)) return forbidden();
  try {
    // Archived ads are hidden unless asked for, the same way every other Loomi
    // list treats them — `?archived=1` is what the Archived status filter sends.
    const archived = req.nextUrl.searchParams.get('archived') === '1';
    // One variant group, archived siblings INCLUDED. Once a design is picked its
    // siblings are archived and vanish from the normal list, which would leave
    // the choice unreviewable and un-undoable — the compare view asks for the
    // group by key so it can still show what was passed over.
    const group = (req.nextUrl.searchParams.get('group') || '').trim();
    const rows = (await prisma.adCreative.findMany({
      where: group
        ? { accountKey, offerGroupKey: group }
        : { accountKey, archivedAt: archived ? { not: null } : null },
      orderBy: { updatedAt: 'desc' },
    })) as Row[];
    // Which of these are live. One query for the account's published launches,
    // then a set — `creativeIds` is a JSON string[], so there is nothing to join
    // against and doing this per row would be N queries for one boolean.
    const live = new Set<string>();
    try {
      const launches = await prisma.adLaunch.findMany({
        where: { accountKey, status: 'published' },
        select: { creativeIds: true },
      });
      for (const l of launches) {
        try {
          const ids = JSON.parse(l.creativeIds);
          if (Array.isArray(ids)) for (const id of ids) if (typeof id === 'string') live.add(id);
        } catch {
          // A malformed row means we can't say this ad is live. Treating it as
          // not-live understates, which is the safe direction: the worst case is
          // an ad shown as needing attention when it doesn't.
        }
      }
    } catch (err) {
      console.warn('[api/ad-generator/creatives] launch lookup failed:', err);
    }

    return NextResponse.json({ creatives: rows.map((r) => shape(r, live.has(r.id))) });
  } catch (err) {
    console.warn('[api/ad-generator/creatives] falling back to []:', err);
    return NextResponse.json({ creatives: [] });
  }
}

export async function POST(req: NextRequest) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  let body: { accountKey?: string; name?: string; templateId?: string; data?: Record<string, string>; status?: string; doc?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  // Originating an ad is staff work. A client holds `studio.adgen.edit` so they
  // can adjust the offer on an ad the run built for them, but an ad created from
  // scratch has no manufacturer program behind it and no co-op provenance —
  // which is the opposite of handing dealers pre-built OEM offers.
  const { error: createDenied } = await requirePermission('studio.adgen.create');
  if (createDenied) return createDenied;

  const accountKey = (body.accountKey ?? '').trim();
  const name = (body.name ?? '').trim() || 'Untitled ad';
  const templateId = (body.templateId ?? '').trim();
  if (!accountKey || !templateId) {
    return NextResponse.json({ error: 'accountKey and templateId are required' }, { status: 400 });
  }
  // Can't create an ad under an account outside the caller's scope.
  if (!canAccessAccount(getAccountScope(session), accountKey)) return forbidden();
  const u = session.user as { id?: string; name?: string | null };

  // The ad's own design copy: an explicit doc (e.g. "from scratch" sends a blank
  // one), else a snapshot of the source DB template so later master edits don't
  // change this ad. Code templates are stable, so they stay referenced (null).
  let docSnapshot: string | null = null;
  if (body.doc && typeof body.doc === 'object' && Array.isArray((body.doc as { sizes?: unknown }).sizes)) {
    docSnapshot = JSON.stringify(body.doc);
  } else {
    try {
      const tpl = await prisma.adTemplateDoc.findUnique({ where: { id: templateId }, select: { doc: true } });
      if (tpl?.doc) docSnapshot = tpl.doc;
    } catch {
      docSnapshot = null;
    }
  }
  // Which template revision this copy came from. The ad is DETACHED (copy-on-use
  // is unchanged for hand-built ads), but recording the revision still matters:
  // it's what lets an untouched copy be told a fix landed upstream and offered
  // the update, instead of quietly sitting on a stale design forever.
  let docHash: string | null = null;
  if (docSnapshot) {
    try {
      docHash = designHash(JSON.parse(docSnapshot) as TemplateDoc);
    } catch {
      docHash = null;
    }
  }

  try {
    const row = await prisma.adCreative.create({
      data: {
        accountKey,
        name,
        templateId,
        doc: docSnapshot,
        data: JSON.stringify(body.data ?? {}),
        status: body.status === 'ready' ? 'ready' : 'draft',
        createdById: u.id ?? null,
        createdByName: u.name ?? null,
        templateSync: 'detached',
        templateDocHash: docHash,
      },
    });
    return NextResponse.json({ creative: { id: row.id, name: row.name } });
  } catch (err) {
    console.error('[api/ad-generator/creatives] create failed:', err);
    return NextResponse.json({ error: 'Could not create — has the table been migrated in this environment?' }, { status: 500 });
  }
}
