/**
 * Ad creatives — /api/ad-generator/creatives
 *
 * A saved ad = a template id + the filled-in field values, scoped to an
 * account. GET lists the account's ads (newest first); POST creates one.
 * Flag- + auth-gated; resilient (unmigrated table → empty list).
 */
import { NextRequest, NextResponse } from 'next/server';
import { getAuthSession, getAccountScope, canAccessAccount, forbidden } from '@/lib/api-auth';
import { adGeneratorAllowed } from '@/lib/ad-generator/access';
import { prisma } from '@/lib/prisma';
import { designHash, resolveSyncState } from '@/lib/ad-generator/template-sync';
import type { TemplateDoc } from '@/lib/ad-generator/doc-types';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Row = {
  id: string;
  name: string;
  templateId: string;
  doc: string | null;
  data: string;
  status: string;
  thumbnailUrl: string | null;
  updatedAt: Date;
  createdByName: string | null;
  autoGenerated: boolean;
  expiresAt: Date | null;
  reviewNotes: string | null;
  archivedAt: Date | null;
  templateSync: string | null;
  templateDocHash: string | null;
  docEditedAt: Date | null;
};

function shape(r: Row) {
  let data: Record<string, string> = {};
  try {
    data = JSON.parse(r.data) ?? {};
  } catch {
    data = {};
  }
  let doc: unknown = null;
  if (r.doc) {
    try {
      doc = JSON.parse(r.doc);
    } catch {
      doc = null;
    }
  }
  return {
    id: r.id,
    name: r.name,
    templateId: r.templateId,
    status: r.status,
    thumbnailUrl: r.thumbnailUrl,
    updatedAt: r.updatedAt,
    createdByName: r.createdByName,
    // Provenance. Without this the list can't tell an ad a person built from one
    // the nightly job produced, which is the first thing anyone asks of a shared
    // library that two things write to.
    autoGenerated: r.autoGenerated,
    /** When the underlying offer stops being valid. Auto-generated ads only. */
    expiresAt: r.expiresAt,
    /** Set while the ad is archived; null for a live one. */
    archivedAt: r.archivedAt,
    /** Why the generator held it back, when it did. */
    reviewNotes: r.reviewNotes,
    // Template link. `templateSync` is resolved (never null) so the client never
    // has to repeat the auto-vs-hand-built default; the hash lets the list say
    // "this ad is behind its template" by comparing against the template docs it
    // already loaded, with no extra request.
    templateSync: resolveSyncState(r),
    templateDocHash: r.templateDocHash,
    docEditedAt: r.docEditedAt,
    doc,
    data,
  };
}

export async function GET(req: NextRequest) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const accountKey = (req.nextUrl.searchParams.get('accountKey') || '').trim();
  if (!accountKey) return NextResponse.json({ creatives: [] });
  // A caller may only list ads for an account within their scope. Clients (and
  // scoped admins) can't read another account's creatives by swapping the key.
  if (!canAccessAccount(getAccountScope(session), accountKey)) return forbidden();
  try {
    // Archived ads are hidden unless asked for, the same way every other Loomi
    // list treats them — `?archived=1` is what the Archived status filter sends.
    const archived = req.nextUrl.searchParams.get('archived') === '1';
    const rows = (await prisma.adCreative.findMany({
      where: { accountKey, archivedAt: archived ? { not: null } : null },
      orderBy: { updatedAt: 'desc' },
    })) as Row[];
    return NextResponse.json({ creatives: rows.map(shape) });
  } catch (err) {
    console.warn('[api/ad-generator/creatives] falling back to []:', err);
    return NextResponse.json({ creatives: [] });
  }
}

export async function POST(req: NextRequest) {
  if (!(await adGeneratorAllowed())) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const session = await getAuthSession();
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  let body: { accountKey?: string; name?: string; templateId?: string; data?: Record<string, string>; status?: string; doc?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  const accountKey = (body.accountKey ?? '').trim();
  const name = (body.name ?? '').trim() || 'Untitled ad';
  const templateId = (body.templateId ?? '').trim();
  if (!accountKey || !templateId) {
    return NextResponse.json({ error: 'accountKey and templateId are required' }, { status: 400 });
  }
  // Can't create an ad under an account outside the caller's scope.
  if (!canAccessAccount(getAccountScope(session), accountKey)) return forbidden();
  const u = session.user as { id?: string; name?: string | null };

  // The ad's own design copy: an explicit doc (e.g. "from scratch" sends a blank
  // one), else a snapshot of the source DB template so later master edits don't
  // change this ad. Code templates are stable, so they stay referenced (null).
  let docSnapshot: string | null = null;
  if (body.doc && typeof body.doc === 'object' && Array.isArray((body.doc as { sizes?: unknown }).sizes)) {
    docSnapshot = JSON.stringify(body.doc);
  } else {
    try {
      const tpl = await prisma.adTemplateDoc.findUnique({ where: { id: templateId }, select: { doc: true } });
      if (tpl?.doc) docSnapshot = tpl.doc;
    } catch {
      docSnapshot = null;
    }
  }
  // Which template revision this copy came from. The ad is DETACHED (copy-on-use
  // is unchanged for hand-built ads), but recording the revision still matters:
  // it's what lets an untouched copy be told a fix landed upstream and offered
  // the update, instead of quietly sitting on a stale design forever.
  let docHash: string | null = null;
  if (docSnapshot) {
    try {
      docHash = designHash(JSON.parse(docSnapshot) as TemplateDoc);
    } catch {
      docHash = null;
    }
  }

  try {
    const row = await prisma.adCreative.create({
      data: {
        accountKey,
        name,
        templateId,
        doc: docSnapshot,
        data: JSON.stringify(body.data ?? {}),
        status: body.status === 'ready' ? 'ready' : 'draft',
        createdById: u.id ?? null,
        createdByName: u.name ?? null,
        templateSync: 'detached',
        templateDocHash: docHash,
      },
    });
    return NextResponse.json({ creative: { id: row.id, name: row.name } });
  } catch (err) {
    console.error('[api/ad-generator/creatives] create failed:', err);
    return NextResponse.json({ error: 'Could not create — has the table been migrated in this environment?' }, { status: 500 });
  }
}
