import { describe, expect, it } from 'vitest';
import {
  countByStage,
  isWaitingOnSomeone,
  stageOf,
  tallyStages,
  type StageableAd,
} from './ad-lifecycle';
import { groupVariants } from './variant-groups';

function ad(over: Partial<StageableAd> & { id: string }): StageableAd {
  return {
    name: 'CR-V — $329/mo',
    templateId: 't1',
    status: 'draft',
    updatedAt: '2026-09-01T00:00:00.000Z',
    autoGenerated: true,
    offerGroupKey: 'g1',
    recommended: false,
    selectedAt: null,
    running: false,
    ...over,
  };
}

const one = (a: StageableAd) => groupVariants([a])[0];

describe('stageOf', () => {
  it('is needs_approval for a lone generated draft', () => {
    expect(stageOf(one(ad({ id: 'a', offerGroupKey: null })))).toBe('needs_approval');
  });

  it('is needs_pick when several designs exist and none is chosen', () => {
    const g = groupVariants([ad({ id: 'a' }), ad({ id: 'b' })])[0];
    expect(stageOf(g)).toBe('needs_pick');
  });

  it('puts needs_pick ahead of needs_approval', () => {
    // Picking is the first action; approving a design that may be discarded is
    // wasted effort.
    const g = groupVariants([ad({ id: 'a', status: 'draft' }), ad({ id: 'b', status: 'draft' })])[0];
    expect(stageOf(g)).toBe('needs_pick');
  });

  it('drops to needs_approval once a draft is chosen', () => {
    const g = groupVariants([
      ad({ id: 'a', selectedAt: '2026-09-02T00:00:00.000Z' }),
      ad({ id: 'b' }),
    ])[0];
    expect(stageOf(g)).toBe('needs_approval');
  });

  it('is approved when the chosen design is ready', () => {
    const g = groupVariants([
      ad({ id: 'a', selectedAt: '2026-09-02T00:00:00.000Z', status: 'ready' }),
      ad({ id: 'b' }),
    ])[0];
    expect(stageOf(g)).toBe('approved');
  });

  it('is running when the chosen design is live, even if still a draft', () => {
    // Live is a fact about the world; it outranks anything we think locally.
    const g = groupVariants([
      ad({ id: 'a', selectedAt: '2026-09-02T00:00:00.000Z', status: 'draft', running: true }),
    ])[0];
    expect(stageOf(g)).toBe('running');
  });

  it('judges by the chosen design, not the newest one', () => {
    // The lead is the pick; a newer unchosen sibling must not decide the stage.
    const g = groupVariants([
      ad({ id: 'a', selectedAt: '2026-09-02T00:00:00.000Z', status: 'ready' }),
      ad({ id: 'b', status: 'draft', updatedAt: '2026-09-09T00:00:00.000Z' }),
    ])[0];
    expect(stageOf(g)).toBe('approved');
  });

  it('treats a hand-built ready ad as approved', () => {
    expect(
      stageOf(one(ad({ id: 'h', offerGroupKey: null, autoGenerated: false, status: 'ready' }))),
    ).toBe('approved');
  });
});

describe('isWaitingOnSomeone', () => {
  it('is the split the list is organized around', () => {
    expect(isWaitingOnSomeone('needs_pick')).toBe(true);
    expect(isWaitingOnSomeone('needs_approval')).toBe(true);
    expect(isWaitingOnSomeone('approved')).toBe(false);
    expect(isWaitingOnSomeone('running')).toBe(false);
  });
});

describe('countByStage', () => {
  it('returns every key even at zero, so the tabs keep a stable shape', () => {
    expect(countByStage([])).toEqual({
      needs_pick: 0,
      needs_approval: 0,
      approved: 0,
      running: 0,
    });
  });

  it('tallies one per group, not per design', () => {
    const groups = groupVariants([
      ad({ id: 'a' }),
      ad({ id: 'b' }),
      ad({ id: 'c' }),
      ad({ id: 'd', offerGroupKey: 'g2', status: 'ready', running: true }),
      ad({ id: 'e', offerGroupKey: null, status: 'ready' }),
    ]);
    expect(countByStage(groups)).toEqual({
      needs_pick: 1,
      needs_approval: 0,
      approved: 1,
      running: 1,
    });
  });
});

describe('tallyStages', () => {
  it('returns every key even for an empty list', () => {
    expect(tallyStages([])).toEqual({
      needs_pick: 0,
      needs_approval: 0,
      approved: 0,
      running: 0,
    });
  });

  it('counts a mixed list of ad and email stages', () => {
    // The client's folder header tallies ads AND the run's offer email, so this
    // has to work on bare stages rather than on offer groups.
    expect(tallyStages(['needs_pick', 'needs_approval', 'needs_approval', 'running'])).toEqual({
      needs_pick: 1,
      needs_approval: 2,
      approved: 0,
      running: 1,
    });
  });
});
