import type { DocElement, TemplateDoc } from './doc-types';
import type { FieldSpec } from './types';

/**
 * Template → ad design sync: the pure half.
 *
 * Loomi's default is copy-on-use — an ad owns a frozen snapshot of the template
 * it was built from, so later template edits never reach it. That is right for a
 * designer who took a library plate and made it theirs, and wrong for the
 * automated OEM-offer ads, where the template is the ONLY place a person can fix
 * fifty machine-built ads at once.
 *
 * So the link is per-ad state, not a per-template policy:
 *
 *   synced   — a template edit may be pushed into this ad
 *   detached — the ad owns its design; nothing overwrites it
 *
 * and editing an ad's own design detaches it. Customizing IS the opt-out, which
 * is why there's no separate switch for the user to get wrong.
 *
 * Everything here is pure and isomorphic (no prisma, no renderer), because the
 * ad list computes "is this ad behind its template?" in the browser from docs it
 * already has. The side-effecting half lives in `template-sync-apply.ts`.
 */

export type SyncState = 'synced' | 'detached';

/** The columns this module reasons about. */
export interface SyncableCreative {
  autoGenerated?: boolean | null;
  templateSync?: string | null;
  templateDocHash?: string | null;
  docEditedAt?: Date | string | null;
}

/**
 * Is this ad following its template?
 *
 * A NULL `templateSync` is not "unknown" — it's every row written before the
 * link existed, and it resolves to what that row already did in practice:
 * auto-generated ads were being silently overwritten by each generate run, and
 * hand-built ads never were. Reading the null this way is what lets the feature
 * ship with no backfill and no behavior change on existing data.
 */
export function resolveSyncState(row: SyncableCreative): SyncState {
  if (row.templateSync === 'synced') return 'synced';
  if (row.templateSync === 'detached') return 'detached';
  return row.autoGenerated ? 'synced' : 'detached';
}

// ── design hash ───────────────────────────────────────────────────────────────

/**
 * Stable JSON: object keys sorted at every depth.
 *
 * `JSON.stringify` preserves insertion order, so the same doc round-tripped
 * through the builder (which rebuilds objects constantly) would serialize
 * differently and hash differently. That would mark every ad stale on a save
 * that changed nothing — the exact false alarm that gets a prompt dismissed
 * unread.
 */
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    // Drop undefined the way JSON.stringify does, so `{a: undefined}` and `{}`
    // are the same design.
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`).join(',')}}`;
}

/**
 * The part of a doc that affects what an ad RENDERS.
 *
 * Deliberately excludes the library metadata — id, name, description, category,
 * tags, industries, schedule, make. Renaming a template or adding a tag must not
 * report every ad built from it as out of date; only a change that would produce
 * different pixels counts. `defaults` is in because the renderer merges it under
 * the ad's data (see mergeRenderData), so editing a default changes output.
 */
function renderRelevant(doc: TemplateDoc): Record<string, unknown> {
  return {
    sizes: doc.sizes,
    fields: doc.fields,
    fieldGroups: doc.fieldGroups,
    background: doc.background,
    safeArea: doc.safeArea,
    elements: doc.elements,
    layouts: doc.layouts,
    overrides: doc.overrides,
    defaults: doc.defaults,
  };
}

/**
 * 64-bit FNV-1a-style digest of the render-relevant doc, as hex.
 *
 * Hand-rolled rather than `node:crypto` so this module stays usable in the
 * browser, where the ad list needs it. Two independent 32-bit accumulators with
 * different offset bases give ~2^-64 collision odds — and the only comparison
 * ever made is one template's current doc against the one revision an ad stored,
 * so a collision would mean a single missed "template updated" badge, not
 * corruption.
 */
export function designHash(doc: TemplateDoc): string {
  const s = stableStringify(renderRelevant(doc));
  let h1 = 0x811c9dc5;
  let h2 = 0x01000193;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    h1 ^= c;
    h1 = Math.imul(h1, 0x01000193);
    h2 = Math.imul(h2 ^ c, 0x85ebca6b);
    h2 ^= h2 >>> 13;
  }
  const hex = (n: number) => (n >>> 0).toString(16).padStart(8, '0');
  return `${hex(h1)}${hex(h2)}`;
}

/**
 * Is this ad's design behind the template's?
 *
 * Prefers hashing the ad's OWN doc, which is exact — an ad stores the design it
 * renders, so comparing that against the template's current design answers the
 * question outright, with no bookkeeping to trust. `templateDocHash` is the
 * fallback for an ad with no stored doc (older rows, code-rendered templates).
 *
 * When neither is available the answer is "no". An ad whose design can't be
 * established is not evidence that it's stale, and asserting otherwise would
 * light up every legacy row in the list on the day this ships.
 */
export function isBehindTemplate(
  row: SyncableCreative & { doc?: TemplateDoc | null },
  templateHash: string | null,
): boolean {
  if (!templateHash) return false;
  const own = row.doc ? designHash(row.doc) : row.templateDocHash;
  if (!own) return false;
  return own !== templateHash;
}

// ── change classification ─────────────────────────────────────────────────────

export type ChangeKind = 'none' | 'cosmetic' | 'structural';

export interface DocChange {
  kind: ChangeKind;
  /** Human-readable reasons, for the save-time prompt. Structural first. */
  reasons: string[];
}

/** Field keys an element pulls from the ad's data. */
function boundFieldKeys(elements: DocElement[]): Set<string> {
  const keys = new Set<string>();
  for (const el of elements) {
    if (el.binding?.kind === 'field' && el.binding.key) keys.add(el.binding.key);
  }
  return keys;
}

/**
 * The parts of a FieldSpec that decide what value it will accept and when it is
 * shown. A FieldSpec carries no `required` flag — requirement lives in the OEM
 * rules (see `requiredFieldsFor`) — so the contract is the type plus the
 * visibility condition, changing either of which can leave an existing ad's data
 * no longer fitting the design.
 */
function fieldContract(f: FieldSpec): string {
  return stableStringify({
    key: f.key,
    type: f.type,
    visibleWhen: f.visibleWhen,
    options: f.options?.map((o) => o.value),
  });
}

function added<T>(prev: Set<T>, next: Set<T>): T[] {
  return [...next].filter((v) => !prev.has(v));
}

function removed<T>(prev: Set<T>, next: Set<T>): T[] {
  return [...prev].filter((v) => !next.has(v));
}

function list(items: string[], limit = 4): string {
  if (items.length <= limit) return items.join(', ');
  return `${items.slice(0, limit).join(', ')} +${items.length - limit} more`;
}

/**
 * Classify a template edit by the RISK it carries to an existing ad, not by how
 * big it looks.
 *
 * - cosmetic: position, colour, font, static text, background. The ad's data
 *   still satisfies the design, so pushing it is safe and is the default.
 * - structural: the data contract moved — a field appeared or vanished, an
 *   element was rebound to a different field, a size was added or dropped, a
 *   `visibleWhen` changed. Existing ads may not have values for what the design
 *   now asks for, so the default flips to "don't apply" and the reasons are
 *   shown.
 *
 * Note what is NOT structural: adding or deleting a purely decorative element.
 * It changes the picture, but no ad's values stop fitting, so treating it as
 * risky would make the alarming case routine.
 */
export function classifyDocChange(prev: TemplateDoc, next: TemplateDoc): DocChange {
  if (designHash(prev) === designHash(next)) return { kind: 'none', reasons: [] };

  const structural: string[] = [];
  const cosmetic: string[] = [];

  // ── sizes ──
  const prevSizes = new Set(prev.sizes.map((s) => s.id));
  const nextSizes = new Set(next.sizes.map((s) => s.id));
  const sizeLabel = (id: string) =>
    next.sizes.find((s) => s.id === id)?.label ?? prev.sizes.find((s) => s.id === id)?.label ?? id;
  const sizesAdded = added(prevSizes, nextSizes);
  const sizesGone = removed(prevSizes, nextSizes);
  if (sizesAdded.length) {
    structural.push(`${sizesAdded.length} new size(s): ${list(sizesAdded.map(sizeLabel))} — existing ads have no render for them yet.`);
  }
  if (sizesGone.length) {
    structural.push(`${sizesGone.length} size(s) removed: ${list(sizesGone.map(sizeLabel))} — ads keep those renders only if they don't take the update.`);
  }

  // ── fields ──
  const prevFields = new Map(prev.fields.map((f) => [f.key, f]));
  const nextFields = new Map(next.fields.map((f) => [f.key, f]));
  const fieldsAdded = added(new Set(prevFields.keys()), new Set(nextFields.keys()));
  const fieldsGone = removed(new Set(prevFields.keys()), new Set(nextFields.keys()));
  if (fieldsAdded.length) {
    structural.push(`New field(s): ${list(fieldsAdded.map((k) => nextFields.get(k)?.label ?? k))}.`);
  }
  if (fieldsGone.length) {
    structural.push(`Field(s) removed: ${list(fieldsGone.map((k) => prevFields.get(k)?.label ?? k))}.`);
  }
  const contractChanged = [...nextFields.keys()].filter(
    (k) => prevFields.has(k) && fieldContract(prevFields.get(k)!) !== fieldContract(nextFields.get(k)!),
  );
  if (contractChanged.length) {
    structural.push(
      `Requirement or visibility rules changed on: ${list(contractChanged.map((k) => nextFields.get(k)?.label ?? k))}.`,
    );
  }

  // ── bindings ──
  const prevBound = boundFieldKeys(prev.elements);
  const nextBound = boundFieldKeys(next.elements);
  const boundAdded = added(prevBound, nextBound).filter((k) => !fieldsAdded.includes(k));
  const boundGone = removed(prevBound, nextBound).filter((k) => !fieldsGone.includes(k));
  if (boundAdded.length) {
    structural.push(`Now displays: ${list(boundAdded.map((k) => nextFields.get(k)?.label ?? k))}.`);
  }
  if (boundGone.length) {
    structural.push(`No longer displays: ${list(boundGone.map((k) => prevFields.get(k)?.label ?? k))}.`);
  }
  // An element kept but pointed at a different field: the same slot, different
  // value. Invisible in the two sets above when both keys are still used
  // somewhere, which is the common case for a designer fixing a mis-binding.
  const prevEls = new Map(prev.elements.map((e) => [e.id, e]));
  const rebound = next.elements.filter((e) => {
    const before = prevEls.get(e.id);
    if (!before) return false;
    const a = before.binding?.kind === 'field' ? before.binding.key : null;
    const b = e.binding?.kind === 'field' ? e.binding.key : null;
    return !!a && !!b && a !== b;
  });
  if (rebound.length) {
    structural.push(`${rebound.length} element(s) rebound to a different field.`);
  }

  // ── cosmetic remainder ──
  // Only described in aggregate: the prompt needs to convey "the design moved",
  // and a per-element diff would bury the structural findings that matter.
  const prevElIds = new Set(prev.elements.map((e) => e.id));
  const nextElIds = new Set(next.elements.map((e) => e.id));
  const elsAdded = added(prevElIds, nextElIds).length;
  const elsGone = removed(prevElIds, nextElIds).length;
  if (elsAdded) cosmetic.push(`${elsAdded} element(s) added.`);
  if (elsGone) cosmetic.push(`${elsGone} element(s) removed.`);
  const sharedIds = [...nextElIds].filter((id) => prevElIds.has(id));
  const restyled = sharedIds.filter(
    (id) => stableStringify(prevEls.get(id)) !== stableStringify(next.elements.find((e) => e.id === id)),
  ).length;
  if (restyled) cosmetic.push(`${restyled} element(s) restyled or re-worded.`);
  const layoutMoved = [...nextSizes].filter(
    (sid) => prevSizes.has(sid) && stableStringify(prev.layouts[sid]) !== stableStringify(next.layouts[sid]),
  ).length;
  if (layoutMoved) cosmetic.push(`Layout changed on ${layoutMoved} size(s).`);
  if (stableStringify(prev.background) !== stableStringify(next.background)) cosmetic.push('Background changed.');
  if (stableStringify(prev.defaults) !== stableStringify(next.defaults)) cosmetic.push('Default values changed.');

  const reasons = [...structural, ...cosmetic];
  return {
    kind: structural.length ? 'structural' : 'cosmetic',
    // Never return an empty reason list for a real change: the hashes differed,
    // so something moved, and a prompt that says "0 changes" reads as a bug.
    reasons: reasons.length ? reasons : ['The design changed.'],
  };
}
