import { describe, it, expect, vi, beforeEach } from 'vitest';

/**
 * The batch shares ONE Chromium across every ad, which is what took a 10-ad
 * request from 10 browser launches to 1. That sharing has a failure mode the
 * per-ad launch did not: a browser that dies stays dead, so every later ad
 * fails with "Session closed". It happened on the first live run of this code —
 * ad 1 died inside `Page.captureScreenshot` and ads 2 and 3 were collateral.
 *
 * These tests pin the two properties that must hold together: one launch for a
 * healthy run, and a replacement browser after a render failure.
 */

const launches: number[] = [];
let renderBehavior: (call: number) => void | Promise<void> = () => {};
let renderCalls = 0;

vi.mock('./render', () => ({
  openAdRenderSession: vi.fn(async () => {
    launches.push(Date.now());
    const id = launches.length;
    return { id, render: vi.fn(), renderToFile: vi.fn(), close: vi.fn(async () => {}) };
  }),
}));

// Stubbed so the render step is the only thing that can fail, and so nothing
// reaches Chromium, S3 or the font tables.
vi.mock('./render-creative', () => ({
  mergeRenderData: (_doc: unknown, data: unknown) => data,
  renderCreativeSizes: vi.fn(async () => {
    renderCalls += 1;
    await renderBehavior(renderCalls);
    return [{ sizeId: 'square', label: 'Square', width: 1080, height: 1080, png: Buffer.alloc(0) }];
  }),
  renderCreativeToS3: vi.fn(async () => []),
}));

vi.mock('@/lib/s3', () => ({ isS3Configured: () => false }));

const ads = ['a1', 'a2', 'a3'];

vi.mock('@/lib/prisma', () => ({
  prisma: {
    adCreative: {
      findUnique: vi.fn(async ({ where }: { where: { id: string } }) => ({
        id: where.id,
        name: `Ad ${where.id}`,
        accountKey: 'acct-1',
        templateId: 'tpl',
        // A design that differs from the one being applied, so the ad is
        // "behind" and actually gets rendered rather than short-circuiting.
        doc: JSON.stringify({ sizes: [], elements: [], layouts: {} }),
        data: JSON.stringify({}),
        status: 'draft',
        autoGenerated: true,
        templateSync: 'synced',
        templateDocHash: 'old-hash',
        reviewNotes: null,
      })),
      update: vi.fn(async () => ({})),
    },
  },
}));

import type { TemplateDoc } from './doc-types';
import { applyTemplateDocToCreatives } from './template-sync-apply';

const doc = {
  id: 'tpl',
  name: 'Test',
  sizes: [{ id: 'square', label: 'Square', width: 1080, height: 1080 }],
  fields: [],
  elements: [{ id: 'plate', type: 'shape' }],
  layouts: { square: { plate: { x: 0, y: 0, w: 1, h: 1 } } },
  defaults: {},
} as unknown as TemplateDoc;

beforeEach(() => {
  launches.length = 0;
  renderCalls = 0;
  renderBehavior = () => {};
});

describe('applyTemplateDocToCreatives — browser lifecycle', () => {
  it('launches Chromium once for the whole batch', async () => {
    const results = await applyTemplateDocToCreatives(ads, doc);
    expect(results.map((r) => r.outcome)).toEqual(['updated', 'updated', 'updated']);
    expect(launches).toHaveLength(1);
  });

  it('never launches a browser for an empty batch', async () => {
    await applyTemplateDocToCreatives([], doc);
    expect(launches).toHaveLength(0);
  });

  it('replaces the browser after a render failure, so later ads still land', async () => {
    // Exactly the observed crash: the first ad dies inside the screenshot.
    renderBehavior = (call) => {
      if (call === 1) throw new Error('Protocol error (Page.captureScreenshot): Target closed');
    };

    const results = await applyTemplateDocToCreatives(ads, doc);

    expect(results[0].outcome).toBe('failed');
    expect(results[0].renderFailed).toBe(true);
    // The whole point: the crash cost one ad, not the rest of the run.
    expect(results[1].outcome).toBe('updated');
    expect(results[2].outcome).toBe('updated');
    // One launch for the run, one replacement after the death. Not three.
    expect(launches).toHaveLength(2);
  });

  it('keeps going when every ad fails to render', async () => {
    renderBehavior = () => {
      throw new Error('Target closed');
    };
    const results = await applyTemplateDocToCreatives(ads, doc);
    expect(results.map((r) => r.outcome)).toEqual(['failed', 'failed', 'failed']);
    // A fresh browser per attempt, and no ad silently dropped.
    expect(results).toHaveLength(ads.length);
    expect(launches).toHaveLength(3);
  });

  it('does not recycle a session it borrowed from the caller', async () => {
    const borrowed = { render: vi.fn(), renderToFile: vi.fn(), close: vi.fn(async () => {}) };
    renderBehavior = (call) => {
      if (call === 1) throw new Error('Target closed');
    };

    await applyTemplateDocToCreatives(ads, doc, { session: borrowed });

    // The caller owns it: nothing here opens or closes a browser.
    expect(launches).toHaveLength(0);
    expect(borrowed.close).not.toHaveBeenCalled();
  });
});

describe('applyTemplateDocToCreatives — a wedged render', () => {
  /**
   * `page.screenshot()` takes no timeout and, under real resource pressure, can
   * simply never return — reproduced while several Chromium instances competed
   * for the machine. On the worker there is no request to die and take the hang
   * with it, so without a bound the first ad pins the run at 0 processed and the
   * queue entry stays `active` until pg-boss expires it an hour later.
   */
  it('gives up on an ad that never finishes rendering, and finishes the rest', async () => {
    vi.useFakeTimers();
    try {
      // A holder, because the assignment happens inside a nested closure that
      // TypeScript's flow analysis cannot see through.
      const hung: { release: (() => void) | null } = { release: null };
      renderBehavior = (call) => {
        // The first ad hangs forever; nothing resolves it.
        if (call === 1) return new Promise<void>((resolve) => { hung.release = resolve; });
      };

      const promise = applyTemplateDocToCreatives(ads, doc);
      // Let the hung render be entered, then push past the render bound.
      await vi.advanceTimersByTimeAsync(1);
      await vi.advanceTimersByTimeAsync(120_000);
      const results = await promise;

      expect(results[0].outcome).toBe('failed');
      expect(results[0].renderFailed).toBe(true);
      expect(results[0].detail).toMatch(/did not finish within 120s/);
      // The run is not held hostage by the one ad that wedged.
      expect(results[1].outcome).toBe('updated');
      expect(results[2].outcome).toBe('updated');
      // The wedged browser is replaced rather than reused.
      expect(launches).toHaveLength(2);

      // Releasing the abandoned render must not produce an unhandled rejection.
      hung.release?.();
    } finally {
      vi.useRealTimers();
    }
  });
});
