import { describe, it, expect } from 'vitest';
import type { TemplateDoc } from './doc-types';
import { classifyDocChange, designHash, isBehindTemplate, resolveSyncState } from './template-sync';

/** A minimal two-size doc with an offer-bound headline and a disclaimer. */
function doc(over: Partial<TemplateDoc> = {}): TemplateDoc {
  return {
    id: 't1',
    name: 'Test',
    sizes: [
      { id: 'square', label: 'Square', width: 1080, height: 1080 },
      { id: 'story', label: 'Story', width: 1080, height: 1920 },
    ],
    fields: [
      { key: 'monthlyPayment', label: 'Monthly payment', type: 'text' },
      { key: 'disclaimer', label: 'Disclaimer', type: 'textarea' },
    ],
    elements: [
      { id: 'pay', type: 'text', binding: { kind: 'field', key: 'monthlyPayment' }, color: '#111' },
      { id: 'disc', type: 'text', binding: { kind: 'field', key: 'disclaimer' } },
      { id: 'plate', type: 'shape' },
    ],
    layouts: {
      square: {
        pay: { x: 0.1, y: 0.1, w: 0.5, h: 0.2 },
        disc: { x: 0.05, y: 0.9, w: 0.9, h: 0.08 },
        plate: { x: 0, y: 0, w: 1, h: 1 },
      },
      story: {
        pay: { x: 0.1, y: 0.2, w: 0.6, h: 0.15 },
        disc: { x: 0.05, y: 0.92, w: 0.9, h: 0.06 },
        plate: { x: 0, y: 0, w: 1, h: 1 },
      },
    },
    defaults: { monthlyPayment: 'XXX', disclaimer: '' },
    ...over,
  };
}

describe('resolveSyncState', () => {
  it('reads a null as what the row already did — auto follows, hand-built does not', () => {
    // This is what lets the feature ship without backfilling every existing row.
    expect(resolveSyncState({ templateSync: null, autoGenerated: true })).toBe('synced');
    expect(resolveSyncState({ templateSync: null, autoGenerated: false })).toBe('detached');
  });

  it('honors an explicit value over the default', () => {
    expect(resolveSyncState({ templateSync: 'detached', autoGenerated: true })).toBe('detached');
    expect(resolveSyncState({ templateSync: 'synced', autoGenerated: false })).toBe('synced');
  });
});

describe('designHash', () => {
  it('ignores library metadata — renaming a template must not age every ad', () => {
    const a = doc();
    const b = doc({ name: 'Renamed', description: 'new blurb', category: 'Vehicle Offer', tags: ['aug'] });
    expect(designHash(b)).toBe(designHash(a));
  });

  it('ignores the publish schedule', () => {
    expect(designHash(doc({ schedule: { start: '2026-08-01', end: '2026-08-31' } }))).toBe(designHash(doc()));
  });

  it('is stable across key order — the builder rebuilds objects constantly', () => {
    const reordered: TemplateDoc = {
      ...doc(),
      // Same content, different insertion order.
      defaults: { disclaimer: '', monthlyPayment: 'XXX' },
    };
    expect(designHash(reordered)).toBe(designHash(doc()));
  });

  it('changes when a style changes', () => {
    const next = doc();
    next.elements = next.elements.map((e) => (e.id === 'pay' ? { ...e, color: '#f00' } : e));
    expect(designHash(next)).not.toBe(designHash(doc()));
  });

  it('changes when a layout moves', () => {
    const next = doc();
    next.layouts.square.pay = { x: 0.2, y: 0.1, w: 0.5, h: 0.2 };
    expect(designHash(next)).not.toBe(designHash(doc()));
  });

  it('changes when a default value changes — the renderer merges those', () => {
    expect(designHash(doc({ defaults: { monthlyPayment: '299', disclaimer: '' } }))).not.toBe(designHash(doc()));
  });
});

describe('isBehindTemplate', () => {
  it('treats an ad with neither a doc nor a recorded revision as up to date', () => {
    // Not knowing an ad's design isn't evidence that it's stale.
    expect(isBehindTemplate({ templateDocHash: null }, 'abc')).toBe(false);
  });

  it('falls back to the recorded hash when there is no stored doc', () => {
    expect(isBehindTemplate({ templateDocHash: 'abc' }, 'abc')).toBe(false);
    expect(isBehindTemplate({ templateDocHash: 'abc' }, 'def')).toBe(true);
  });

  it("prefers the ad's own doc over a missing or stale hash column", () => {
    // The doc is exact: an ad renders the design it stores. This is what lets ads
    // written before the hash column existed still be told their template moved.
    const ad = doc();
    expect(isBehindTemplate({ doc: ad, templateDocHash: null }, designHash(ad))).toBe(false);
    expect(isBehindTemplate({ doc: ad, templateDocHash: null }, 'something-else')).toBe(true);
    // A wrong hash column doesn't fool it either.
    expect(isBehindTemplate({ doc: ad, templateDocHash: 'stale' }, designHash(ad))).toBe(false);
  });
});

describe('classifyDocChange', () => {
  it('reports no change for the same design', () => {
    expect(classifyDocChange(doc(), doc()).kind).toBe('none');
  });

  it('calls a restyle cosmetic', () => {
    const next = doc();
    next.elements = next.elements.map((e) => (e.id === 'pay' ? { ...e, color: '#f00', fontWeight: 800 } : e));
    const change = classifyDocChange(doc(), next);
    expect(change.kind).toBe('cosmetic');
    expect(change.reasons.join(' ')).toMatch(/restyled/);
  });

  it('calls a move cosmetic', () => {
    const next = doc();
    next.layouts.story.pay = { x: 0.3, y: 0.3, w: 0.4, h: 0.1 };
    expect(classifyDocChange(doc(), next).kind).toBe('cosmetic');
  });

  it('calls a decorative element cosmetic — no ad stops fitting', () => {
    const next = doc();
    next.elements = [...next.elements, { id: 'flourish', type: 'shape' }];
    next.layouts.square.flourish = { x: 0.8, y: 0.8, w: 0.1, h: 0.1 };
    next.layouts.story.flourish = { x: 0.8, y: 0.8, w: 0.1, h: 0.1 };
    expect(classifyDocChange(doc(), next).kind).toBe('cosmetic');
  });

  it('calls a new field structural', () => {
    const next = doc();
    next.fields = [...next.fields, { key: 'dueAtSigning', label: 'Due at signing', type: 'text' }];
    const change = classifyDocChange(doc(), next);
    expect(change.kind).toBe('structural');
    expect(change.reasons[0]).toMatch(/Due at signing/);
  });

  it('calls a removed field structural', () => {
    const next = doc();
    next.fields = next.fields.filter((f) => f.key !== 'monthlyPayment');
    expect(classifyDocChange(doc(), next).kind).toBe('structural');
  });

  it('calls a changed visibility rule structural', () => {
    const next = doc();
    next.fields = next.fields.map((f) =>
      f.key === 'monthlyPayment' ? { ...f, visibleWhen: { field: 'offerType', in: ['lease'] } } : f,
    );
    const change = classifyDocChange(doc(), next);
    expect(change.kind).toBe('structural');
    expect(change.reasons.join(' ')).toMatch(/visibility/i);
  });

  it('calls a rebound element structural — same slot, different value', () => {
    const next = doc();
    next.fields = [...next.fields, { key: 'aprRate', label: 'APR rate', type: 'text' }];
    next.elements = next.elements.map((e) =>
      e.id === 'pay' ? { ...e, binding: { kind: 'field' as const, key: 'aprRate' } } : e,
    );
    const change = classifyDocChange(doc(), next);
    expect(change.kind).toBe('structural');
    expect(change.reasons.join(' ')).toMatch(/rebound/);
  });

  it('calls an added size structural — existing ads have no render for it', () => {
    const next = doc();
    next.sizes = [...next.sizes, { id: 'wide', label: 'Wide', width: 1200, height: 628 }];
    next.layouts.wide = { pay: { x: 0.1, y: 0.1, w: 0.4, h: 0.2 } };
    const change = classifyDocChange(doc(), next);
    expect(change.kind).toBe('structural');
    expect(change.reasons[0]).toMatch(/Wide/);
  });

  it('calls a removed size structural', () => {
    const next = doc();
    next.sizes = next.sizes.filter((s) => s.id !== 'story');
    delete next.layouts.story;
    expect(classifyDocChange(doc(), next).kind).toBe('structural');
  });

  it('never returns an empty reason list for a real change', () => {
    // A hash difference the classifier has no specific label for still has to say
    // something — a prompt reading "0 changes" looks like a bug.
    const next = doc({ safeArea: { value: 8, unit: 'percent' } });
    const change = classifyDocChange(doc(), next);
    expect(change.kind).not.toBe('none');
    expect(change.reasons.length).toBeGreaterThan(0);
  });

  it('leads with the structural reasons when a change is both', () => {
    const next = doc();
    next.fields = [...next.fields, { key: 'msrp', label: 'MSRP', type: 'text' }];
    next.layouts.square.disc = { x: 0.05, y: 0.8, w: 0.9, h: 0.08 };
    const change = classifyDocChange(doc(), next);
    expect(change.kind).toBe('structural');
    expect(change.reasons[0]).toMatch(/MSRP/);
    expect(change.reasons.join(' ')).toMatch(/Layout changed/);
  });
});
