/**
 * Grouping the ad list into "one offer, several designs".
 *
 * The offer fan-out turns one OEM offer into a design per published template, so
 * a flat list of ads stops being the right shape: eight rows that differ only by
 * plate read as eight ads rather than one choice. This folds them back into the
 * unit a dealer actually decides about — a vehicle and its offer — with the
 * designs as alternatives inside it.
 *
 * Pure and client-safe (no prisma, no Node), because the list page does the
 * grouping locally off the creatives it already fetched rather than asking the
 * server for a second, differently-shaped payload.
 */

/** The fields grouping needs. Deliberately a structural subset so the list
 *  page's richer row type satisfies it without a cast. */
export interface GroupableAd {
  id: string;
  name: string;
  templateId: string;
  status: string;
  updatedAt: string;
  autoGenerated?: boolean;
  /** Shared by every design built from the same vehicle + offer(s). */
  offerGroupKey?: string | null;
  /** The design the generator's resolution rules would have chosen alone. */
  recommended?: boolean;
  /** Set when a person chose this design out of its group. */
  selectedAt?: string | null;
  expiresAt?: string | null;
}

export interface VariantGroup<T extends GroupableAd> {
  /** `offerGroupKey`, or `solo:<id>` for an ad that belongs to no group. */
  key: string;
  /** The offer's name — every design in a group shares it. */
  name: string;
  /** Designs, best-first: chosen, then recommended, then newest. */
  variants: T[];
  /** The design a person picked, if any. */
  selected: T | null;
  /** The design the generator put first, if it is still present. */
  recommended: T | null;
  /** The one to show when the group is collapsed. Never null. */
  lead: T;
  /**
   * True when this is a real fan-out group the dealer must choose within.
   *
   * A single hand-built ad is a group of one and must NOT render as a choice —
   * "1 design" with a Compare button is noise. So is an automated offer that
   * only ever matched one template.
   */
  isChoice: boolean;
}

/**
 * Order designs within a group.
 *
 * A chosen design leads absolutely — once a person has decided, the ranking is
 * history and moving their pick out from under them would be perverse. Then the
 * generator's recommendation, then newest, then id so the order is total and a
 * re-render never reshuffles equal rows.
 */
function variantOrder<T extends GroupableAd>(a: T, b: T): number {
  const picked = (v: T) => (v.selectedAt ? 0 : 1);
  if (picked(a) !== picked(b)) return picked(a) - picked(b);
  const rec = (v: T) => (v.recommended ? 0 : 1);
  if (rec(a) !== rec(b)) return rec(a) - rec(b);
  const t = new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime();
  if (t !== 0) return t;
  return a.id.localeCompare(b.id);
}

/**
 * Fold a flat ad list into offer groups, preserving the list's existing order.
 *
 * Groups appear where their FIRST member appeared, so grouping never reorders
 * the page under a filter or sort the user chose — it only merges rows that were
 * already adjacent in meaning.
 *
 * An ad with no `offerGroupKey` — every hand-built ad, and everything generated
 * before the fan-out — becomes its own group of one and renders exactly as it
 * always did.
 */
export function groupVariants<T extends GroupableAd>(ads: T[]): VariantGroup<T>[] {
  const order: string[] = [];
  const buckets = new Map<string, T[]>();

  for (const ad of ads) {
    const key = ad.offerGroupKey?.trim() ? `g:${ad.offerGroupKey}` : `solo:${ad.id}`;
    const bucket = buckets.get(key);
    if (bucket) {
      bucket.push(ad);
    } else {
      buckets.set(key, [ad]);
      order.push(key);
    }
  }

  return order.map((key) => {
    const variants = [...buckets.get(key)!].sort(variantOrder);
    const selected = variants.find((v) => v.selectedAt) ?? null;
    const recommended = variants.find((v) => v.recommended) ?? null;
    return {
      key,
      name: variants[0].name,
      variants,
      selected,
      recommended,
      lead: variants[0],
      isChoice: variants.length > 1,
    };
  });
}

/**
 * How many designs in this group still need a decision.
 *
 * Drives the "needs a pick" filter. A group with a chosen design is settled even
 * if its siblings are technically still around — the dealer has decided, and the
 * archive sweep is what clears the rest.
 */
export function awaitingPick<T extends GroupableAd>(groups: VariantGroup<T>[]): VariantGroup<T>[] {
  return groups.filter((g) => g.isChoice && !g.selected);
}
