import { describe, expect, it } from 'vitest';
import { awaitingPick, groupVariants, type GroupableAd } from './variant-groups';

function ad(over: Partial<GroupableAd> & { id: string }): GroupableAd {
  return {
    name: 'Traverse — $329/mo',
    templateId: 't1',
    status: 'draft',
    updatedAt: '2026-09-01T00:00:00.000Z',
    autoGenerated: true,
    offerGroupKey: 'g1',
    recommended: false,
    selectedAt: null,
    ...over,
  };
}

describe('groupVariants', () => {
  it('folds designs sharing an offer into one group', () => {
    const groups = groupVariants([ad({ id: 'a' }), ad({ id: 'b' }), ad({ id: 'c' })]);
    expect(groups).toHaveLength(1);
    expect(groups[0].variants).toHaveLength(3);
    expect(groups[0].isChoice).toBe(true);
  });

  it('keeps separate offers apart', () => {
    const groups = groupVariants([ad({ id: 'a' }), ad({ id: 'b', offerGroupKey: 'g2' })]);
    expect(groups).toHaveLength(2);
  });

  it('gives a hand-built ad its own group of one, not a choice', () => {
    // A single ad rendering as "1 design" with a Compare button is noise.
    const groups = groupVariants([ad({ id: 'solo', offerGroupKey: null, autoGenerated: false })]);
    expect(groups).toHaveLength(1);
    expect(groups[0].isChoice).toBe(false);
    expect(groups[0].lead.id).toBe('solo');
  });

  it('does not merge two ungrouped ads with each other', () => {
    // Both have a null key; keying on that alone would collapse every hand-built
    // ad in the account into one row.
    const groups = groupVariants([
      ad({ id: 'x', offerGroupKey: null }),
      ad({ id: 'y', offerGroupKey: null }),
    ]);
    expect(groups).toHaveLength(2);
  });

  it('treats an empty-string key as ungrouped', () => {
    const groups = groupVariants([
      ad({ id: 'x', offerGroupKey: '' }),
      ad({ id: 'y', offerGroupKey: '   ' }),
    ]);
    expect(groups).toHaveLength(2);
    expect(groups.every((g) => !g.isChoice)).toBe(true);
  });

  it('leads with the recommended design', () => {
    const groups = groupVariants([
      ad({ id: 'a' }),
      ad({ id: 'b', recommended: true }),
      ad({ id: 'c' }),
    ]);
    expect(groups[0].lead.id).toBe('b');
    expect(groups[0].recommended?.id).toBe('b');
  });

  it('leads with the chosen design over the recommended one', () => {
    // Once a person decides, the ranking is history — moving their pick out from
    // under them would be perverse.
    const groups = groupVariants([
      ad({ id: 'a', recommended: true }),
      ad({ id: 'b', selectedAt: '2026-09-02T00:00:00.000Z' }),
    ]);
    expect(groups[0].lead.id).toBe('b');
    expect(groups[0].selected?.id).toBe('b');
    expect(groups[0].recommended?.id).toBe('a');
  });

  it('falls back to newest, then id, so the order is total', () => {
    const groups = groupVariants([
      ad({ id: 'b', updatedAt: '2026-09-01T00:00:00.000Z' }),
      ad({ id: 'a', updatedAt: '2026-09-01T00:00:00.000Z' }),
      ad({ id: 'c', updatedAt: '2026-09-05T00:00:00.000Z' }),
    ]);
    expect(groups[0].variants.map((v) => v.id)).toEqual(['c', 'a', 'b']);
  });

  it('preserves the incoming list order of groups', () => {
    // Grouping must not reorder the page under a filter or sort the user chose.
    const groups = groupVariants([
      ad({ id: 'z', offerGroupKey: 'g9' }),
      ad({ id: 'a', offerGroupKey: 'g1' }),
      ad({ id: 'b', offerGroupKey: 'g9' }),
    ]);
    expect(groups.map((g) => g.key)).toEqual(['g:g9', 'g:g1']);
    expect(groups[0].variants).toHaveLength(2);
  });

  it('is empty for no ads', () => {
    expect(groupVariants([])).toEqual([]);
  });
});

describe('awaitingPick', () => {
  it('keeps only real groups with no choice made', () => {
    const groups = groupVariants([
      ad({ id: 'a' }),
      ad({ id: 'b' }),
      ad({ id: 'c', offerGroupKey: 'g2', selectedAt: '2026-09-02T00:00:00.000Z' }),
      ad({ id: 'd', offerGroupKey: 'g2' }),
      ad({ id: 'solo', offerGroupKey: null }),
    ]);
    expect(awaitingPick(groups).map((g) => g.key)).toEqual(['g:g1']);
  });
});
